{
  "abstract": [
    {
      "text": "Methods for managing the addition and removal of devices and responding to device changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ICDeviceBrowserDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICDeviceBrowserDelegate"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICDeviceBrowserDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "ICDeviceBrowserDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICDeviceBrowserDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowser/delegate": {
      "abstract": [
        {
          "text": "The object that acts as the delegate of the device browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)ICDeviceBrowserDelegate",
          "text": "ICDeviceBrowserDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowser/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowser/delegate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate": {
      "abstract": [
        {
          "text": "Methods for managing the addition and removal of devices and responding to device changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceBrowserDelegate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceBrowserDelegate"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceBrowserDelegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeName:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the name of a device changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceDidChangeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDevice",
          "text": "ICDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowser:deviceDidChangeName:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowser(_:deviceDidChangeName:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowser(_:devicedidchangename:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeSharingState:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the sharing state of a device changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceDidChangeSharingState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDevice",
          "text": "ICDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeSharingState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowser:deviceDidChangeSharingState:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowser(_:deviceDidChangeSharingState:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowser(_:devicedidchangesharingstate:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didAdd:moreComing:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a device has been added.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDevice",
          "text": "ICDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "moreComing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didAdd:moreComing:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowser:didAddDevice:moreComing:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deviceBrowser(_:didAdd:moreComing:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowser(_:didadd:morecoming:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didRemove:moreGoing:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a device has been removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDevice",
          "text": "ICDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "moreGoing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didRemove:moreGoing:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowser:didRemoveDevice:moreGoing:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deviceBrowser(_:didRemove:moreGoing:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowser(_:didremove:moregoing:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:requestsSelect:)": {
      "abstract": [
        {
          "text": "Tells the delegate when an event occurs on the device that may be of interest to the client application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requestsSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDevice",
          "text": "ICDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:requestsSelect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowser:requestsSelectDevice:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowser(_:requestsSelect:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowser(_:requestsselect:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidCancelSuspendOperations(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowserDidCancelSuspendOperations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidCancelSuspendOperations(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowserDidCancelSuspendOperations:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowserDidCancelSuspendOperations(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowserdidcancelsuspendoperations(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidEnumerateLocalDevices(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the device browser has completed sending ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didAdd:moreComing:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for all local devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowserDidEnumerateLocalDevices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidEnumerateLocalDevices(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowserDidEnumerateLocalDevices:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowserDidEnumerateLocalDevices(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowserdidenumeratelocaldevices(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidResumeOperations(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowserDidResumeOperations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidResumeOperations(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowserDidResumeOperations:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowserDidResumeOperations(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowserdidresumeoperations(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidSuspendOperations(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowserDidSuspendOperations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidSuspendOperations(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowserDidSuspendOperations:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowserDidSuspendOperations(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowserdidsuspendoperations(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserWillSuspendOperations(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceBrowserWillSuspendOperations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDeviceBrowser",
          "text": "ICDeviceBrowser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserWillSuspendOperations(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceBrowserWillSuspendOperations:"
        }
      ],
      "role": "symbol",
      "title": "deviceBrowserWillSuspendOperations(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicebrowserdelegate/devicebrowserwillsuspendoperations(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Device-Browsing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowser/delegate"
      ],
      "title": "Managing Device Browsing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adding-and-Removing-Devices",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didAdd:moreComing:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didRemove:moreGoing:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidEnumerateLocalDevices(_:)"
      ],
      "title": "Adding and Removing Devices"
    },
    {
      "anchor": "Responding-to-Device-Changes",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:requestsSelect:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeName:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeSharingState:)"
      ],
      "title": "Responding to Device Changes"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidCancelSuspendOperations(_:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidResumeOperations(_:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidSuspendOperations(_:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserWillSuspendOperations(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICDeviceBrowserDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceBrowserDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceBrowserDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adding-and-Removing-Devices",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didAdd:moreComing:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:didRemove:moreGoing:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidEnumerateLocalDevices(_:)"
              ],
              "title": "Adding and Removing Devices"
            },
            {
              "anchor": "Responding-to-Device-Changes",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:requestsSelect:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeName:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowser(_:deviceDidChangeSharingState:)"
              ],
              "title": "Responding to Device Changes"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidCancelSuspendOperations(_:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidResumeOperations(_:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserDidSuspendOperations(_:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowserDelegate/deviceBrowserWillSuspendOperations(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Device-Browsing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceBrowser/delegate"
              ],
              "title": "Managing Device Browsing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICDeviceBrowserDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidEnumerateLocalDevices(_:)/title",
          "value": "deviceBrowserDidEnumerateLocalDevices:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidEnumerateLocalDevices(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowserDidEnumerateLocalDevices:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:didAdd:moreComing:)/title",
          "value": "deviceBrowser:didAddDevice:moreComing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:didAdd:moreComing:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowser:didAddDevice:moreComing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserWillSuspendOperations(_:)/title",
          "value": "deviceBrowserWillSuspendOperations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserWillSuspendOperations(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowserWillSuspendOperations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidResumeOperations(_:)/title",
          "value": "deviceBrowserDidResumeOperations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidResumeOperations(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowserDidResumeOperations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidCancelSuspendOperations(_:)/title",
          "value": "deviceBrowserDidCancelSuspendOperations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidCancelSuspendOperations(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowserDidCancelSuspendOperations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate/title",
          "value": "ICDeviceBrowserDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceBrowserDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceBrowserDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidSuspendOperations(_:)/title",
          "value": "deviceBrowserDidSuspendOperations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowserDidSuspendOperations(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowserDidSuspendOperations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:deviceDidChangeSharingState:)/title",
          "value": "deviceBrowser:deviceDidChangeSharingState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:deviceDidChangeSharingState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowser:deviceDidChangeSharingState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:deviceDidChangeName:)/title",
          "value": "deviceBrowser:deviceDidChangeName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:deviceDidChangeName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowser:deviceDidChangeName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:requestsSelect:)/title",
          "value": "deviceBrowser:requestsSelectDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:requestsSelect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowser:requestsSelectDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowser~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowser~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:didRemove:moreGoing:)/title",
          "value": "deviceBrowser:didRemoveDevice:moreGoing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceBrowserDelegate~1deviceBrowser(_:didRemove:moreGoing:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceBrowser:didRemoveDevice:moreGoing:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicebrowserdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicebrowserdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
