{
  "abstract": [
    {
      "text": "Options for the location of the image capture device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ICDeviceLocationOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICDeviceLocationOptions"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICDeviceLocationOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ICDeviceLocationOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICDeviceLocationOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/locationDescription": {
      "abstract": [
        {
          "text": "A nonlocalized location description for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/locationDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationDescription"
        }
      ],
      "role": "symbol",
      "title": "locationDescription",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/locationdescription"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/modulePath": {
      "abstract": [
        {
          "text": "The file system path of the device module associated with this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modulePath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/modulePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modulePath"
        }
      ],
      "role": "symbol",
      "title": "modulePath",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/modulepath"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/moduleVersion": {
      "abstract": [
        {
          "text": "The bundle version of the device module associated with this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moduleVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/moduleVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moduleVersion"
        }
      ],
      "role": "symbol",
      "title": "moduleVersion",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/moduleversion"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/type": {
      "abstract": [
        {
          "text": "A combination of the device’s type and its location type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICDeviceType",
          "text": "ICDeviceType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/type"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbLocationID": {
      "abstract": [
        {
          "text": "The USB location that the device is occupying.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usbLocationID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbLocationID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usbLocationID"
        }
      ],
      "role": "symbol",
      "title": "usbLocationID",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/usblocationid"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbProductID": {
      "abstract": [
        {
          "text": "The USB Product ID (PID) associated with the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usbProductID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbProductID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usbProductID"
        }
      ],
      "role": "symbol",
      "title": "usbProductID",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/usbproductid"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbVendorID": {
      "abstract": [
        {
          "text": "The USB Vendor ID (VID) associated with the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usbVendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbVendorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usbVendorID"
        }
      ],
      "role": "symbol",
      "title": "usbVendorID",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/usbvendorid"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions": {
      "abstract": [
        {
          "text": "Options for the location of the image capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceLocationOptions"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationOptions"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationOptions",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationoptions"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionBluetooth": {
      "abstract": [
        {
          "text": "A paired Bluetooth device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionBluetooth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceLocationOptions",
          "text": "ICDeviceLocationOptions"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionBluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationDescriptionBluetooth"
        }
      ],
      "role": "symbol",
      "title": "descriptionBluetooth",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationoptions/descriptionbluetooth"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionFireWire": {
      "abstract": [
        {
          "text": "A device that’s directly attached to the Mac through its FireWire port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceLocationOptions",
          "text": "ICDeviceLocationOptions"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionFireWire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationDescriptionFireWire"
        }
      ],
      "role": "symbol",
      "title": "descriptionFireWire",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationoptions/descriptionfirewire"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionMassStorage": {
      "abstract": [
        {
          "text": "A mass storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionMassStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceLocationOptions",
          "text": "ICDeviceLocationOptions"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionMassStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationDescriptionMassStorage"
        }
      ],
      "role": "symbol",
      "title": "descriptionMassStorage",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationoptions/descriptionmassstorage"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionUSB": {
      "abstract": [
        {
          "text": "A device that’s directly attached to the Mac through its USB port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptionUSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceLocationOptions",
          "text": "ICDeviceLocationOptions"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionUSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationDescriptionUSB"
        }
      ],
      "role": "symbol",
      "title": "descriptionUSB",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationoptions/descriptionusb"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates ImageCaptureCore location options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationoptions/init(rawvalue:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationType": {
      "abstract": [
        {
          "text": "The location of the image capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceLocationType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationType"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask": {
      "abstract": [
        {
          "text": "Masks for detecting different device locations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMask"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceLocationTypeMask"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceLocationTypeMask",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicelocationtypemask"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceType": {
      "abstract": [
        {
          "text": "The type of image capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceType"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicetype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTypeMask": {
      "abstract": [
        {
          "text": "Masks for detecting different device types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceTypeMask"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceTypeMask"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceTypeMask",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicetypemask"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Devices-Type-and-Location",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/type",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceType",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTypeMask",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/locationDescription",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/modulePath",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/moduleVersion",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationType",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbLocationID",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbProductID",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbVendorID"
      ],
      "title": "Inspecting a Device’s Type and Location"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Location-Options",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/init(rawValue:)"
      ],
      "title": "Creating Location Options"
    },
    {
      "anchor": "Determining-a-Location",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionBluetooth",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionFireWire",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionMassStorage",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionUSB"
      ],
      "title": "Determining a Location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICDeviceLocationOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-a-Location",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionBluetooth",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionFireWire",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionMassStorage",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationOptions/descriptionUSB"
              ],
              "title": "Determining a Location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Devices-Type-and-Location",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/type",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceType",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTypeMask",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/locationDescription",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/modulePath",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/moduleVersion",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationType",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceLocationTypeMask",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbLocationID",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbProductID",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/usbVendorID"
              ],
              "title": "Inspecting a Device’s Type and Location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICDeviceLocationOptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1usbProductID/title",
          "value": "usbProductID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1usbProductID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usbProductID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionBluetooth/title",
          "value": "ICDeviceLocationDescriptionBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionBluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationDescriptionBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask/title",
          "value": "ICDeviceLocationTypeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationType/title",
          "value": "ICDeviceLocationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTypeMask/title",
          "value": "ICDeviceTypeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceTypeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1locationDescription/title",
          "value": "locationDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1locationDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locationDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1modulePath/title",
          "value": "modulePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1modulePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modulePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceType/title",
          "value": "ICDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions/title",
          "value": "ICDeviceLocationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1moduleVersion/title",
          "value": "moduleVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1moduleVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "moduleVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionUSB/title",
          "value": "ICDeviceLocationDescriptionUSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionUSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationDescriptionUSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionFireWire/title",
          "value": "ICDeviceLocationDescriptionFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionFireWire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationDescriptionFireWire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1usbLocationID/title",
          "value": "usbLocationID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1usbLocationID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usbLocationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1usbVendorID/title",
          "value": "usbVendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1usbVendorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usbVendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionMassStorage/title",
          "value": "ICDeviceLocationDescriptionMassStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceLocationOptions~1descriptionMassStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceLocationDescriptionMassStorage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicelocationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicelocationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
