{
  "abstract": [
    {
      "text": "Constants that describe the capabilities of a camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ICDeviceCapability",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICDeviceCapability"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICDeviceCapability"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ICDeviceCapability"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICDeviceCapability"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/capabilities": {
      "abstract": [
        {
          "text": "The capabilities of the device as reported by the device module.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capabilities"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/capabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capabilities"
        }
      ],
      "role": "symbol",
      "title": "capabilities",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice/capabilities"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability": {
      "abstract": [
        {
          "text": "Constants that describe the capabilities of a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceCapability"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceCapability",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanAcceptPTPCommands": {
      "abstract": [
        {
          "text": "Indicates that the camera can accept PTP commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceCanAcceptPTPCommands"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanAcceptPTPCommands",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceCanAcceptPTPCommands"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceCanAcceptPTPCommands",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicecanacceptptpcommands"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteAllFiles": {
      "abstract": [
        {
          "text": "Indicates that the camera can delete all files in a single operation while it is connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceCanDeleteAllFiles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteAllFiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceCanDeleteAllFiles"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceCanDeleteAllFiles",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicecandeleteallfiles"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteOneFile": {
      "abstract": [
        {
          "text": "Indicates that the camera can delete a file at a time while it is connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceCanDeleteOneFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteOneFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceCanDeleteOneFile"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceCanDeleteOneFile",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicecandeleteonefile"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanReceiveFile": {
      "abstract": [
        {
          "text": "Indicates that the host can upload files to the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceCanReceiveFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanReceiveFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceCanReceiveFile"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceCanReceiveFile",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicecanreceivefile"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanSyncClock": {
      "abstract": [
        {
          "text": "Indicates that the camera can synchronize its date and time with that of the host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceCanSyncClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanSyncClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceCanSyncClock"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceCanSyncClock",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicecansyncclock"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePicture": {
      "abstract": [
        {
          "text": "The capability for the client to request to take a picture while the camera is connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceCanTakePicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceCanTakePicture"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceCanTakePicture",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicecantakepicture"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePictureUsingShutterReleaseOnCamera": {
      "abstract": [
        {
          "text": "The capability to capture a picture if the user presses the shutter release on the camera while the camera is connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceCanTakePictureUsingShutterReleaseOnCamera"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePictureUsingShutterReleaseOnCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceCanTakePictureUsingShutterReleaseOnCamera"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceCanTakePictureUsingShutterReleaseOnCamera",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicecantakepictureusingshutterreleaseoncamera"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/canEjectOrDisconnect": {
      "abstract": [
        {
          "text": "Indicates that the camera can eject or disconnect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canEjectOrDisconnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/canEjectOrDisconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceCanEjectOrDisconnect"
        }
      ],
      "role": "symbol",
      "title": "canEjectOrDisconnect",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/canejectordisconnect"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an ImageCaptureCore device capability.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/init(rawvalue:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICSessionOptions": {
      "abstract": [
        {
          "text": "Session options for altering the delivery of the device contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICSessionOptions"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICSessionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICSessionOptions"
        }
      ],
      "role": "symbol",
      "title": "ICSessionOptions",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icsessionoptions"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Devices-Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/capabilities",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICSessionOptions"
      ],
      "title": "Inspecting a Device’s Capabilities"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Device-Capabilities",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/init(rawValue:)"
      ],
      "title": "Creating Device Capabilities"
    },
    {
      "anchor": "Taking-Pictures",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePicture",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePictureUsingShutterReleaseOnCamera"
      ],
      "title": "Taking Pictures"
    },
    {
      "anchor": "Deleting-Files",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteOneFile",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteAllFiles"
      ],
      "title": "Deleting Files"
    },
    {
      "anchor": "Uploading-Files",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanReceiveFile"
      ],
      "title": "Uploading Files"
    },
    {
      "anchor": "Synchronizing-the-Clock",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanSyncClock"
      ],
      "title": "Synchronizing the Clock"
    },
    {
      "anchor": "Sending-PTP-Commands",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanAcceptPTPCommands"
      ],
      "title": "Sending PTP Commands"
    },
    {
      "anchor": "Disconnecting",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/canEjectOrDisconnect"
      ],
      "title": "Disconnecting"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICDeviceCapability"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Taking-Pictures",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePicture",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanTakePictureUsingShutterReleaseOnCamera"
              ],
              "title": "Taking Pictures"
            },
            {
              "anchor": "Deleting-Files",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteOneFile",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanDeleteAllFiles"
              ],
              "title": "Deleting Files"
            },
            {
              "anchor": "Uploading-Files",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanReceiveFile"
              ],
              "title": "Uploading Files"
            },
            {
              "anchor": "Synchronizing-the-Clock",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanSyncClock"
              ],
              "title": "Synchronizing the Clock"
            },
            {
              "anchor": "Sending-PTP-Commands",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceCanAcceptPTPCommands"
              ],
              "title": "Sending PTP Commands"
            },
            {
              "anchor": "Disconnecting",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/canEjectOrDisconnect"
              ],
              "title": "Disconnecting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Devices-Capabilities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice/capabilities",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICSessionOptions"
              ],
              "title": "Inspecting a Device’s Capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICDeviceCapability"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1canEjectOrDisconnect/title",
          "value": "ICDeviceCanEjectOrDisconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1canEjectOrDisconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceCanEjectOrDisconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanTakePicture/title",
          "value": "ICCameraDeviceCanTakePicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanTakePicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceCanTakePicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanTakePictureUsingShutterReleaseOnCamera/title",
          "value": "ICCameraDeviceCanTakePictureUsingShutterReleaseOnCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanTakePictureUsingShutterReleaseOnCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceCanTakePictureUsingShutterReleaseOnCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability/title",
          "value": "ICDeviceCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1capabilities/title",
          "value": "capabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice~1capabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICSessionOptions/title",
          "value": "ICSessionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICSessionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICSessionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICSessionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanSyncClock/title",
          "value": "ICCameraDeviceCanSyncClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanSyncClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceCanSyncClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanAcceptPTPCommands/title",
          "value": "ICCameraDeviceCanAcceptPTPCommands"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanAcceptPTPCommands/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceCanAcceptPTPCommands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanDeleteOneFile/title",
          "value": "ICCameraDeviceCanDeleteOneFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanDeleteOneFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceCanDeleteOneFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanReceiveFile/title",
          "value": "ICCameraDeviceCanReceiveFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanReceiveFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceCanReceiveFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanDeleteAllFiles/title",
          "value": "ICCameraDeviceCanDeleteAllFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceCanDeleteAllFiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceCanDeleteAllFiles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicecapability"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icdevicecapability"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
