{
  "abstract": [
    {
      "text": "The file’s orientation type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICEXIFOrientationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICEXIFOrientationType"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICEXIFOrientationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ICEXIFOrientationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The meaning of this value is defined by the ",
              "type": "text"
            },
            {
              "code": "EXIF",
              "type": "codeVoice"
            },
            {
              "text": " specification. Here is what the letter ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "F",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " would look like if it were tagged correctly and displayed by a program that ignores the orientation tag (thus showing the stored image):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "               1             2             3             4",
            "",
            "            8888888       8888888            88       88",
            "            88                 88            88       88",
            "            8888             8888          8888       8888",
            "            88                 88            88       88",
            "            88                 88       8888888       8888888",
            "",
            "               5             6             7             8",
            "",
            "            8888888888    88                    88    8888888888",
            "            88  88        88  88            88  88        88  88",
            "            88            8888888888    8888888888            88"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifCreationDate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "EXIF",
          "type": "codeVoice"
        },
        {
          "text": " creation date of the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exifCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exifCreationDate"
        }
      ],
      "role": "symbol",
      "title": "exifCreationDate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccamerafile/exifcreationdate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifModificationDate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "EXIF",
          "type": "codeVoice"
        },
        {
          "text": " modification date of the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exifModificationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifModificationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exifModificationDate"
        }
      ],
      "role": "symbol",
      "title": "exifModificationDate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccamerafile/exifmodificationdate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/orientation": {
      "abstract": [
        {
          "text": "The orientation to use when downloading the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICEXIFOrientationType",
          "text": "ICEXIFOrientationType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/orientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orientation"
        }
      ],
      "role": "symbol",
      "title": "orientation",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccamerafile/orientation"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType": {
      "abstract": [
        {
          "text": "The file’s orientation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICEXIFOrientationType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientationType"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/init(rawvalue:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1": {
      "abstract": [
        {
          "text": "Normal",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation1"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation1"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation1",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation1"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2": {
      "abstract": [
        {
          "text": "Flipped horizontally",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation2"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation2"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation2",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation2"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3": {
      "abstract": [
        {
          "text": "Rotated 180°",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation3"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation3"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation3",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation3"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4": {
      "abstract": [
        {
          "text": "Flipped vertically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation4"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation4"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation4",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation4"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation5": {
      "abstract": [
        {
          "text": "Rotated 90° CCW and flipped vertically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation5"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation5"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation5",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation5"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6": {
      "abstract": [
        {
          "text": "Rotated 90° CCW",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation6"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation6"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation6",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation6"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7": {
      "abstract": [
        {
          "text": "Rotated 90° CW and flipped vertically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation7"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation7"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation7",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation7"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8": {
      "abstract": [
        {
          "text": "Rotated 90° CW",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation8"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation8"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation8",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation8"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Files-EXIF-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/orientation",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifCreationDate",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifModificationDate"
      ],
      "title": "Inspecting a File’s EXIF Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation5",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICEXIFOrientationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation5",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Files-EXIF-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/orientation",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifCreationDate",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile/exifModificationDate"
              ],
              "title": "Inspecting a File’s EXIF Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICEXIFOrientationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1orientation/title",
          "value": "orientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation3/title",
          "value": "ICEXIFOrientation3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation4/title",
          "value": "ICEXIFOrientation4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation6/title",
          "value": "ICEXIFOrientation6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation7/title",
          "value": "ICEXIFOrientation7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation5/title",
          "value": "ICEXIFOrientation5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1exifCreationDate/title",
          "value": "exifCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1exifCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exifCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/title",
          "value": "ICEXIFOrientationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation1/title",
          "value": "ICEXIFOrientation1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation2/title",
          "value": "ICEXIFOrientation2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation8/title",
          "value": "ICEXIFOrientation8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1exifModificationDate/title",
          "value": "exifModificationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile~1exifModificationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exifModificationDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icexiforientationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icexiforientationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
