{
  "abstract": [
    {
      "text": "A legacy error returned from ImageCaptureCore.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ICLegacyReturn"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain": {
      "abstract": [
        {
          "text": "An error returned by the ImageCaptureCore framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ICErrorDomain",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icerrordomain"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn": {
      "abstract": [
        {
          "text": "A legacy error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ICLegacyReturn",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotYieldDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeCannotYieldDevice"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.cannotYieldDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/cannotyielddevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeCommunicationErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.communicationErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/communicationerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataTypeNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDataTypeNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.dataTypeNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/datatypenotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceAlreadyOpenErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceAlreadyOpenErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceAlreadyOpenErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicealreadyopenerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceGUIDNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceGUIDNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceGUIDNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceguidnotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIOServicePathNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceIOServicePathNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceIOServicePathNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceioservicepathnotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceInternalErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceInternalErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceInternalErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceinternalerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceInvalidParamErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceInvalidParamErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceInvalidParamErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceinvalidparamerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceLocationIDNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceLocationIDNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceLocationIDNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicelocationidnotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceMemoryAllocationErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceMemoryAllocationErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceMemoryAllocationErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicememoryallocationerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicenotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotOpenErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceNotOpenErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceNotOpenErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicenotopenerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceUnsupportedErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceUnsupportedErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceUnsupportedErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceunsupportederr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionInternalErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeExtensionInternalErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.extensionInternalErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/extensioninternalerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileCorruptedErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeFileCorruptedErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.fileCorruptedErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/filecorruptederr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/frameworkInternalErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameworkInternalErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/frameworkInternalErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeFrameworkInternalErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.frameworkInternalErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/frameworkinternalerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/indexOutOfRangeErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOutOfRangeErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/indexOutOfRangeErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeIndexOutOfRangeErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.indexOutOfRangeErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/indexoutofrangeerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidObjectErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidObjectErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidObjectErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeInvalidObjectErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.invalidObjectErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/invalidobjecterr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidPropertyErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPropertyErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidPropertyErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeInvalidPropertyErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.invalidPropertyErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/invalidpropertyerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidSessionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSessionErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidSessionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeInvalidSessionErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.invalidSessionErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/invalidsessionerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/ioPendingErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ioPendingErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/ioPendingErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeIOPendingErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.ioPendingErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/iopendingerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/propertyTypeNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyTypeNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/propertyTypeNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodePropertyTypeNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.propertyTypeNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/propertytypenotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn": {
      "abstract": [
        {
          "text": "An error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ICReturn",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError": {
      "abstract": [
        {
          "text": "A connection error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError": {
      "abstract": [
        {
          "text": "A download error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnDownloadError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDownloadError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnDownloadError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndownloaderror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError": {
      "abstract": [
        {
          "text": "A metadata error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError": {
      "abstract": [
        {
          "text": "An object error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnObjectError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnObjectError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnObjectError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnobjecterror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError": {
      "abstract": [
        {
          "text": "A PTP device error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnPTPDeviceError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnPTPDeviceError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnPTPDeviceError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnptpdeviceerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError": {
      "abstract": [
        {
          "text": "A thumbnail error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnThumbnailError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnThumbnailError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnThumbnailError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnthumbnailerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Details",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn"
      ],
      "title": "Error Details"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/frameworkInternalErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/indexOutOfRangeErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidObjectErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidPropertyErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidSessionErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/ioPendingErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/propertyTypeNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Details",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn"
              ],
              "title": "Error Details"
            },
            {
              "anchor": "Error-Domain",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain"
              ],
              "title": "Error Domain"
            },
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/frameworkInternalErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/indexOutOfRangeErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidObjectErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidPropertyErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidSessionErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/ioPendingErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/propertyTypeNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1cannotYieldDevice/title",
          "value": "ICLegacyReturnCodeCannotYieldDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1cannotYieldDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeCannotYieldDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidPropertyErr/title",
          "value": "ICLegacyReturnCodeInvalidPropertyErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidPropertyErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeInvalidPropertyErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidObjectErr/title",
          "value": "ICLegacyReturnCodeInvalidObjectErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidObjectErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeInvalidObjectErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1indexOutOfRangeErr/title",
          "value": "ICLegacyReturnCodeIndexOutOfRangeErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1indexOutOfRangeErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeIndexOutOfRangeErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceGUIDNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceGUIDNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceGUIDNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceGUIDNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1communicationErr/title",
          "value": "ICLegacyReturnCodeCommunicationErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1communicationErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeCommunicationErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceUnsupportedErr/title",
          "value": "ICLegacyReturnCodeDeviceUnsupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceUnsupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceUnsupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceAlreadyOpenErr/title",
          "value": "ICLegacyReturnCodeDeviceAlreadyOpenErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceAlreadyOpenErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceAlreadyOpenErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICErrorDomain/title",
          "value": "ICErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInvalidParamErr/title",
          "value": "ICLegacyReturnCodeDeviceInvalidParamErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInvalidParamErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceInvalidParamErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidSessionErr/title",
          "value": "ICLegacyReturnCodeInvalidSessionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidSessionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeInvalidSessionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotOpenErr/title",
          "value": "ICLegacyReturnCodeDeviceNotOpenErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotOpenErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceNotOpenErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1ioPendingErr/title",
          "value": "ICLegacyReturnCodeIOPendingErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1ioPendingErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeIOPendingErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceMemoryAllocationErr/title",
          "value": "ICLegacyReturnCodeDeviceMemoryAllocationErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceMemoryAllocationErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceMemoryAllocationErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1propertyTypeNotFoundErr/title",
          "value": "ICLegacyReturnCodePropertyTypeNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1propertyTypeNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodePropertyTypeNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1fileCorruptedErr/title",
          "value": "ICLegacyReturnCodeFileCorruptedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1fileCorruptedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeFileCorruptedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1dataTypeNotFoundErr/title",
          "value": "ICLegacyReturnCodeDataTypeNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1dataTypeNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDataTypeNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInternalErr/title",
          "value": "ICLegacyReturnCodeDeviceInternalErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInternalErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceInternalErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceIOServicePathNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceIOServicePathNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceIOServicePathNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceIOServicePathNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceLocationIDNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceLocationIDNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceLocationIDNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceLocationIDNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1extensionInternalErr/title",
          "value": "ICLegacyReturnCodeExtensionInternalErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1extensionInternalErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeExtensionInternalErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1frameworkInternalErr/title",
          "value": "ICLegacyReturnCodeFrameworkInternalErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1frameworkInternalErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeFrameworkInternalErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/title",
          "value": "ICLegacyReturnCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/iclegacyreturn"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/iclegacyreturn"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
