{
  "abstract": [
    {
      "text": "An error returned from ImageCaptureCore.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ICReturn"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain": {
      "abstract": [
        {
          "text": "An error returned by the ImageCaptureCore framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ICErrorDomain",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icerrordomain"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn": {
      "abstract": [
        {
          "text": "A legacy error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ICLegacyReturn",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn": {
      "abstract": [
        {
          "text": "An error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ICReturn",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationTimedOut"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCommunicationTimedOut"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.communicationTimedOut",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/communicationtimedout"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteFilesCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeleteFilesCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deleteFilesCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deletefilescanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteFilesFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeleteFilesFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deleteFilesFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deletefilesfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCommandGeneralFailure"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCommandGeneralFailure"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCommandGeneralFailure",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecommandgeneralfailure"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCouldNotPair"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCouldNotPair"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCouldNotPair",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecouldnotpair"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCouldNotUnpair"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCouldNotUnpair"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCouldNotUnpair",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecouldnotunpair"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToCloseSession"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToCloseSession"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToCloseSession",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtoclosesession"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer": {
      "abstract": [
        {
          "text": "Failed to complete a data transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToCompleteTransfer"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToCompleteTransfer"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToCompleteTransfer",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtocompletetransfer"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToOpenSession"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToOpenSession"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToOpenSession",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtoopensession"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData": {
      "abstract": [
        {
          "text": "Failed to send data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToSendData"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToSendData"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToSendData",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtosenddata"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToTakePicture"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToTakePicture"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToTakePicture",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtotakepicture"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIsBusyEnumerating"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceIsBusyEnumerating"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceIsBusyEnumerating",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceisbusyenumerating"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIsPasscodeLocked"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceIsPasscodeLocked"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceIsPasscodeLocked",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceispasscodelocked"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNeedsCredentials"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceNeedsCredentials"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceNeedsCredentials",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceneedscredentials"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareInstallationCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareInstallationCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareInstallationCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwareinstallationcanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCompleted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareInstallationCompleted"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCompleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareInstallationCompleted"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareInstallationCompleted",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwareinstallationcompleted"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareInstallationFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareInstallationFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareInstallationFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwareinstallationfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareIsBeingInstalled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareIsBeingInstalled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareIsBeingInstalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareIsBeingInstalled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareIsBeingInstalled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwareisbeinginstalled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareNotAvailable",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwarenotavailable"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotInstalled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareNotInstalled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotInstalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareNotInstalled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareNotInstalled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwarenotinstalled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDownloadCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.downloadCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/downloadcanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDownloadFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.downloadFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/downloadfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/exFATVolumeInvalid": {
      "abstract": [
        {
          "text": "EXFAT volume is invalid, and cannot be enumerated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exFATVolumeInvalid"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/exFATVolumeInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnExFATVolumeInvalid"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.exFATVolumeInvalid",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/exfatvolumeinvalid"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompletePassThroughCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToCompletePassThroughCommand"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompletePassThroughCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnFailedToCompletePassThroughCommand"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.failedToCompletePassThroughCommand",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/failedtocompletepassthroughcommand"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompleteSendMessageRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToCompleteSendMessageRequest"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompleteSendMessageRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnFailedToCompleteSendMessageRequest"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.failedToCompleteSendMessageRequest",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/failedtocompletesendmessagerequest"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToDisabeTethering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToDisabeTethering"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToDisabeTethering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnFailedToDisabeTethering"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.failedToDisabeTethering",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/failedtodisabetethering"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToEnabeTethering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToEnabeTethering"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToEnabeTethering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnFailedToEnabeTethering"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.failedToEnabeTethering",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/failedtoenabetethering"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/invalidParam": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParam"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/invalidParam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnInvalidParam"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.invalidParam",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/invalidparam"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/multiErrorDictionary": {
      "abstract": [
        {
          "text": "Multierror",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiErrorDictionary"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/multiErrorDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMultiErrorDictionary"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.multiErrorDictionary",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/multierrordictionary"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerErrorInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "receivedUnsolicitedScannerErrorInfo"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerErrorInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnReceivedUnsolicitedScannerErrorInfo"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.receivedUnsolicitedScannerErrorInfo",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/receivedunsolicitedscannererrorinfo"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerStatusInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "receivedUnsolicitedScannerStatusInfo"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerStatusInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnReceivedUnsolicitedScannerStatusInfo"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.receivedUnsolicitedScannerStatusInfo",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/receivedunsolicitedscannerstatusinfo"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scanOperationCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanOperationCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scanOperationCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnScanOperationCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.scanOperationCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/scanoperationcanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteOverviewScan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerFailedToCompleteOverviewScan"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteOverviewScan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnScannerFailedToCompleteOverviewScan"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.scannerFailedToCompleteOverviewScan",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/scannerfailedtocompleteoverviewscan"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteScan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerFailedToCompleteScan"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteScan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnScannerFailedToCompleteScan"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.scannerFailedToCompleteScan",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/scannerfailedtocompletescan"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToSelectFunctionalUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerFailedToSelectFunctionalUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToSelectFunctionalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnScannerFailedToSelectFunctionalUnit"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.scannerFailedToSelectFunctionalUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/scannerfailedtoselectfunctionalunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByLocalUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerInUseByLocalUser"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByLocalUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnScannerInUseByLocalUser"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.scannerInUseByLocalUser",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/scannerinusebylocaluser"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByRemoteUser": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerInUseByRemoteUser"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByRemoteUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnScannerInUseByRemoteUser"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.scannerInUseByRemoteUser",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/scannerinusebyremoteuser"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/sessionNotOpened": {
      "abstract": [
        {
          "text": "Session is not open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotOpened"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/sessionNotOpened",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnSessionNotOpened"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.sessionNotOpened",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/sessionnotopened"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/success": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnSuccess"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.success",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/success"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/uploadFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uploadFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/uploadFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnUploadFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.uploadFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/uploadfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnCodeOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError": {
      "abstract": [
        {
          "text": "A connection error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError": {
      "abstract": [
        {
          "text": "A download error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnDownloadError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDownloadError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnDownloadError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndownloaderror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError": {
      "abstract": [
        {
          "text": "A metadata error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError": {
      "abstract": [
        {
          "text": "An object error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnObjectError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnObjectError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnObjectError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnobjecterror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError": {
      "abstract": [
        {
          "text": "A PTP device error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnPTPDeviceError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnPTPDeviceError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnPTPDeviceError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnptpdeviceerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError": {
      "abstract": [
        {
          "text": "A thumbnail error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnThumbnailError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnThumbnailError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnThumbnailError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnthumbnailerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Details",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn"
      ],
      "title": "Error Details"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCompleted",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareIsBeingInstalled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotAvailable",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotInstalled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadCanceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/exFATVolumeInvalid",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompletePassThroughCommand",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompleteSendMessageRequest",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToDisabeTethering",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToEnabeTethering",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/invalidParam",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/multiErrorDictionary",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerErrorInfo",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerStatusInfo",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scanOperationCanceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteOverviewScan",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteScan",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToSelectFunctionalUnit",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByLocalUser",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByRemoteUser",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/sessionNotOpened",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/success",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/uploadFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Comparison-Operator",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn"
      ],
      "title": "Comparison Operator"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Details",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn"
              ],
              "title": "Error Details"
            },
            {
              "anchor": "Error-Domain",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain"
              ],
              "title": "Error Domain"
            },
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCompleted",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareIsBeingInstalled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotAvailable",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareNotInstalled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadCanceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/downloadFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/exFATVolumeInvalid",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompletePassThroughCommand",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToCompleteSendMessageRequest",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToDisabeTethering",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/failedToEnabeTethering",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/invalidParam",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/multiErrorDictionary",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerErrorInfo",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/receivedUnsolicitedScannerStatusInfo",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scanOperationCanceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteOverviewScan",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteScan",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToSelectFunctionalUnit",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByLocalUser",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerInUseByRemoteUser",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/sessionNotOpened",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/success",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/uploadFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code"
              ],
              "title": "Error Codes"
            },
            {
              "anchor": "Comparison-Operator",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn"
              ],
              "title": "Comparison Operator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceNeedsCredentials/title",
          "value": "ICReturnDeviceNeedsCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceNeedsCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceNeedsCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1uploadFailed/title",
          "value": "ICReturnUploadFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1uploadFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnUploadFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsBusyEnumerating/title",
          "value": "ICReturnDeviceIsBusyEnumerating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsBusyEnumerating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceIsBusyEnumerating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1receivedUnsolicitedScannerErrorInfo/title",
          "value": "ICReturnReceivedUnsolicitedScannerErrorInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1receivedUnsolicitedScannerErrorInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnReceivedUnsolicitedScannerErrorInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICErrorDomain/title",
          "value": "ICErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToTakePicture/title",
          "value": "ICReturnDeviceFailedToTakePicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToTakePicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToTakePicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerInUseByRemoteUser/title",
          "value": "ICReturnScannerInUseByRemoteUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerInUseByRemoteUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScannerInUseByRemoteUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareNotInstalled/title",
          "value": "ICReturnDeviceSoftwareNotInstalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareNotInstalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareNotInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotPair/title",
          "value": "ICReturnDeviceCouldNotPair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotPair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCouldNotPair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1success/title",
          "value": "ICReturnSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1multiErrorDictionary/title",
          "value": "ICReturnMultiErrorDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1multiErrorDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMultiErrorDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1exFATVolumeInvalid/title",
          "value": "ICReturnExFATVolumeInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1exFATVolumeInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnExFATVolumeInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1downloadCanceled/title",
          "value": "ICReturnDownloadCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1downloadCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDownloadCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerInUseByLocalUser/title",
          "value": "ICReturnScannerInUseByLocalUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerInUseByLocalUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScannerInUseByLocalUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToCompleteSendMessageRequest/title",
          "value": "ICReturnFailedToCompleteSendMessageRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToCompleteSendMessageRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnFailedToCompleteSendMessageRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToCompleteOverviewScan/title",
          "value": "ICReturnScannerFailedToCompleteOverviewScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToCompleteOverviewScan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScannerFailedToCompleteOverviewScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/title",
          "value": "ICReturnCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationFailed/title",
          "value": "ICReturnDeviceSoftwareInstallationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareInstallationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToCompletePassThroughCommand/title",
          "value": "ICReturnFailedToCompletePassThroughCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToCompletePassThroughCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnFailedToCompletePassThroughCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1communicationTimedOut/title",
          "value": "ICReturnCommunicationTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1communicationTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCommunicationTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCompleted/title",
          "value": "ICReturnDeviceSoftwareInstallationCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCompleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareInstallationCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToOpenSession/title",
          "value": "ICReturnDeviceFailedToOpenSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToOpenSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToOpenSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1sessionNotOpened/title",
          "value": "ICReturnSessionNotOpened"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1sessionNotOpened/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnSessionNotOpened"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1receivedUnsolicitedScannerStatusInfo/title",
          "value": "ICReturnReceivedUnsolicitedScannerStatusInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1receivedUnsolicitedScannerStatusInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnReceivedUnsolicitedScannerStatusInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToDisabeTethering/title",
          "value": "ICReturnFailedToDisabeTethering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToDisabeTethering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnFailedToDisabeTethering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToCompleteScan/title",
          "value": "ICReturnScannerFailedToCompleteScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToCompleteScan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScannerFailedToCompleteScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToSelectFunctionalUnit/title",
          "value": "ICReturnScannerFailedToSelectFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToSelectFunctionalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScannerFailedToSelectFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesFailed/title",
          "value": "ICReturnDeleteFilesFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeleteFilesFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCloseSession/title",
          "value": "ICReturnDeviceFailedToCloseSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCloseSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToCloseSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareIsBeingInstalled/title",
          "value": "ICReturnDeviceSoftwareIsBeingInstalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareIsBeingInstalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareIsBeingInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCanceled/title",
          "value": "ICReturnDeviceSoftwareInstallationCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareInstallationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1invalidParam/title",
          "value": "ICReturnInvalidParam"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1invalidParam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnInvalidParam"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCompleteTransfer/title",
          "value": "ICReturnDeviceFailedToCompleteTransfer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCompleteTransfer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToCompleteTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1downloadFailed/title",
          "value": "ICReturnDownloadFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1downloadFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDownloadFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scanOperationCanceled/title",
          "value": "ICReturnScanOperationCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scanOperationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScanOperationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareNotAvailable/title",
          "value": "ICReturnDeviceSoftwareNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToEnabeTethering/title",
          "value": "ICReturnFailedToEnabeTethering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1failedToEnabeTethering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnFailedToEnabeTethering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCommandGeneralFailure/title",
          "value": "ICReturnDeviceCommandGeneralFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCommandGeneralFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCommandGeneralFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesCanceled/title",
          "value": "ICReturnDeleteFilesCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeleteFilesCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToSendData/title",
          "value": "ICReturnDeviceFailedToSendData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToSendData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToSendData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/title",
          "value": "ICReturnCodeOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotUnpair/title",
          "value": "ICReturnDeviceCouldNotUnpair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotUnpair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCouldNotUnpair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsPasscodeLocked/title",
          "value": "ICReturnDeviceIsPasscodeLocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsPasscodeLocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceIsPasscodeLocked"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturn"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icreturn"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
