{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@ICReturnCodeOffset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICReturnCodeOffset"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICReturnCodeOffset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ICReturnCodeOffset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationTimedOut"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCommunicationTimedOut"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.communicationTimedOut",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/communicationtimedout"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteFilesCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeleteFilesCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deleteFilesCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deletefilescanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteFilesFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeleteFilesFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deleteFilesFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deletefilesfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCommandGeneralFailure"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCommandGeneralFailure"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCommandGeneralFailure",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecommandgeneralfailure"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCouldNotPair"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCouldNotPair"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCouldNotPair",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecouldnotpair"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCouldNotUnpair"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCouldNotUnpair"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCouldNotUnpair",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecouldnotunpair"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToCloseSession"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToCloseSession"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToCloseSession",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtoclosesession"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer": {
      "abstract": [
        {
          "text": "Failed to complete a data transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToCompleteTransfer"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToCompleteTransfer"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToCompleteTransfer",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtocompletetransfer"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToOpenSession"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToOpenSession"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToOpenSession",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtoopensession"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData": {
      "abstract": [
        {
          "text": "Failed to send data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToSendData"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToSendData"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToSendData",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtosenddata"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToTakePicture"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToTakePicture"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToTakePicture",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtotakepicture"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIsBusyEnumerating"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceIsBusyEnumerating"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceIsBusyEnumerating",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceisbusyenumerating"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIsPasscodeLocked"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceIsPasscodeLocked"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceIsPasscodeLocked",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceispasscodelocked"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNeedsCredentials"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceNeedsCredentials"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceNeedsCredentials",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceneedscredentials"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareInstallationCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareInstallationCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareInstallationCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwareinstallationcanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnCodeOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deleteOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deleteOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeDeleteOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.deleteOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/deleteoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceConnection"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeDeviceConnection"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.deviceConnection",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/deviceconnection"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeDeviceOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.deviceOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/deviceoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/downloadOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/downloadOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeDownloadOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.downloadOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/downloadoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/exFATOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exFATOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/exFATOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeExFATOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.exFATOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/exfatoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/init(rawvalue:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/metadataOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/metadataOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeMetadataOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.metadataOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/metadataoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/objectOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/objectOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeObjectOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.objectOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/objectoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/ptpOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ptpOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/ptpOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodePTPOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.ptpOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/ptpoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/systemOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/systemOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeSystemOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.systemOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/systemoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/thumbnailOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbnailOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/thumbnailOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeThumbnailOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset.thumbnailOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset/thumbnailoffset"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled"
      ],
      "title": "Error Codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deleteOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceConnection",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/downloadOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/exFATOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/metadataOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/objectOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/ptpOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/systemOffset",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/thumbnailOffset"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICReturnCodeOffset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deleteOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceConnection",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/deviceOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/downloadOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/exFATOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/metadataOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/objectOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/ptpOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/systemOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset/thumbnailOffset"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICReturnCodeOffset"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1ptpOffset/title",
          "value": "ICReturnCodePTPOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1ptpOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodePTPOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsPasscodeLocked/title",
          "value": "ICReturnDeviceIsPasscodeLocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsPasscodeLocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceIsPasscodeLocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/title",
          "value": "ICReturnCodeOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCompleteTransfer/title",
          "value": "ICReturnDeviceFailedToCompleteTransfer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCompleteTransfer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToCompleteTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToSendData/title",
          "value": "ICReturnDeviceFailedToSendData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToSendData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToSendData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsBusyEnumerating/title",
          "value": "ICReturnDeviceIsBusyEnumerating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsBusyEnumerating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceIsBusyEnumerating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCanceled/title",
          "value": "ICReturnDeviceSoftwareInstallationCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareInstallationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCloseSession/title",
          "value": "ICReturnDeviceFailedToCloseSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCloseSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToCloseSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1deleteOffset/title",
          "value": "ICReturnCodeDeleteOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1deleteOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeDeleteOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1communicationTimedOut/title",
          "value": "ICReturnCommunicationTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1communicationTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCommunicationTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesFailed/title",
          "value": "ICReturnDeleteFilesFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeleteFilesFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1exFATOffset/title",
          "value": "ICReturnCodeExFATOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1exFATOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeExFATOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToTakePicture/title",
          "value": "ICReturnDeviceFailedToTakePicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToTakePicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToTakePicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotPair/title",
          "value": "ICReturnDeviceCouldNotPair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotPair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCouldNotPair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1deviceOffset/title",
          "value": "ICReturnCodeDeviceOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1deviceOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeDeviceOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1thumbnailOffset/title",
          "value": "ICReturnCodeThumbnailOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1thumbnailOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeThumbnailOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1downloadOffset/title",
          "value": "ICReturnCodeDownloadOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1downloadOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeDownloadOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceNeedsCredentials/title",
          "value": "ICReturnDeviceNeedsCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceNeedsCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceNeedsCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesCanceled/title",
          "value": "ICReturnDeleteFilesCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeleteFilesCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotUnpair/title",
          "value": "ICReturnDeviceCouldNotUnpair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotUnpair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCouldNotUnpair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1metadataOffset/title",
          "value": "ICReturnCodeMetadataOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1metadataOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeMetadataOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1systemOffset/title",
          "value": "ICReturnCodeSystemOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1systemOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeSystemOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1objectOffset/title",
          "value": "ICReturnCodeObjectOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1objectOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeObjectOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToOpenSession/title",
          "value": "ICReturnDeviceFailedToOpenSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToOpenSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToOpenSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1deviceConnection/title",
          "value": "ICReturnCodeDeviceConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset~1deviceConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeDeviceConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCommandGeneralFailure/title",
          "value": "ICReturnDeviceCommandGeneralFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCommandGeneralFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCommandGeneralFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturncodeoffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icreturncodeoffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
