{
  "abstract": [
    {
      "text": "An object that represents a scanner.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ICScannerDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICScannerDevice"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICScannerDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ICScannerDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An instance of ICScannerDevice class is intended to be used by the ICScannerDeviceView object. The ICScannerDeviceView class encapsulates the complexities of setting scan parameters, performing scans and saving the result. The developer should consider using ICScannerDeviceView instead of building their own views using the ICScannerDevice object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice": {
      "abstract": [
        {
          "text": "An abstract object that represents a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDevice"
        }
      ],
      "role": "symbol",
      "title": "ICDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice": {
      "abstract": [
        {
          "text": "An object that represents a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes": {
      "abstract": [
        {
          "text": "An array of functional unit types available on this scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableFunctionalUnitTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableFunctionalUnitTypes"
        }
      ],
      "role": "symbol",
      "title": "availableFunctionalUnitTypes",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/availablefunctionalunittypes"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/cancelScan()": {
      "abstract": [
        {
          "text": "Cancels the current scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelScan"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/cancelScan()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelScan"
        }
      ],
      "role": "symbol",
      "title": "cancelScan()",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/cancelscan()"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/defaultUsername": {
      "abstract": [
        {
          "text": "A default username on protected scanners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultUsername"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/defaultUsername",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultUsername"
        }
      ],
      "role": "symbol",
      "title": "defaultUsername",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/defaultusername"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentName": {
      "abstract": [
        {
          "text": "The document’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentName"
        }
      ],
      "role": "symbol",
      "title": "documentName",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/documentname"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentUTI": {
      "abstract": [
        {
          "text": "The document’s uniform type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentUTI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentUTI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentUTI"
        }
      ],
      "role": "symbol",
      "title": "documentUTI",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/documentuti"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/downloadsDirectory": {
      "abstract": [
        {
          "text": "The downloads directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadsDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/downloadsDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downloadsDirectory"
        }
      ],
      "role": "symbol",
      "title": "downloadsDirectory",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/downloadsdirectory"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/maxMemoryBandSize": {
      "abstract": [
        {
          "text": "The total maximum band size requested when performing a memory-based transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxMemoryBandSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/maxMemoryBandSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxMemoryBandSize"
        }
      ],
      "role": "symbol",
      "title": "maxMemoryBandSize",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/maxmemorybandsize"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOpenSession(withCredentials:password:)": {
      "abstract": [
        {
          "text": "Opens a session on the protected device with the authorized username and passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestOpenSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOpenSession(withCredentials:password:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestOpenSessionWithCredentials:password:"
        }
      ],
      "role": "symbol",
      "title": "requestOpenSession(withCredentials:password:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/requestopensession(withcredentials:password:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOverviewScan()": {
      "abstract": [
        {
          "text": "Starts an overview scan on the selected functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestOverviewScan"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOverviewScan()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestOverviewScan"
        }
      ],
      "role": "symbol",
      "title": "requestOverviewScan()",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/requestoverviewscan()"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestScan()": {
      "abstract": [
        {
          "text": "Starts a scan on the selected functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestScan"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestScan()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestScan"
        }
      ],
      "role": "symbol",
      "title": "requestScan()",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/requestscan()"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)": {
      "abstract": [
        {
          "text": "Requests to select a functional unit on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSelect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerFunctionalUnitType",
          "text": "ICScannerFunctionalUnitType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestSelectFunctionalUnit:"
        }
      ],
      "role": "symbol",
      "title": "requestSelect(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/requestselect(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit": {
      "abstract": [
        {
          "text": "The currently selected functional unit on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedFunctionalUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerFunctionalUnit",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedFunctionalUnit"
        }
      ],
      "role": "symbol",
      "title": "selectedFunctionalUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/selectedfunctionalunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/transferMode": {
      "abstract": [
        {
          "text": "The transfer mode for the scanned document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerTransferMode",
          "text": "ICScannerTransferMode"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/transferMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transferMode"
        }
      ],
      "role": "symbol",
      "title": "transferMode",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/transfermode"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate": {
      "abstract": [
        {
          "text": "Methods for determining availability, selecting a functional unit, and performing scans on connected scanners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDeviceDelegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState": {
      "abstract": [
        {
          "text": "Flags to indicate the state of the scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitState"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitState"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitState",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitstate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType": {
      "abstract": [
        {
          "text": "The types of scanner functional units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunittype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration": {
      "abstract": [
        {
          "text": "Examine a scanner’s functional units and features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scanner Configuration",
      "type": "topic",
      "url": "/documentation/imagecapturecore/scanner-configuration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scanners",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration"
      ],
      "title": "Scanners"
    }
  ],
  "topicSections": [
    {
      "anchor": "Selecting-a-Functional-Unit",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState"
      ],
      "title": "Selecting a Functional Unit"
    },
    {
      "anchor": "Performing-a-Scan",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOpenSession(withCredentials:password:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOverviewScan()",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestScan()",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/cancelScan()",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentName",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentUTI",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/downloadsDirectory",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/transferMode",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/maxMemoryBandSize"
      ],
      "title": "Performing a Scan"
    },
    {
      "anchor": "Logging-into-a-Protected-Device",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/defaultUsername"
      ],
      "title": "Logging into a Protected Device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICScannerDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Selecting-a-Functional-Unit",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState"
              ],
              "title": "Selecting a Functional Unit"
            },
            {
              "anchor": "Performing-a-Scan",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOpenSession(withCredentials:password:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestOverviewScan()",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestScan()",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/cancelScan()",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentName",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/documentUTI",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/downloadsDirectory",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/transferMode",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/maxMemoryBandSize"
              ],
              "title": "Performing a Scan"
            },
            {
              "anchor": "Logging-into-a-Protected-Device",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/defaultUsername"
              ],
              "title": "Logging into a Protected Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scanners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration"
              ],
              "title": "Scanners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICScannerDevice"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDevice",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ICDevice",
                    "text": "ICDevice"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1transferMode/title",
          "value": "transferMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1transferMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestScan()/title",
          "value": "requestScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestScan()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/title",
          "value": "ICScannerDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestSelect(_:)/title",
          "value": "requestSelectFunctionalUnit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestSelect(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestSelectFunctionalUnit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/title",
          "value": "ICScannerDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestOverviewScan()/title",
          "value": "requestOverviewScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestOverviewScan()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestOverviewScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1availableFunctionalUnitTypes/title",
          "value": "availableFunctionalUnitTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1availableFunctionalUnitTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableFunctionalUnitTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1selectedFunctionalUnit/title",
          "value": "selectedFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1selectedFunctionalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1documentUTI/title",
          "value": "documentUTI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1documentUTI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentUTI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1documentName/title",
          "value": "documentName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1documentName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1maxMemoryBandSize/title",
          "value": "maxMemoryBandSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1maxMemoryBandSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxMemoryBandSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestOpenSession(withCredentials:password:)/title",
          "value": "requestOpenSessionWithCredentials:password:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestOpenSession(withCredentials:password:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestOpenSessionWithCredentials:password:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitState/title",
          "value": "ICScannerFunctionalUnitState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice/title",
          "value": "ICDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitType/title",
          "value": "ICScannerFunctionalUnitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1downloadsDirectory/title",
          "value": "downloadsDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1downloadsDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downloadsDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1defaultUsername/title",
          "value": "defaultUsername"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1defaultUsername/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultUsername"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1cancelScan()/title",
          "value": "cancelScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1cancelScan()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelScan"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
