{
  "abstract": [
    {
      "text": "An abstract class that represents a scanner functional unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ICScannerFunctionalUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICScannerFunctionalUnit"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICScannerFunctionalUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ICScannerFunctionalUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ImageCaptureCore framework defines four concrete subclasses of functional units:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " creates instances of these subclasses.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice": {
      "abstract": [
        {
          "text": "An object that represents a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit": {
      "abstract": [
        {
          "text": "An abstract class that represents a scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/acceptsThresholdForBlackAndWhiteScanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptsThresholdForBlackAndWhiteScanning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/acceptsThresholdForBlackAndWhiteScanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptsThresholdForBlackAndWhiteScanning"
        }
      ],
      "role": "symbol",
      "title": "acceptsThresholdForBlackAndWhiteScanning",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/acceptsthresholdforblackandwhitescanning"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/bitDepth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerBitDepth",
          "text": "ICScannerBitDepth"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/bitDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bitDepth"
        }
      ],
      "role": "symbol",
      "title": "bitDepth",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/bitdepth"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/canPerformOverviewScan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerformOverviewScan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/canPerformOverviewScan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformOverviewScan"
        }
      ],
      "role": "symbol",
      "title": "canPerformOverviewScan",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/canperformoverviewscan"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/defaultThresholdForBlackAndWhiteScanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultThresholdForBlackAndWhiteScanning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/defaultThresholdForBlackAndWhiteScanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultThresholdForBlackAndWhiteScanning"
        }
      ],
      "role": "symbol",
      "title": "defaultThresholdForBlackAndWhiteScanning",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/defaultthresholdforblackandwhitescanning"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/measurementUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measurementUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerMeasurementUnit",
          "text": "ICScannerMeasurementUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/measurementUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "measurementUnit"
        }
      ],
      "role": "symbol",
      "title": "measurementUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/measurementunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeXResolution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nativeXResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeXResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nativeXResolution"
        }
      ],
      "role": "symbol",
      "title": "nativeXResolution",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/nativexresolution"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeYResolution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nativeYResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeYResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nativeYResolution"
        }
      ],
      "role": "symbol",
      "title": "nativeYResolution",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/nativeyresolution"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overviewImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overviewImage"
        }
      ],
      "role": "symbol",
      "title": "overviewImage",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/overviewimage"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewResolution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overviewResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overviewResolution"
        }
      ],
      "role": "symbol",
      "title": "overviewResolution",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/overviewresolution"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewScanInProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overviewScanInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewScanInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overviewScanInProgress"
        }
      ],
      "role": "symbol",
      "title": "overviewScanInProgress",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/overviewscaninprogress"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/physicalSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/physicalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "physicalSize"
        }
      ],
      "role": "symbol",
      "title": "physicalSize",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/physicalsize"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/pixelDataType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelDataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerPixelDataType",
          "text": "ICScannerPixelDataType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/pixelDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelDataType"
        }
      ],
      "role": "symbol",
      "title": "pixelDataType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/pixeldatatype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredResolutions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredResolutions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredResolutions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredResolutions"
        }
      ],
      "role": "symbol",
      "title": "preferredResolutions",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/preferredresolutions"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredScaleFactors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredScaleFactors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredScaleFactors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredScaleFactors"
        }
      ],
      "role": "symbol",
      "title": "preferredScaleFactors",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/preferredscalefactors"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/resolution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/resolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolution"
        }
      ],
      "role": "symbol",
      "title": "resolution",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/resolution"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scaleFactor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleFactor"
        }
      ],
      "role": "symbol",
      "title": "scaleFactor",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/scalefactor"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanArea": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scanArea"
        }
      ],
      "role": "symbol",
      "title": "scanArea",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/scanarea"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanAreaOrientation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanAreaOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICEXIFOrientationType",
          "text": "ICEXIFOrientationType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanAreaOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scanAreaOrientation"
        }
      ],
      "role": "symbol",
      "title": "scanAreaOrientation",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/scanareaorientation"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanInProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scanInProgress"
        }
      ],
      "role": "symbol",
      "title": "scanInProgress",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/scaninprogress"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanProgressPercentDone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanProgressPercentDone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanProgressPercentDone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scanProgressPercentDone"
        }
      ],
      "role": "symbol",
      "title": "scanProgressPercentDone",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/scanprogresspercentdone"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/state": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerFunctionalUnitState",
          "text": "ICScannerFunctionalUnitState"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/state"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedBitDepths": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedBitDepths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedBitDepths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedBitDepths"
        }
      ],
      "role": "symbol",
      "title": "supportedBitDepths",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/supportedbitdepths"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedMeasurementUnits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedMeasurementUnits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedMeasurementUnits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedMeasurementUnits"
        }
      ],
      "role": "symbol",
      "title": "supportedMeasurementUnits",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/supportedmeasurementunits"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedResolutions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedResolutions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedResolutions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedResolutions"
        }
      ],
      "role": "symbol",
      "title": "supportedResolutions",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/supportedresolutions"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedScaleFactors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedScaleFactors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedScaleFactors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedScaleFactors"
        }
      ],
      "role": "symbol",
      "title": "supportedScaleFactors",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/supportedscalefactors"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/templates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templates"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerFeatureTemplate",
          "text": "ICScannerFeatureTemplate"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/templates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templates"
        }
      ],
      "role": "symbol",
      "title": "templates",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/templates"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/thresholdForBlackAndWhiteScanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thresholdForBlackAndWhiteScanning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/thresholdForBlackAndWhiteScanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thresholdForBlackAndWhiteScanning"
        }
      ],
      "role": "symbol",
      "title": "thresholdForBlackAndWhiteScanning",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/thresholdforblackandwhitescanning"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/type": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerFunctionalUnitType",
          "text": "ICScannerFunctionalUnitType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/type"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/usesThresholdForBlackAndWhiteScanning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesThresholdForBlackAndWhiteScanning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/usesThresholdForBlackAndWhiteScanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesThresholdForBlackAndWhiteScanning"
        }
      ],
      "role": "symbol",
      "title": "usesThresholdForBlackAndWhiteScanning",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/usesthresholdforblackandwhitescanning"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/vendorFeatures": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorFeatures"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerFeature",
          "text": "ICScannerFeature"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/vendorFeatures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorFeatures"
        }
      ],
      "role": "symbol",
      "title": "vendorFeatures",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit/vendorfeatures"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder": {
      "abstract": [
        {
          "text": "An object that represents the document feeder unit on a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitDocumentFeeder"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitDocumentFeeder"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitDocumentFeeder",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitdocumentfeeder"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed": {
      "abstract": [
        {
          "text": "An object that represents the flatbed unit on a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitFlatbed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitFlatbed"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitFlatbed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitflatbed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency": {
      "abstract": [
        {
          "text": "An object that represents the transparency unit for scanning negatives on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitNegativeTransparency"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitNegativeTransparency"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitNegativeTransparency",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitnegativetransparency"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency": {
      "abstract": [
        {
          "text": "An object that represents the transparency unit for scanning positives on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitPositiveTransparency"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitPositiveTransparency"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitPositiveTransparency",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitpositivetransparency"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode": {
      "abstract": [
        {
          "text": "The modes for transferring scan data from the scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerTransferMode"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerTransferMode"
        }
      ],
      "role": "symbol",
      "title": "ICScannerTransferMode",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannertransfermode"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functional-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode"
      ],
      "title": "Functional Units"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/acceptsThresholdForBlackAndWhiteScanning",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/bitDepth",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/canPerformOverviewScan",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/defaultThresholdForBlackAndWhiteScanning",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/measurementUnit",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeXResolution",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeYResolution",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewImage",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewResolution",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewScanInProgress",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/physicalSize",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/pixelDataType",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredResolutions",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredScaleFactors",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/resolution",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scaleFactor",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanArea",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanAreaOrientation",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanInProgress",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanProgressPercentDone",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/state",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedBitDepths",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedMeasurementUnits",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedResolutions",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedScaleFactors",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/templates",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/thresholdForBlackAndWhiteScanning",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/type",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/usesThresholdForBlackAndWhiteScanning",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/vendorFeatures"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICScannerFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/acceptsThresholdForBlackAndWhiteScanning",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/bitDepth",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/canPerformOverviewScan",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/defaultThresholdForBlackAndWhiteScanning",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/measurementUnit",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeXResolution",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/nativeYResolution",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewImage",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewResolution",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/overviewScanInProgress",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/physicalSize",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/pixelDataType",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredResolutions",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/preferredScaleFactors",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/resolution",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scaleFactor",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanArea",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanAreaOrientation",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanInProgress",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/scanProgressPercentDone",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/state",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedBitDepths",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedMeasurementUnits",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedResolutions",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/supportedScaleFactors",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/templates",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/thresholdForBlackAndWhiteScanning",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/type",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/usesThresholdForBlackAndWhiteScanning",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit/vendorFeatures"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functional-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode"
              ],
              "title": "Functional Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICScannerFunctionalUnit"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedResolutions/title",
          "value": "supportedResolutions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedResolutions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedResolutions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1overviewResolution/title",
          "value": "overviewResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1overviewResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overviewResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedMeasurementUnits/title",
          "value": "supportedMeasurementUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedMeasurementUnits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedMeasurementUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1overviewImage/title",
          "value": "overviewImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1overviewImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overviewImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scaleFactor/title",
          "value": "scaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1canPerformOverviewScan/title",
          "value": "canPerformOverviewScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1canPerformOverviewScan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canPerformOverviewScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1usesThresholdForBlackAndWhiteScanning/title",
          "value": "usesThresholdForBlackAndWhiteScanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1usesThresholdForBlackAndWhiteScanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesThresholdForBlackAndWhiteScanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1vendorFeatures/title",
          "value": "vendorFeatures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1vendorFeatures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorFeatures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanInProgress/title",
          "value": "scanInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scanInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1preferredScaleFactors/title",
          "value": "preferredScaleFactors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1preferredScaleFactors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredScaleFactors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1thresholdForBlackAndWhiteScanning/title",
          "value": "thresholdForBlackAndWhiteScanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1thresholdForBlackAndWhiteScanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "thresholdForBlackAndWhiteScanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1acceptsThresholdForBlackAndWhiteScanning/title",
          "value": "acceptsThresholdForBlackAndWhiteScanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1acceptsThresholdForBlackAndWhiteScanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptsThresholdForBlackAndWhiteScanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1resolution/title",
          "value": "resolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1resolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1pixelDataType/title",
          "value": "pixelDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1pixelDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedBitDepths/title",
          "value": "supportedBitDepths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedBitDepths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedBitDepths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanProgressPercentDone/title",
          "value": "scanProgressPercentDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanProgressPercentDone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scanProgressPercentDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1bitDepth/title",
          "value": "bitDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1bitDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1defaultThresholdForBlackAndWhiteScanning/title",
          "value": "defaultThresholdForBlackAndWhiteScanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1defaultThresholdForBlackAndWhiteScanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultThresholdForBlackAndWhiteScanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerTransferMode/title",
          "value": "ICScannerTransferMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerTransferMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerTransferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerTransferMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerTransferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1overviewScanInProgress/title",
          "value": "overviewScanInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1overviewScanInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overviewScanInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitNegativeTransparency/title",
          "value": "ICScannerFunctionalUnitNegativeTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitNegativeTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitNegativeTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitNegativeTransparency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitNegativeTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitFlatbed/title",
          "value": "ICScannerFunctionalUnitFlatbed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitFlatbed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitFlatbed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitFlatbed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitFlatbed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1nativeYResolution/title",
          "value": "nativeYResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1nativeYResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nativeYResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitPositiveTransparency/title",
          "value": "ICScannerFunctionalUnitPositiveTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitPositiveTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitPositiveTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitPositiveTransparency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitPositiveTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/title",
          "value": "ICScannerFunctionalUnitDocumentFeeder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitDocumentFeeder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitDocumentFeeder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1preferredResolutions/title",
          "value": "preferredResolutions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1preferredResolutions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredResolutions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanAreaOrientation/title",
          "value": "scanAreaOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanAreaOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scanAreaOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1nativeXResolution/title",
          "value": "nativeXResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1nativeXResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nativeXResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanArea/title",
          "value": "scanArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1scanArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scanArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/title",
          "value": "ICScannerFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1templates/title",
          "value": "templates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1templates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1physicalSize/title",
          "value": "physicalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1physicalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "physicalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1measurementUnit/title",
          "value": "measurementUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1measurementUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "measurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/title",
          "value": "ICScannerDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedScaleFactors/title",
          "value": "supportedScaleFactors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit~1supportedScaleFactors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedScaleFactors"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerfunctionalunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerfunctionalunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
