{
  "abstract": [
    {
      "text": "Methods for determining availability, selecting a functional unit, and performing scans on connected scanners.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ICScannerDeviceDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICScannerDeviceDelegate"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICScannerDeviceDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "ICScannerDeviceDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)ICDeviceDelegate",
              "text": "ICDeviceDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate": {
      "abstract": [
        {
          "text": "Methods for responding to device events and changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceDelegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicedelegate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice": {
      "abstract": [
        {
          "text": "An object that represents a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate": {
      "abstract": [
        {
          "text": "Methods for determining availability, selecting a functional unit, and performing scans on connected scanners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDeviceDelegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteOverviewScanWithError:)": {
      "abstract": [
        {
          "text": "Tells the client when the scanner completes an overview scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerDevice",
          "text": "ICScannerDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCompleteOverviewScanWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteOverviewScanWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDevice:didCompleteOverviewScanWithError:"
        }
      ],
      "role": "symbol",
      "title": "scannerDevice(_:didCompleteOverviewScanWithError:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice(_:didcompleteoverviewscanwitherror:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteScanWithError:)": {
      "abstract": [
        {
          "text": "Tells the client when the scanner completes a scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerDevice",
          "text": "ICScannerDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCompleteScanWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteScanWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDevice:didCompleteScanWithError:"
        }
      ],
      "role": "symbol",
      "title": "scannerDevice(_:didCompleteScanWithError:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice(_:didcompletescanwitherror:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-10whl": {
      "abstract": [
        {
          "text": "Tells the client when the scanner receives the requested scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerDevice",
          "text": "ICScannerDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didScanTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-10whl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDevice:didScanToURL:"
        }
      ],
      "role": "symbol",
      "title": "scannerDevice(_:didScanTo:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice(_:didscanto:)-10whl"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-6tht3": {
      "abstract": [
        {
          "text": "Tells the client when the scanner receives the requested scan progress notification and a band of data is sent for each notification received.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerDevice",
          "text": "ICScannerDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didScanTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerBandData",
          "text": "ICScannerBandData"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-6tht3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDevice:didScanToBandData:"
        }
      ],
      "role": "symbol",
      "title": "scannerDevice(_:didScanTo:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice(_:didscanto:)-6tht3"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didSelect:error:)": {
      "abstract": [
        {
          "text": "Tells the client when a functional unit is selected on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerDevice",
          "text": "ICScannerDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerFunctionalUnit",
          "text": "ICScannerFunctionalUnit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didSelect:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDevice:didSelectFunctionalUnit:error:"
        }
      ],
      "role": "symbol",
      "title": "scannerDevice(_:didSelect:error:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice(_:didselect:error:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice:didScanToURL:data:": {
      "abstract": [
        {
          "text": "Tells the client when the scanner device receives the requested scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "scannerDevice:didScanToURL:data:"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice:didScanToURL:data:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDevice:didScanToURL:data:"
        }
      ],
      "role": "symbol",
      "title": "scannerDevice:didScanToURL:data:",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevice:didscantourl:data:"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDeviceDidBecomeAvailable(_:)": {
      "abstract": [
        {
          "text": "Tells the client when another client closes the current open session on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerDeviceDidBecomeAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerDevice",
          "text": "ICScannerDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDeviceDidBecomeAvailable(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scannerDeviceDidBecomeAvailable:"
        }
      ],
      "role": "symbol",
      "title": "scannerDeviceDidBecomeAvailable(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate/scannerdevicedidbecomeavailable(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration": {
      "abstract": [
        {
          "text": "Examine a scanner’s functional units and features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scanner Configuration",
      "type": "topic",
      "url": "/documentation/imagecapturecore/scanner-configuration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scanners",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration"
      ],
      "title": "Scanners"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Scanner-Availability",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDeviceDidBecomeAvailable(_:)"
      ],
      "title": "Determining Scanner Availability"
    },
    {
      "anchor": "Selecting-a-Functional-Unit",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didSelect:error:)"
      ],
      "title": "Selecting a Functional Unit"
    },
    {
      "anchor": "Performing-a-Scan",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteOverviewScanWithError:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteScanWithError:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-6tht3",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-10whl"
      ],
      "title": "Performing a Scan"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICScannerDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-Scanner-Availability",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDeviceDidBecomeAvailable(_:)"
              ],
              "title": "Determining Scanner Availability"
            },
            {
              "anchor": "Selecting-a-Functional-Unit",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didSelect:error:)"
              ],
              "title": "Selecting a Functional Unit"
            },
            {
              "anchor": "Performing-a-Scan",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteOverviewScanWithError:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didCompleteScanWithError:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-6tht3",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice(_:didScanTo:)-10whl"
              ],
              "title": "Performing a Scan"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate/scannerDevice:didScanToURL:data:"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scanners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration"
              ],
              "title": "Scanners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICScannerDeviceDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)ICDeviceDelegate",
                    "text": "ICDeviceDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/title",
          "value": "ICScannerDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-10whl/title",
          "value": "scannerDevice:didScanToURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-10whl/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDevice:didScanToURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-6tht3/title",
          "value": "scannerDevice:didScanToBandData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didScanTo:)-6tht3/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDevice:didScanToBandData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didSelect:error:)/title",
          "value": "scannerDevice:didSelectFunctionalUnit:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didSelect:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDevice:didSelectFunctionalUnit:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDeviceDidBecomeAvailable(_:)/title",
          "value": "scannerDeviceDidBecomeAvailable:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDeviceDidBecomeAvailable(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDeviceDidBecomeAvailable:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/title",
          "value": "ICScannerDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didCompleteScanWithError:)/title",
          "value": "scannerDevice:didCompleteScanWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didCompleteScanWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDevice:didCompleteScanWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didCompleteOverviewScanWithError:)/title",
          "value": "scannerDevice:didCompleteOverviewScanWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate~1scannerDevice(_:didCompleteOverviewScanWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scannerDevice:didCompleteOverviewScanWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceDelegate/title",
          "value": "ICDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdevicedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdevicedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
