{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ImageCaptureCore Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ICAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icauthorizationstatus"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Constants",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-constants"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Enumerations",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-enumerations"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Macros",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-macros"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros"
      ],
      "title": "Articles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros"
              ],
              "title": "Articles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus/title",
          "value": "ICAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/imagecapturecore-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/imagecapturecore-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
