{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ImageCaptureCore Macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICPoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ICPoint"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "ICPoint",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icpoint"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICRect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ICRect"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "ICRect",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icrect"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDeviceIsAccessRestrictedAppleDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceIsAccessRestrictedAppleDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDeviceIsAccessRestrictedAppleDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "ICReturnDeviceIsAccessRestrictedAppleDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndeviceisaccessrestrictedappledevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnFailedToDisableTethering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ICReturnFailedToDisableTethering"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnFailedToDisableTethering",
      "kind": "symbol",
      "role": "symbol",
      "title": "ICReturnFailedToDisableTethering",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnfailedtodisabletethering"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnFailedToEnableTethering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ICReturnFailedToEnableTethering"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnFailedToEnableTethering",
      "kind": "symbol",
      "role": "symbol",
      "title": "ICReturnFailedToEnableTethering",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnfailedtoenabletethering"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ICSize"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "ICSize",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icsize"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IC_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "IC_AVAILABLE",
      "type": "topic",
      "url": "/documentation/imagecapturecore/ic_available"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IC_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "IC_DEPRECATED",
      "type": "topic",
      "url": "/documentation/imagecapturecore/ic_deprecated"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_DEPRECATED_WITH_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IC_DEPRECATED_WITH_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_DEPRECATED_WITH_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "IC_DEPRECATED_WITH_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/imagecapturecore/ic_deprecated_with_replacement"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IC_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "IC_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/imagecapturecore/ic_unavailable"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGECAPTURE_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGECAPTURE_EXTERN",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapture_extern"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGECAPTURE_IOS"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGECAPTURE_IOS",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapture_ios"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_OSX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGECAPTURE_IOS_OSX"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_OSX",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGECAPTURE_IOS_OSX",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapture_ios_osx"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_OSX_SIM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGECAPTURE_IOS_OSX_SIM"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_OSX_SIM",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGECAPTURE_IOS_OSX_SIM",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapture_ios_osx_sim"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_SIM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGECAPTURE_IOS_SIM"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_SIM",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGECAPTURE_IOS_SIM",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapture_ios_sim"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_PLATFORM_IOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGECAPTURE_PLATFORM_IOS"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_PLATFORM_IOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGECAPTURE_PLATFORM_IOS",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapture_platform_ios"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_PLATFORM_OSX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IMAGECAPTURE_PLATFORM_OSX"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_PLATFORM_OSX",
      "kind": "symbol",
      "role": "symbol",
      "title": "IMAGECAPTURE_PLATFORM_OSX",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapture_platform_osx"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/SuppressPerformSelectorLeakWarning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SuppressPerformSelectorLeakWarning"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/SuppressPerformSelectorLeakWarning",
      "kind": "symbol",
      "role": "symbol",
      "title": "SuppressPerformSelectorLeakWarning",
      "type": "topic",
      "url": "/documentation/imagecapturecore/suppressperformselectorleakwarning"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Constants",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-constants"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Data Types",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-data-types"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Enumerations",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations"
      ],
      "title": "Articles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICPoint",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICRect",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDeviceIsAccessRestrictedAppleDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnFailedToDisableTethering",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnFailedToEnableTethering",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICSize",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_AVAILABLE",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_DEPRECATED",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_DEPRECATED_WITH_REPLACEMENT",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IC_UNAVAILABLE",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_EXTERN",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_OSX",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_OSX_SIM",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_IOS_SIM",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_PLATFORM_IOS",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/IMAGECAPTURE_PLATFORM_OSX",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/SuppressPerformSelectorLeakWarning"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations"
              ],
              "title": "Articles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/imagecapturecore-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/imagecapturecore-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
