{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ImageCaptureCore Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICMediaPresentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICMediaPresentation"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICMediaPresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICMediaPresentation"
        }
      ],
      "role": "symbol",
      "title": "ICMediaPresentation",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icmediapresentation"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnCodeOffset"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCodeOffset"
        }
      ],
      "role": "symbol",
      "title": "ICReturnCodeOffset",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturncodeoffset"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnDownloadError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturndownloaderror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnObjectError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnobjecterror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnPTPDeviceError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnptpdeviceerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnThumbnailError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnthumbnailerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Constants",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-constants"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Data Types",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-data-types"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ImageCaptureCore Macros",
      "type": "topic",
      "url": "/documentation/imagecapturecore/imagecapturecore-macros"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros"
      ],
      "title": "Articles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICMediaPresentation"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICMediaPresentation",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnCodeOffset",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnDownloadError/Code",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnObjectError/Code",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnPTPDeviceError/Code",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnThumbnailError/Code"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-constants",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-data-types",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/imagecapturecore-macros"
              ],
              "title": "Articles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/title",
          "value": "ICReturnMetadataErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnDownloadError~1Code/title",
          "value": "ICReturnDownloadErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnDownloadError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDownloadErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnDownloadError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDownloadErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/title",
          "value": "ICReturnCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnPTPDeviceError~1Code/title",
          "value": "ICReturnPTPDeviceErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnPTPDeviceError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnPTPDeviceErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnPTPDeviceError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnPTPDeviceErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnThumbnailError~1Code/title",
          "value": "ICReturnThumbnailErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnThumbnailError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnThumbnailErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnThumbnailError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnThumbnailErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnObjectError~1Code/title",
          "value": "ICReturnObjectErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnObjectError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnObjectErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnObjectError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnObjectErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICMediaPresentation/title",
          "value": "ICMediaPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICMediaPresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICMediaPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICMediaPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICMediaPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/title",
          "value": "ICReturnConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/title",
          "value": "ICReturnCodeOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnCodeOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCodeOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/title",
          "value": "ICLegacyReturnCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/imagecapturecore-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/imagecapturecore-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
