{
  "abstract": [
    {
      "text": "Examine a scanner’s functional units and features.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/scanner-configuration"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Scanner Configuration"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeCopy": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the Copy button on the device was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICButtonTypeCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeCopy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICButtonTypeCopy"
        }
      ],
      "role": "symbol",
      "title": "ICButtonTypeCopy",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icbuttontypecopy"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeMail": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the Mail button on the device was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICButtonTypeMail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeMail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICButtonTypeMail"
        }
      ],
      "role": "symbol",
      "title": "ICButtonTypeMail",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icbuttontypemail"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypePrint": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the Print button on the device was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICButtonTypePrint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypePrint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICButtonTypePrint"
        }
      ],
      "role": "symbol",
      "title": "ICButtonTypePrint",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icbuttontypeprint"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeScan": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the Scan button on the device was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICButtonTypeScan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeScan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICButtonTypeScan"
        }
      ],
      "role": "symbol",
      "title": "ICButtonTypeScan",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icbuttontypescan"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeTransfer": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the Transfer button on the device was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICButtonTypeTransfer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeTransfer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICButtonTypeTransfer"
        }
      ],
      "role": "symbol",
      "title": "ICButtonTypeTransfer",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icbuttontypetransfer"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeWeb": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the Web button on the device was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICButtonTypeWeb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeWeb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICButtonTypeWeb"
        }
      ],
      "role": "symbol",
      "title": "ICButtonTypeWeb",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icbuttontypeweb"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBandData": {
      "abstract": [
        {
          "text": "The options for each band of data that the scanner reads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerBandData"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerBandData"
        }
      ],
      "role": "symbol",
      "title": "ICScannerBandData",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerbanddata"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBitDepth": {
      "abstract": [
        {
          "text": "The number of bits per channel in the scanned image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerBitDepth"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBitDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerBitDepth"
        }
      ],
      "role": "symbol",
      "title": "ICScannerBitDepth",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerbitdepth"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerColorDataFormatType": {
      "abstract": [
        {
          "text": "The color data formats relevant to multichannel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerColorDataFormatType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerColorDataFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerColorDataFormatType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerColorDataFormatType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannercolordataformattype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice": {
      "abstract": [
        {
          "text": "An object that represents a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate": {
      "abstract": [
        {
          "text": "Methods for determining availability, selecting a functional unit, and performing scans on connected scanners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDeviceDelegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevicedelegate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType": {
      "abstract": [
        {
          "text": "The supported document size types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDocumentType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDocumentType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdocumenttype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeature": {
      "abstract": [
        {
          "text": "An abstract class that describes a scanner feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFeature"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFeature"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFeature",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfeature"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureBoolean": {
      "abstract": [
        {
          "text": "A feature with a value of ",
          "type": "text"
        },
        {
          "code": "YES",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "NO",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFeatureBoolean"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureBoolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFeatureBoolean"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFeatureBoolean",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfeatureboolean"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureEnumeration": {
      "abstract": [
        {
          "text": "A feature that can have one of several discrete values, strings or numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFeatureEnumeration"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureEnumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFeatureEnumeration"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFeatureEnumeration",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfeatureenumeration"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureRange": {
      "abstract": [
        {
          "text": "A feature with a value that lies within a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFeatureRange"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFeatureRange"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFeatureRange",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfeaturerange"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureTemplate": {
      "abstract": [
        {
          "text": "A group of one or more rectangular scan areas that can be used with a scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFeatureTemplate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFeatureTemplate"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFeatureTemplate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfeaturetemplate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureType": {
      "abstract": [
        {
          "text": "The types of scanner features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFeatureType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFeatureType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFeatureType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfeaturetype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit": {
      "abstract": [
        {
          "text": "An abstract class that represents a scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder": {
      "abstract": [
        {
          "text": "An object that represents the document feeder unit on a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitDocumentFeeder"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitDocumentFeeder"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitDocumentFeeder",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitdocumentfeeder"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed": {
      "abstract": [
        {
          "text": "An object that represents the flatbed unit on a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitFlatbed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitFlatbed"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitFlatbed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitflatbed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency": {
      "abstract": [
        {
          "text": "An object that represents the transparency unit for scanning negatives on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitNegativeTransparency"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitNegativeTransparency"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitNegativeTransparency",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitnegativetransparency"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency": {
      "abstract": [
        {
          "text": "An object that represents the transparency unit for scanning positives on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitPositiveTransparency"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitPositiveTransparency"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitPositiveTransparency",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitpositivetransparency"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit": {
      "abstract": [
        {
          "text": "The unit of measurement used by the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnit"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType": {
      "abstract": [
        {
          "text": "The pixel data types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusRequestsOverviewScan": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the scanner is requesting an overview scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerStatusRequestsOverviewScan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusRequestsOverviewScan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerStatusRequestsOverviewScan"
        }
      ],
      "role": "symbol",
      "title": "ICScannerStatusRequestsOverviewScan",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerstatusrequestsoverviewscan"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmUpDone": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the scanner has warmed up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerStatusWarmUpDone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmUpDone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerStatusWarmUpDone"
        }
      ],
      "role": "symbol",
      "title": "ICScannerStatusWarmUpDone",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerstatuswarmupdone"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmingUp": {
      "abstract": [
        {
          "text": "A nonlocalized notification string to indicate that the scanner is warming up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerStatusWarmingUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmingUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerStatusWarmingUp"
        }
      ],
      "role": "symbol",
      "title": "ICScannerStatusWarmingUp",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerstatuswarmingup"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode": {
      "abstract": [
        {
          "text": "The modes for transferring scan data from the scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerTransferMode"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerTransferMode"
        }
      ],
      "role": "symbol",
      "title": "ICScannerTransferMode",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannertransfermode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scanners",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate"
      ],
      "title": "Scanners"
    }
  ],
  "topicSections": [
    {
      "anchor": "Band-Data",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBandData"
      ],
      "title": "Band Data"
    },
    {
      "anchor": "Bit-Depth",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBitDepth"
      ],
      "title": "Bit Depth"
    },
    {
      "anchor": "Color-Formats",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerColorDataFormatType"
      ],
      "title": "Color Formats"
    },
    {
      "anchor": "Document-Sizes",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit"
      ],
      "title": "Document Sizes"
    },
    {
      "anchor": "Features",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeature",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureBoolean",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureEnumeration",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureRange",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureTemplate",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureType"
      ],
      "title": "Features"
    },
    {
      "anchor": "Functional-Units",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode"
      ],
      "title": "Functional Units"
    },
    {
      "anchor": "Pixel-Data-Types",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType"
      ],
      "title": "Pixel Data Types"
    },
    {
      "anchor": "Scanner-States",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusRequestsOverviewScan",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmingUp",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmUpDone"
      ],
      "title": "Scanner States"
    },
    {
      "anchor": "Buttons",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeCopy",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeMail",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypePrint",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeScan",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeTransfer",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeWeb"
      ],
      "title": "Buttons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Band-Data",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBandData"
              ],
              "title": "Band Data"
            },
            {
              "anchor": "Bit-Depth",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerBitDepth"
              ],
              "title": "Bit Depth"
            },
            {
              "anchor": "Color-Formats",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerColorDataFormatType"
              ],
              "title": "Color Formats"
            },
            {
              "anchor": "Document-Sizes",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDocumentType",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit"
              ],
              "title": "Document Sizes"
            },
            {
              "anchor": "Features",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeature",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureBoolean",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureEnumeration",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureRange",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureTemplate",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFeatureType"
              ],
              "title": "Features"
            },
            {
              "anchor": "Functional-Units",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitFlatbed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitNegativeTransparency",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitPositiveTransparency",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerTransferMode"
              ],
              "title": "Functional Units"
            },
            {
              "anchor": "Pixel-Data-Types",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType"
              ],
              "title": "Pixel Data Types"
            },
            {
              "anchor": "Scanner-States",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusRequestsOverviewScan",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmingUp",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerStatusWarmUpDone"
              ],
              "title": "Scanner States"
            },
            {
              "anchor": "Buttons",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeCopy",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeMail",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypePrint",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeScan",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeTransfer",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICButtonTypeWeb"
              ],
              "title": "Buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scanners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDeviceDelegate"
              ],
              "title": "Scanners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitPositiveTransparency/title",
          "value": "ICScannerFunctionalUnitPositiveTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitPositiveTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitPositiveTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitPositiveTransparency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitPositiveTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType/title",
          "value": "ICScannerPixelDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureBoolean/title",
          "value": "ICScannerFeatureBoolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureBoolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureBoolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureBoolean/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureBoolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeTransfer/title",
          "value": "ICButtonTypeTransfer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeTransfer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICButtonTypeTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeMail/title",
          "value": "ICButtonTypeMail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeMail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICButtonTypeMail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerBandData/title",
          "value": "ICScannerBandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerBandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerBandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerBandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerBandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerStatusRequestsOverviewScan/title",
          "value": "ICScannerStatusRequestsOverviewScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerStatusRequestsOverviewScan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerStatusRequestsOverviewScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeCopy/title",
          "value": "ICButtonTypeCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeCopy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICButtonTypeCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureTemplate/title",
          "value": "ICScannerFeatureTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitFlatbed/title",
          "value": "ICScannerFunctionalUnitFlatbed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitFlatbed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitFlatbed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitFlatbed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitFlatbed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit/title",
          "value": "ICScannerMeasurementUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/title",
          "value": "ICScannerDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeature/title",
          "value": "ICScannerFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerColorDataFormatType/title",
          "value": "ICScannerColorDataFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerColorDataFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerColorDataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerColorDataFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerColorDataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeScan/title",
          "value": "ICButtonTypeScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeScan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICButtonTypeScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitNegativeTransparency/title",
          "value": "ICScannerFunctionalUnitNegativeTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitNegativeTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitNegativeTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitNegativeTransparency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitNegativeTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/title",
          "value": "ICScannerFunctionalUnitDocumentFeeder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitDocumentFeeder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitDocumentFeeder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/title",
          "value": "ICScannerDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureRange/title",
          "value": "ICScannerFeatureRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType/title",
          "value": "ICScannerDocumentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDocumentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDocumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureEnumeration/title",
          "value": "ICScannerFeatureEnumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureEnumeration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureEnumeration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureEnumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerStatusWarmingUp/title",
          "value": "ICScannerStatusWarmingUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerStatusWarmingUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerStatusWarmingUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeWeb/title",
          "value": "ICButtonTypeWeb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypeWeb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICButtonTypeWeb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureType/title",
          "value": "ICScannerFeatureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFeatureType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerBitDepth/title",
          "value": "ICScannerBitDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerBitDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerBitDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerBitDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypePrint/title",
          "value": "ICButtonTypePrint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICButtonTypePrint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICButtonTypePrint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerStatusWarmUpDone/title",
          "value": "ICScannerStatusWarmUpDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerStatusWarmUpDone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerStatusWarmUpDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/title",
          "value": "ICScannerFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerTransferMode/title",
          "value": "ICScannerTransferMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerTransferMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerTransferMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerTransferMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerTransferMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/scanner-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/scanner-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
