{
  "abstract": [
    {
      "text": "Creates an average pooling descriptor with the kernel sizes, strides, dilution rates, padding policy and sizes, and zero padding option you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCPoolingDescriptor(cm)averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "averagePoolingDescriptorWithKernelSizes:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "kernelSizes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "strides:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "strides"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dilationRates:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "dilationRates"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paddingPolicy:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-14ba7",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MLCPaddingPolicy",
              "text": "MLCPaddingPolicy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "paddingPolicy"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paddingSizes:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "paddingSizes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "countIncludesPadding:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "countIncludesPadding"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array that contains the kernel sizes for y and x.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "kernelSizes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array containing the kernel strides for y and x.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "strides"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array containing the dilation rates for y and x.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "dilationRates"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The padding policy.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "paddingPolicy"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array containing the padding sizes for y and x.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "paddingSizes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean that indicates whether you include zero padding in the averaging calculation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "countIncludesPadding"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A pooling descriptor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-14ba7": {
      "abstract": [
        {
          "text": "A padding policy that you specify for a convolution or pooling layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPaddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-14ba7",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPaddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingpolicy-14ba7"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:": {
      "abstract": [
        {
          "text": "Creates an average pooling descriptor with the kernel sizes, strides, dilution rates, padding policy and sizes, and zero padding option you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "role": "symbol",
      "title": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/averagepoolingdescriptorwithkernelsizes:strides:dilationrates:paddingpolicy:paddingsizes:countincludespadding:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:": {
      "abstract": [
        {
          "text": "Creates an average pooling descriptor with the kernel sizes, strides, padding policy, padding sizes, and zero padding option that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "role": "symbol",
      "title": "averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/averagepoolingdescriptorwithkernelsizes:strides:paddingpolicy:paddingsizes:countincludespadding:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for an L2 norm pooling function with the kernel sizes, strides, dilation rates, padding policy, and padding sizes you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/l2normpoolingdescriptorwithkernelsizes:strides:dilationrates:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for an L2 norm pooling function with the kernel sizes, strides, padding policy, and padding sizes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/l2normpoolingdescriptorwithkernelsizes:strides:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for a max pooling function with the kernel sizes, strides, dilation rates, padding policy, and padding sizes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/maxpoolingdescriptorwithkernelsizes:strides:dilationrates:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for a max pooling function with the kernel sizes, strides, padding policy, and padding sizes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/maxpoolingdescriptorwithkernelsizes:strides:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingDescriptorWithType:kernelSize:stride:": {
      "abstract": [
        {
          "text": "Creates a pooling descriptor with the pooling function, kernel size, and stride you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "poolingDescriptorWithType:kernelSize:stride:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingDescriptorWithType:kernelSize:stride:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "poolingDescriptorWithType:kernelSize:stride:"
        }
      ],
      "role": "symbol",
      "title": "poolingDescriptorWithType:kernelSize:stride:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/poolingdescriptorwithtype:kernelsize:stride:"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Pooling-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingDescriptorWithType:kernelSize:stride:"
      ],
      "title": "Creating Pooling Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/title",
          "value": "MLCPoolingDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcpoolingdescriptor/averagepoolingdescriptorwithkernelsizes:strides:dilationrates:paddingpolicy:paddingsizes:countincludespadding:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
