{
  "abstract": [
    {
      "text": "The pooling kernel size in x.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelWidth"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCPoolingDescriptor(py)kernelWidth",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kernelWidth"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kernelWidth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "kernelWidth"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kernelWidth"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/countIncludesPadding": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether you include zero padding in the averaging calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "countIncludesPadding"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/countIncludesPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "countIncludesPadding",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/countincludespadding"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInX": {
      "abstract": [
        {
          "text": "The kernel dilation rate, or stride of elements, in x.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dilationRateInX"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInX",
      "kind": "symbol",
      "role": "symbol",
      "title": "dilationRateInX",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/dilationrateinx"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInY": {
      "abstract": [
        {
          "text": "The kernel dilation rate, or stride of elements, in y.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dilationRateInY"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInY",
      "kind": "symbol",
      "role": "symbol",
      "title": "dilationRateInY",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/dilationrateiny"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelHeight": {
      "abstract": [
        {
          "text": "The pooling kernel size in y.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kernelHeight"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelHeight",
      "kind": "symbol",
      "role": "symbol",
      "title": "kernelHeight",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/kernelheight"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelWidth": {
      "abstract": [
        {
          "text": "The pooling kernel size in x.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kernelWidth"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelWidth",
      "kind": "symbol",
      "role": "symbol",
      "title": "kernelWidth",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/kernelwidth"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-1e6rg": {
      "abstract": [
        {
          "text": "The padding policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "paddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-1e6rg",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingpolicy-1e6rg"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInX": {
      "abstract": [
        {
          "text": "The padding size in x, left and right, to use if the padding policy is to use padding size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "paddingSizeInX"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInX",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingSizeInX",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingsizeinx"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInY": {
      "abstract": [
        {
          "text": "The padding size in y, top and bottom, to use if the padding policy is to use padding size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "paddingSizeInY"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInY",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingSizeInY",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingsizeiny"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-9daku": {
      "abstract": [
        {
          "text": "The pooling operation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "poolingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-9daku",
      "kind": "symbol",
      "role": "symbol",
      "title": "poolingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/poolingtype-9daku"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInX": {
      "abstract": [
        {
          "text": "The stride of the kernel in x.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "strideInX"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInX",
      "kind": "symbol",
      "role": "symbol",
      "title": "strideInX",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/strideinx"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInY": {
      "abstract": [
        {
          "text": "The stride of the kernel in y.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "strideInY"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInY",
      "kind": "symbol",
      "role": "symbol",
      "title": "strideInY",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/strideiny"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Pooling-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-9daku",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelHeight",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInX",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInY",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInX",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInY",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-1e6rg",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInX",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInY",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/countIncludesPadding"
      ],
      "title": "Inspecting Pooling Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/title",
          "value": "MLCPoolingDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcpoolingdescriptor/kernelwidth"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
