{
  "abstract": [
    {
      "text": "The padding policy.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Metal Performance Shaders Graph or BNNS instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-7p8a2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MLCompute",
    "externalID": "s:So20MLCPoolingDescriptorC9MLComputeE13paddingPolicyAC010MLCPaddingE0Ovp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "paddingPolicy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9MLCompute16MLCPaddingPolicyO",
        "text": "MLCPaddingPolicy"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "11.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "paddingPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paddingPolicy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-3hic8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9MLCompute16MLCPaddingPolicyO",
              "text": "MLCPaddingPolicy"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-3hic8": {
      "abstract": [
        {
          "text": "A padding policy that you specify for a convolution or pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPaddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-3hic8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingPolicy"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingpolicy-3hic8"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRates": {
      "abstract": [
        {
          "text": "A tuple that contains the dilation rates for y and x.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dilationRates"
        },
        {
          "kind": "text",
          "text": ": (y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRates",
      "kind": "symbol",
      "role": "symbol",
      "title": "dilationRates",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/dilationrates"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelSizes": {
      "abstract": [
        {
          "text": "A tuple that contains the kernel sizes for height and width.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kernelSizes"
        },
        {
          "kind": "text",
          "text": ": (height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelSizes",
      "kind": "symbol",
      "role": "symbol",
      "title": "kernelSizes",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/kernelsizes"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-7p8a2": {
      "abstract": [
        {
          "text": "The padding policy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paddingPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9MLCompute16MLCPaddingPolicyO",
          "text": "MLCPaddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-7p8a2",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingpolicy-7p8a2"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-4ni07": {
      "abstract": [
        {
          "text": "The pooling operation type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "poolingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9MLCompute14MLCPoolingTypeO",
          "text": "MLCPoolingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-4ni07",
      "kind": "symbol",
      "role": "symbol",
      "title": "poolingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/poolingtype-4ni07"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strides": {
      "abstract": [
        {
          "text": "A tuple that contains the kernel strides for y and x.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strides"
        },
        {
          "kind": "text",
          "text": ": (y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strides",
      "kind": "symbol",
      "role": "symbol",
      "title": "strides",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/strides"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Pooling-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-4ni07",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelSizes",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strides",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRates"
      ],
      "title": "Inspecting Pooling Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/title",
          "value": "MLCPoolingDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcpoolingdescriptor/paddingpolicy-7p8a2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
