{
  "abstract": [
    {
      "text": "A structure that contains Watch Connectivity error information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11WCErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "WCError"
      }
    ],
    "modules": [
      {
        "name": "Watch Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WCError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "WCError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "WCError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/watchconnectivity"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError": {
      "abstract": [
        {
          "text": "A structure that contains Watch Connectivity error information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCError"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCError"
        }
      ],
      "role": "symbol",
      "title": "WCError",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code": {
      "abstract": [
        {
          "text": "Constants for errors during a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/companionAppNotInstalled": {
      "abstract": [
        {
          "text": "An error indicating that the companion hasn’t installed the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "companionAppNotInstalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/companionAppNotInstalled",
      "kind": "symbol",
      "role": "symbol",
      "title": "companionAppNotInstalled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/companionappnotinstalled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/deliveryFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t deliver the payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deliveryFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/deliveryFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "deliveryFailed",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/deliveryfailed"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/deviceNotPaired": {
      "abstract": [
        {
          "text": "An error indicating that the current device doesn’t have a paired counterpart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotPaired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/deviceNotPaired",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceNotPaired",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/devicenotpaired"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/errordomain"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/fileAccessDenied": {
      "abstract": [
        {
          "text": "An error indicating that the system can’t transfer a file because it is inaccessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileAccessDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/fileAccessDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileAccessDenied",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/fileaccessdenied"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/genericError": {
      "abstract": [
        {
          "text": "An error that occurs when there is an unknown problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/genericError",
      "kind": "symbol",
      "role": "symbol",
      "title": "genericError",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/genericerror"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/insufficientSpace": {
      "abstract": [
        {
          "text": "An error indicating that there isn’t enough space on the receiving side to store the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/insufficientSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "insufficientSpace",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/insufficientspace"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/invalidParameter": {
      "abstract": [
        {
          "text": "An error indicating that a parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/invalidParameter",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameter",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/invalidparameter"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/messageReplyFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t return the reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageReplyFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/messageReplyFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "messageReplyFailed",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/messagereplyfailed"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/messageReplyTimedOut": {
      "abstract": [
        {
          "text": "An error that occurs when the counterpart app doesn’t return a reply in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageReplyTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/messageReplyTimedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "messageReplyTimedOut",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/messagereplytimedout"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/notReachable": {
      "abstract": [
        {
          "text": "An error indicating that the counterpart app isn’t reachable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/notReachable",
      "kind": "symbol",
      "role": "symbol",
      "title": "notReachable",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/notreachable"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/payloadTooLarge": {
      "abstract": [
        {
          "text": "An error indicating an attempt to send an item that exceeds the maximum size limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payloadTooLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/payloadTooLarge",
      "kind": "symbol",
      "role": "symbol",
      "title": "payloadTooLarge",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/payloadtoolarge"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/payloadUnsupportedTypes": {
      "abstract": [
        {
          "text": "An error indicating that a dictionary contains nonproperty list types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payloadUnsupportedTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/payloadUnsupportedTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "payloadUnsupportedTypes",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/payloadunsupportedtypes"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionInactive": {
      "abstract": [
        {
          "text": "An error indicating that the session is inactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionInactive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionInactive",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionInactive",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/sessioninactive"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionMissingDelegate": {
      "abstract": [
        {
          "text": "An error indicating that the WatchKit extension doesn’t have a valid extension delegate to process events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionMissingDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionMissingDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionMissingDelegate",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/sessionmissingdelegate"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionNotActivated": {
      "abstract": [
        {
          "text": "An error indicating that the other device doesn’t have an active session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotActivated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionNotActivated",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionNotActivated",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/sessionnotactivated"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionNotSupported": {
      "abstract": [
        {
          "text": "An error indicating that the current device doesn’t support the use of session objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionNotSupported",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/sessionnotsupported"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/transferTimedOut": {
      "abstract": [
        {
          "text": "An error that occurs when the transfer reaches the timeout limit before it completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/transferTimedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "transferTimedOut",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/transfertimedout"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/watchAppNotInstalled": {
      "abstract": [
        {
          "text": "An error indicating that the Watch app isn’t an installed app on the user’s Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watchAppNotInstalled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/watchAppNotInstalled",
      "kind": "symbol",
      "role": "symbol",
      "title": "watchAppNotInstalled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/watchappnotinstalled"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/watchOnlyApp": {
      "abstract": [
        {
          "text": "An error indicating that the app is a watch-only app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watchOnlyApp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11WCErrorCodeLeV",
          "text": "WCError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WCErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/watchOnlyApp",
      "kind": "symbol",
      "role": "symbol",
      "title": "watchOnlyApp",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/watchonlyapp"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors associated with the Watch Connectivity framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "WCErrorDomain",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerrordomain"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState": {
      "abstract": [
        {
          "text": "Constants indicating the activation state of a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCSessionActivationState"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCSessionActivationState"
        }
      ],
      "role": "symbol",
      "title": "WCSessionActivationState",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcsessionactivationstate"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCSessionActivationState",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCErrorDomain",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Understanding-Error-Codes",
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/genericError",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionNotSupported",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionMissingDelegate",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionNotActivated",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/deviceNotPaired",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/watchAppNotInstalled",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/notReachable",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/invalidParameter",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/payloadTooLarge",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/payloadUnsupportedTypes",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/messageReplyFailed",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/messageReplyTimedOut",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/fileAccessDenied",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/deliveryFailed",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/insufficientSpace",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/sessionInactive",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/transferTimedOut",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/companionAppNotInstalled",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/watchOnlyApp"
      ],
      "title": "Understanding Error Codes"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code"
      ],
      "title": "Enumerations"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState/title",
          "value": "WCSessionActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCSessionActivationState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCSessionActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCErrorDomain/title",
          "value": "WCErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code/title",
          "value": "WCErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchconnectivity/wcerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
