{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DopplerShift"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AU3DMixerRenderingFlags@k3DMixerRenderingFlags_DopplerShift",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "k3DMixerRenderingFlags_DopplerShift"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
        "text": "AU3DMixerRenderingFlags"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "k3DMixerRenderingFlags_DopplerShift"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "k3DMixerRenderingFlags_DopplerShift"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_DopplerShift"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
              "text": "AU3DMixerRenderingFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "role": "symbol",
      "title": "AU3DMixerRenderingFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_ConstantReverbBlend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_ConstantReverbBlend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_ConstantReverbBlend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_ConstantReverbBlend"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerRenderingFlags_ConstantReverbBlend",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_constantreverbblend"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DistanceAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DistanceAttenuation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerRenderingFlags_DistanceAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_distanceattenuation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceDiffusion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DistanceDiffusion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceDiffusion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DistanceDiffusion"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerRenderingFlags_DistanceDiffusion",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_distancediffusion"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DistanceFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DistanceFilter"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerRenderingFlags_DistanceFilter",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_distancefilter"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DopplerShift": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DopplerShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DopplerShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_DopplerShift"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerRenderingFlags_DopplerShift",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_dopplershift"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_InterAuralDelay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_InterAuralDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_InterAuralDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_InterAuralDelay"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerRenderingFlags_InterAuralDelay",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_interauraldelay"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_LinearDistanceAttenuation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_LinearDistanceAttenuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AU3DMixerRenderingFlags",
          "text": "AU3DMixerRenderingFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_LinearDistanceAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k3DMixerRenderingFlags_LinearDistanceAttenuation"
        }
      ],
      "role": "symbol",
      "title": "k3DMixerRenderingFlags_LinearDistanceAttenuation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_lineardistanceattenuation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_ConstantReverbBlend",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceAttenuation",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceDiffusion",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceFilter",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_InterAuralDelay",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_LinearDistanceAttenuation"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "k3DMixerRenderingFlags_DopplerShift"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_DopplerShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_ConstantReverbBlend",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceAttenuation",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceDiffusion",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_DistanceFilter",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_InterAuralDelay",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AU3DMixerRenderingFlags/k3DMixerRenderingFlags_LinearDistanceAttenuation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "k3DMixerRenderingFlags_DopplerShift"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_ConstantReverbBlend/title",
          "value": "k3DMixerRenderingFlags_ConstantReverbBlend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_ConstantReverbBlend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_ConstantReverbBlend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_InterAuralDelay/title",
          "value": "k3DMixerRenderingFlags_InterAuralDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_InterAuralDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_InterAuralDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DopplerShift/title",
          "value": "k3DMixerRenderingFlags_DopplerShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DopplerShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_DopplerShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags/title",
          "value": "AU3DMixerRenderingFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AU3DMixerRenderingFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_LinearDistanceAttenuation/title",
          "value": "k3DMixerRenderingFlags_LinearDistanceAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_LinearDistanceAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_LinearDistanceAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DistanceDiffusion/title",
          "value": "k3DMixerRenderingFlags_DistanceDiffusion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DistanceDiffusion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_DistanceDiffusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DistanceFilter/title",
          "value": "k3DMixerRenderingFlags_DistanceFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DistanceFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_DistanceFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DistanceAttenuation/title",
          "value": "k3DMixerRenderingFlags_DistanceAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AU3DMixerRenderingFlags~1k3DMixerRenderingFlags_DistanceAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k3DMixerRenderingFlags_DistanceAttenuation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_dopplershift"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/au3dmixerrenderingflags/k3dmixerrenderingflags_dopplershift"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
