{
  "abstract": [
    {
      "text": "Determine the version of XcodeKit available in an instance of Xcode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcodekit/documentation/XcodeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcodekit/documentation/XcodeKit/xcodekit-version-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "XcodeKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "XcodeKit Version Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit": {
      "abstract": [
        {
          "text": "Create extensions to add commands to the Xcode source editor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "XcodeKit",
      "type": "topic",
      "url": "/documentation/xcodekit"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCODE_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "XCODE_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCODE_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCODE_EXPORT",
      "type": "topic",
      "url": "/documentation/xcodekit/xcode_export"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber": {
      "abstract": [
        {
          "text": "The current version of XcodeKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber"
        }
      ],
      "role": "symbol",
      "title": "XCXcodeKitVersionNumber",
      "type": "topic",
      "url": "/documentation/xcodekit/xcxcodekitversionnumber"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0": {
      "abstract": [
        {
          "text": "The version of XcodeKit included in Xcode 8.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber_Xcode_8_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber_Xcode_8_0"
        }
      ],
      "role": "symbol",
      "title": "XCXcodeKitVersionNumber_Xcode_8_0",
      "type": "topic",
      "url": "/documentation/xcodekit/xcxcodekitversionnumber_xcode_8_0"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "XcodeKit-Versions",
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber",
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0"
      ],
      "title": "XcodeKit Versions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "XcodeKit-Versions",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber",
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0"
              ],
              "title": "XcodeKit Versions"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCODE_EXPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber_Xcode_8_0/title",
          "value": "XCXcodeKitVersionNumber_Xcode_8_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber_Xcode_8_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCXcodeKitVersionNumber_Xcode_8_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber/title",
          "value": "XCXcodeKitVersionNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCXcodeKitVersionNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcodekit/xcodekit-version-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcodekit/xcodekit-version-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
