{
  "abstract": [
    {
      "text": "The protocol you implement to handle command invocations in a source editor extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcodekit/documentation/XcodeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)XCSourceEditorCommand",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCSourceEditorCommand"
      }
    ],
    "modules": [
      {
        "name": "XcodeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCSourceEditorCommand"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "XCSourceEditorCommand"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommand"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/creating-a-source-editor-extension"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A one-to-one mapping between command classes and commands is not required—multiple commands can be handled by a single class, by checking their invocation’s ",
              "type": "text"
            },
            {
              "code": "commandIdentifier",
              "type": "codeVoice"
            },
            {
              "text": " at runtime.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit": {
      "abstract": [
        {
          "text": "Create extensions to add commands to the Xcode source editor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "XcodeKit",
      "type": "topic",
      "url": "/documentation/xcodekit"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand": {
      "abstract": [
        {
          "text": "The protocol you implement to handle command invocations in a source editor extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommand"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommand"
        }
      ],
      "role": "symbol",
      "title": "XCSourceEditorCommand",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommand"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand/perform(with:completionHandler:)": {
      "abstract": [
        {
          "text": "Performs the action associated with the command using the information in an invocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCSourceEditorCommandInvocation",
          "text": "XCSourceEditorCommandInvocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand/perform(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performCommandWithInvocation:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "perform(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommand/perform(with:completionhandler:)"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandDefinitionKey": {
      "abstract": [
        {
          "text": "A key in the dictionary that defines a source editor command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandDefinitionKey"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandDefinitionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandDefinitionKey"
        }
      ],
      "role": "symbol",
      "title": "XCSourceEditorCommandDefinitionKey",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommanddefinitionkey"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation": {
      "abstract": [
        {
          "text": "An object that identifies the command issued to your extension and provides the contents of the active source editor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandInvocation"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandInvocation"
        }
      ],
      "role": "symbol",
      "title": "XCSourceEditorCommandInvocation",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommandinvocation"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/creating-a-source-editor-extension": {
      "abstract": [
        {
          "text": "Add and configure a source editor extension in your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/creating-a-source-editor-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a Source Editor Extension",
      "type": "topic",
      "url": "/documentation/xcodekit/creating-a-source-editor-extension"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editor-Commands",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation"
      ],
      "title": "Editor Commands"
    }
  ],
  "topicSections": [
    {
      "anchor": "Defining-Editor-Commands",
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandDefinitionKey"
      ],
      "title": "Defining Editor Commands"
    },
    {
      "anchor": "Handling-Editor-Commands",
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand/perform(with:completionHandler:)"
      ],
      "title": "Handling Editor Commands"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCSourceEditorCommand"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcodekit/documentation/XcodeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Defining-Editor-Commands",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandDefinitionKey"
              ],
              "title": "Defining Editor Commands"
            },
            {
              "anchor": "Handling-Editor-Commands",
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommand/perform(with:completionHandler:)"
              ],
              "title": "Handling Editor Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editor-Commands",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation"
              ],
              "title": "Editor Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCSourceEditorCommand"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand~1perform(with:completionHandler:)/title",
          "value": "performCommandWithInvocation:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand~1perform(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performCommandWithInvocation:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand/title",
          "value": "XCSourceEditorCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/title",
          "value": "XCSourceEditorCommandInvocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandInvocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandInvocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandDefinitionKey/title",
          "value": "XCSourceEditorCommandDefinitionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandDefinitionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandDefinitionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandDefinitionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandDefinitionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcodekit/xcsourceeditorcommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcodekit/xcsourceeditorcommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
