{
  "abstract": [
    {
      "text": "The current version of XcodeKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcodekit/documentation/XcodeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@XCXcodeKitVersionNumber",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCXcodeKitVersionNumber"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      }
    ],
    "modules": [
      {
        "name": "XcodeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCXcodeKitVersionNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "XCXcodeKitVersionNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCXcodeKitVersionNumber"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit": {
      "abstract": [
        {
          "text": "Create extensions to add commands to the Xcode source editor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "XcodeKit",
      "type": "topic",
      "url": "/documentation/xcodekit"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber": {
      "abstract": [
        {
          "text": "The current version of XcodeKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber"
        }
      ],
      "role": "symbol",
      "title": "XCXcodeKitVersionNumber",
      "type": "topic",
      "url": "/documentation/xcodekit/xcxcodekitversionnumber"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0": {
      "abstract": [
        {
          "text": "The version of XcodeKit included in Xcode 8.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber_Xcode_8_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCXcodeKitVersionNumber_Xcode_8_0"
        }
      ],
      "role": "symbol",
      "title": "XCXcodeKitVersionNumber_Xcode_8_0",
      "type": "topic",
      "url": "/documentation/xcodekit/xcxcodekitversionnumber_xcode_8_0"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "XcodeKit-Versions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0"
      ],
      "title": "XcodeKit Versions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCXcodeKitVersionNumber"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCXcodeKitVersionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcodekit/documentation/XcodeKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "XcodeKit-Versions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCXcodeKitVersionNumber_Xcode_8_0"
              ],
              "title": "XcodeKit Versions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCXcodeKitVersionNumber"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber/title",
          "value": "XCXcodeKitVersionNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCXcodeKitVersionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber_Xcode_8_0/title",
          "value": "XCXcodeKitVersionNumber_Xcode_8_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCXcodeKitVersionNumber_Xcode_8_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCXcodeKitVersionNumber_Xcode_8_0"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcodekit/xcxcodekitversionnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcodekit/xcxcodekitversionnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
