{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"open","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Calling ","type":"text"},{"code":"open","type":"codeVoice"},{"text":" on an open drawer does nothing. You can get the state of a drawer by sending it ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/state-swift.property","isActive":true},{"text":". If an edge is not specified, an attempt will be made to choose an edge based on the space available to display the drawer onscreen. If you need to ensure that a drawer opens on a particular edge, use ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(on:)","type":"reference"},{"text":".","type":"text"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"open"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"},{"kind":"text","text":"()"}],"platforms":[{"deprecated":false,"name":"macOS","message":"Drawers are deprecated; consider using NSSplitViewController","introducedAt":"10.0","deprecatedAt":"10.13","unavailable":false,"beta":false}],"symbolKind":"method","modules":[{"name":"AppKit"}],"title":"open()","externalID":"c:objc(cs)NSDrawer(im)open","role":"symbol","roleHeading":"Instance Method"},"seeAlsoSections":[{"anchor":"Opening-and-Closing-Drawers","title":"Opening and Closing Drawers","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDrawer/close()","doc://com.apple.appkit/documentation/AppKit/NSDrawer/close(_:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(_:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(on:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/toggle(_:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/state-swift.property"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsdrawer/open()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsdrawer/open()"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"If the receiver is closed, this method opens it.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Drawers are deprecated; consider using NSSplitViewController","type":"text"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDrawer"]]},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(_:)":{"title":"open(_:)","navigatorTitle":[{"text":"open:","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"An action method to open the drawer."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"open"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(_:)","url":"/documentation/appkit/nsdrawer/open(_:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDrawer/close(_:)":{"type":"topic","url":"/documentation/appkit/nsdrawer/close(_:)","deprecated":true,"navigatorTitle":[{"text":"close:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/close(_:)","abstract":[{"text":"An action method to close the receiver.","type":"text"}],"title":"close(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"close"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSDrawer":{"url":"/documentation/appkit/nsdrawer","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSDrawer"}],"deprecated":true,"title":"NSDrawer","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSDrawer"}],"abstract":[{"text":"A user interface element that contains and displays text, scroll, and browser views, in addition to other view subclasses.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDrawer/close()":{"title":"close()","navigatorTitle":[{"text":"close","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"text":"If the receiver is open, this method closes it.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/close()","url":"/documentation/appkit/nsdrawer/close()","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDrawer/toggle(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/toggle(_:)","title":"toggle(_:)","deprecated":true,"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Toggles the drawer open or closed."}],"url":"/documentation/appkit/nsdrawer/toggle(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggle"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"toggle:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDrawer/state-swift.property":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/state-swift.property","title":"state","deprecated":true,"role":"symbol","kind":"symbol","abstract":[{"text":"The state of the receiver.","type":"text"}],"url":"/documentation/appkit/nsdrawer/state-swift.property","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"state"}]},"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open()":{"title":"open()","navigatorTitle":[{"kind":"identifier","text":"open"}],"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"text":"If the receiver is closed, this method opens it.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"open","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open()","url":"/documentation/appkit/nsdrawer/open()","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(on:)":{"title":"open(on:)","navigatorTitle":[{"text":"openOnEdge:","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"text":"Causes the receiver to open on the specified edge of the parent window.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"open","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSRectEdge","text":"NSRectEdge","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(on:)","url":"/documentation/appkit/nsdrawer/open(on:)","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.0","deprecatedAt":"10.13"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"open","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"open"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDrawer"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDrawer/close()","doc://com.apple.appkit/documentation/AppKit/NSDrawer/close(_:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(_:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/open(on:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/toggle(_:)","doc://com.apple.appkit/documentation/AppKit/NSDrawer/state-swift.property"],"generated":true,"title":"Opening and Closing Drawers","anchor":"Opening-and-Closing-Drawers"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"open","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":[{"type":"paragraph","inlineContent":[{"text":"Drawers are deprecated; consider using NSSplitViewController","type":"text"}]}],"path":"/deprecationSummary"},{"op":"replace","value":"open:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1open(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"open:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1open(_:)/fragments"},{"op":"replace","value":"close:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1close(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"close:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1close(_:)/fragments"},{"op":"replace","value":"NSDrawer","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/title"},{"op":"replace","value":[{"text":"NSDrawer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSDrawer"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer/navigatorTitle"},{"op":"replace","value":"close","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1close()/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1close()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"close"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1toggle(_:)/title","value":"toggle:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1toggle(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggle:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1state-swift.property/title","value":"state"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1state-swift.property/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1open()/title","value":"open"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1open()/fragments","value":[{"text":"- ","kind":"text"},{"text":"open","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1open(on:)/title","value":"openOnEdge:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDrawer~1open(on:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openOnEdge:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}