{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction/nodeInteraction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction/nodeInteraction/connection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AUNodeInteraction@U@AUGraph.h@10929@FI@connection",
    "fragments": [
      {
        "kind": "identifier",
        "text": "connection"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "connection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "connection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitNodeConnection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioUnitNodeConnection",
              "text": "AUNodeConnection"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction": {
      "abstract": [
        {
          "text": "Describes the interaction between two node objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUNodeInteraction"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUNodeInteraction"
        }
      ],
      "role": "symbol",
      "title": "AUNodeInteraction",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aunodeinteraction"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction/nodeInteraction": {
      "abstract": [
        {
          "text": "A union providing information about a node interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nodeInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AUNodeInteraction",
          "text": "AUNodeInteraction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_nodeInteraction"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction/nodeInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nodeInteraction"
        }
      ],
      "role": "symbol",
      "title": "nodeInteraction",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aunodeinteraction/nodeinteraction"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction/nodeInteraction/connection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "connection"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUNodeInteraction/nodeInteraction/connection",
      "kind": "symbol",
      "role": "symbol",
      "title": "connection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aunodeinteraction/nodeinteraction/connection"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitNodeConnection": {
      "abstract": [
        {
          "text": "A connection between two node objects in an audio processing graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitNodeConnection"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitNodeConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitNodeConnection"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitNodeConnection",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitnodeconnection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNodeInteraction~1nodeInteraction/title",
          "value": "nodeInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNodeInteraction~1nodeInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nodeInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitNodeConnection/title",
          "value": "AudioUnitNodeConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitNodeConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitNodeConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitNodeConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitNodeConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNodeInteraction/title",
          "value": "AUNodeInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNodeInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUNodeInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUNodeInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUNodeInteraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/aunodeinteraction/nodeinteraction/connection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
