{
  "abstract": [
    {
      "text": "Returns a new template that has a row of header text and two rows of body text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKComplicationTemplateGraphicRectangularStandardBody(cm)templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "templateWithHeaderTextProvider:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLKTextProvider",
              "text": "CLKTextProvider"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "headerTextProvider"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "body1TextProvider:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLKTextProvider",
              "text": "CLKTextProvider"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "body1TextProvider"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "body2TextProvider:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLKTextProvider",
              "text": "CLKTextProvider"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "body2TextProvider"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text provider for the header text. The template supports multicolored text from this text provider.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "headerTextProvider"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text provider for the first row of body text. The template supports multicolored text from this text provider.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "body1TextProvider"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text provider for the second row of body text. The template supports multicolored text from this text provider.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "body2TextProvider"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody": {
      "abstract": [
        {
          "text": "A template for displaying a large rectangle containing text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularStandardBody",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerImageProvider:headerTextProvider:body1TextProvider:)": {
      "abstract": [
        {
          "text": "Creates a new template that has a header row with an image and text, and a row of body text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "headerImageProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKFullColorImageProvider",
          "text": "CLKFullColorImageProvider"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "headerTextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerImageProvider:headerTextProvider:body1TextProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(headerImageProvider:headerTextProvider:body1TextProvider:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/init(headerimageprovider:headertextprovider:body1textprovider:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:)": {
      "abstract": [
        {
          "text": "Creates a new template that has a header row with an image and text, and two rows of body text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "headerImageProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKFullColorImageProvider",
          "text": "CLKFullColorImageProvider"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "headerTextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body2TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(headerImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/init(headerimageprovider:headertextprovider:body1textprovider:body2textprovider:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerTextProvider:body1TextProvider:)": {
      "abstract": [
        {
          "text": "Creates a new template that has a row of header text and a row of body text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "headerTextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerTextProvider:body1TextProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHeaderTextProvider:body1TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(headerTextProvider:body1TextProvider:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/init(headertextprovider:body1textprovider:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerTextProvider:body1TextProvider:body2TextProvider:)": {
      "abstract": [
        {
          "text": "Creates a new template that has a row of header text and two rows of body text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "headerTextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body2TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerTextProvider:body1TextProvider:body2TextProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(headerTextProvider:body1TextProvider:body2TextProvider:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/init(headertextprovider:body1textprovider:body2textprovider:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:": {
      "abstract": [
        {
          "text": "Returns a new template that has a header row with an image and text, and a row of body text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/templatewithheaderimageprovider:headertextprovider:body1textprovider:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:": {
      "abstract": [
        {
          "text": "Returns a new template that has a header row with an image and text, and two rows of body text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/templatewithheaderimageprovider:headertextprovider:body1textprovider:body2textprovider:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderTextProvider:body1TextProvider:": {
      "abstract": [
        {
          "text": "Returns a new template that has a row of header text and a row of body text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithHeaderTextProvider:body1TextProvider:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderTextProvider:body1TextProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithHeaderTextProvider:body1TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "templateWithHeaderTextProvider:body1TextProvider:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/templatewithheadertextprovider:body1textprovider:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:": {
      "abstract": [
        {
          "text": "Returns a new template that has a row of header text and two rows of body text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "templateWithHeaderTextProvider:body1TextProvider:body2TextProvider:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/templatewithheadertextprovider:body1textprovider:body2textprovider:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider": {
      "abstract": [
        {
          "text": "The common behavior for displaying text-based data in a complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKTextProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKTextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKTextProvider"
        }
      ],
      "role": "symbol",
      "title": "CLKTextProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clktextprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-the-Template",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerTextProvider:body1TextProvider:)",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerTextProvider:body1TextProvider:body2TextProvider:)",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerImageProvider:headerTextProvider:body1TextProvider:)",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/init(headerImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:)",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderTextProvider:body1TextProvider:",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:"
      ],
      "title": "Creating the Template"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerImageProvider:headerTextProvider:body1TextProvider:)/title",
          "value": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerImageProvider:headerTextProvider:body1TextProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerTextProvider:body1TextProvider:body2TextProvider:)/title",
          "value": "initWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerTextProvider:body1TextProvider:body2TextProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHeaderTextProvider:body1TextProvider:body2TextProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/title",
          "value": "CLKComplicationTemplateGraphicRectangularStandardBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerTextProvider:body1TextProvider:)/title",
          "value": "initWithHeaderTextProvider:body1TextProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerTextProvider:body1TextProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHeaderTextProvider:body1TextProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKTextProvider/title",
          "value": "CLKTextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKTextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKTextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKTextProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKTextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:)/title",
          "value": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody~1init(headerImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:body2TextProvider:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody/templatewithheadertextprovider:body1textprovider:body2textprovider:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
