{
  "abstract": [
    {
      "text": "The distances to the far and near clipping planes from the person viewing the content, in meters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/depthRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CompositorServices",
    "externalID": "c:@F@cp_drawable_get_depth_range",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "depthRange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float2",
        "text": "simd_float2"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_drawable_get_depth_range"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "depthRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "depthRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@simd_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "nonmutating"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apply the depth range for drawing to the drawable that it applies to.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The compositor uses these values to compute the perspective projection matrix,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which clips content that’s not between the near and far planes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Compositor Services stores the values in reverse-z order in a 2D floating-point vector:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "x",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property stores the distance of the far plane.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "y",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property stores the distance of the near plane.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Drawable",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/depthRange": {
      "abstract": [
        {
          "text": "The distances to the far and near clipping planes from the person viewing the content, in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/depthRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_drawable_get_depth_range"
        }
      ],
      "role": "symbol",
      "title": "depthRange",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/depthrange"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_drawable_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_drawable_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_drawable_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@simd_float2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@simd_float2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float2",
      "type": "topic",
      "url": "/documentation/simd/simd_float2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cp_drawable_get_depth_range"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_drawable_get_depth_range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compositorservices/documentation/CompositorServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@simd_float2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float2",
                    "text": "simd_float2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "cp_drawable_get_depth_range"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@cp_drawable_t",
                    "text": "cp_drawable_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "drawable"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The drawable for a frame.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "drawable"
              }
            ]
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Two floating-point values, in meters,",
                    "type": "text"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "text": "that represent the distance to the near and far planes, respectively.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@simd_float2/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:]2f",
              "text": "float __attribute__((ext_vector_type(2)))"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_float2"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1depthRange/title",
          "value": "cp_drawable_get_depth_range"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1depthRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_drawable_get_depth_range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/title",
          "value": "CP_OBJECT_cp_layer_renderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer/drawable/depthrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer/drawable/depthrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
