{
  "abstract": [
    {
      "text": "The sequential index of a drawable’s frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/presentationFrameIndex"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CompositorServices",
    "externalID": "c:@F@cp_drawable_get_presentation_frame_index",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "presentationFrameIndex"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@cp_compositor_frame_index_t",
        "text": "CompositorFrameIndex"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_drawable_get_presentation_frame_index"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "presentationFrameIndex"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "presentationFrameIndex"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorFrameIndex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@cp_compositor_frame_index_t",
              "text": "CompositorFrameIndex"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your immersive space becomes visible, you start drawing frames of content.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Compositor Services assigns a sequential index to each frame to indicate its position in the final output.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can use these indexes to differentiate frames during drawing or predict future frame indexes.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, you might start playback of an audio file when a specific frame appears.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorFrameIndex": {
      "abstract": [
        {
          "text": "The sequential index for a frame in the compositor’s timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompositorFrameIndex"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorFrameIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompositorFrameIndex"
        }
      ],
      "role": "symbol",
      "title": "CompositorFrameIndex",
      "type": "topic",
      "url": "/documentation/compositorservices/compositorframeindex"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Drawable"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Drawable",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/frameTiming": {
      "abstract": [
        {
          "text": "The timing information for the drawable’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameTiming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cp_frame_t",
          "text": "Frame"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@cp_frame_timing_t",
          "text": "Timing"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/frameTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_drawable_get_frame_timing"
        }
      ],
      "role": "symbol",
      "title": "frameTiming",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/frametiming"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/presentationFrameIndex": {
      "abstract": [
        {
          "text": "The sequential index of a drawable’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationFrameIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@cp_compositor_frame_index_t",
          "text": "CompositorFrameIndex"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/presentationFrameIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_drawable_get_presentation_frame_index"
        }
      ],
      "role": "symbol",
      "title": "presentationFrameIndex",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/drawable/presentationframeindex"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t": {
      "abstract": [
        {
          "text": "A type that provides the textures and information you need to draw a frame of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cp_drawable_t"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "cp_drawable_t",
      "type": "topic",
      "url": "/documentation/compositorservices/cp_drawable_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Synchronizing-the-drawing-operation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/frameTiming"
      ],
      "title": "Synchronizing the drawing operation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cp_drawable_get_presentation_frame_index"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_drawable_get_presentation_frame_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compositorservices/documentation/CompositorServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Synchronizing-the-drawing-operation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Drawable/frameTiming"
              ],
              "title": "Synchronizing the drawing operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/CompositorFrameIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@cp_compositor_frame_index_t",
                    "text": "cp_compositor_frame_index_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "cp_drawable_get_presentation_frame_index"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/cp_drawable_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@cp_drawable_t",
                    "text": "cp_drawable_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "drawable"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The drawable for a frame.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "drawable"
              }
            ]
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The presentation index of the frame.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1presentationFrameIndex/title",
          "value": "cp_drawable_get_presentation_frame_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1presentationFrameIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_drawable_get_presentation_frame_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/title",
          "value": "CP_OBJECT_cp_layer_renderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1frameTiming/title",
          "value": "cp_drawable_get_frame_timing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer~1Drawable~1frameTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_drawable_get_frame_timing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1CompositorFrameIndex/title",
          "value": "cp_compositor_frame_index_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1CompositorFrameIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_compositor_frame_index_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1CompositorFrameIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_compositor_frame_index_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer/drawable/presentationframeindex"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer/drawable/presentationframeindex"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
