{"seeAlsoSections":[{"anchor":"Configuring-the-Checkerboard-Pattern","generated":true,"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions"],"title":"Configuring the Checkerboard Pattern"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"color1"}],"role":"symbol","roleHeading":"Instance Property","title":"color1","externalID":"c:objc(cs)MDLCheckerboardTexture(py)color1","modules":[{"name":"Model I/O"}],"symbolKind":"property","platforms":[{"beta":false,"name":"iOS","introducedAt":"9.0","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"9.0","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false},{"unavailable":false,"introducedAt":"10.11","name":"macOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"9.0","name":"tvOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"color1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGColorRef","text":"CGColor"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture"]]},"abstract":[{"text":"The color for half of the squares in the checkerboard pattern.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color1","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGColorRef","preciseIdentifier":"c:@T@CGColorRef","text":"CGColor","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"This color appears in the top left square of the generated pattern, and in alternate squares thereafter.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Changing the ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1","type":"reference","isActive":true},{"text":", or ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2","type":"reference","isActive":true},{"text":" properties invalidates the cache, causing Model I/O to regenerate texel data the next time it is needed.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/modelio/mdlcheckerboardtexture/color1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/modelio/mdlcheckerboardtexture/color1"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2":{"url":"/documentation/modelio/mdlcheckerboardtexture/color2","title":"color2","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2","abstract":[{"type":"text","text":"The color for the other half of the squares in the checkerboard pattern."}],"navigatorTitle":[{"text":"color2","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color2","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGColor","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGColorRef"},{"text":"?","kind":"text"}]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions":{"url":"/documentation/modelio/mdlcheckerboardtexture/divisions","title":"divisions","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions","abstract":[{"type":"text","text":"The number of squares along each dimension in the checkerboard pattern."}],"navigatorTitle":[{"text":"divisions","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"divisions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]},"doc://com.externally.resolved.symbol/c:@T@CGColorRef":{"type":"topic","title":"CGColor","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"CGColor","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@CGColorRef","url":"/documentation/coregraphics/cgcolor","abstract":[{"type":"text","text":"A set of components that define a color, with a color space specifying how to interpret them."}]},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1":{"url":"/documentation/modelio/mdlcheckerboardtexture/color1","title":"color1","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1","abstract":[{"type":"text","text":"The color for half of the squares in the checkerboard pattern."}],"navigatorTitle":[{"text":"color1","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGColor","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGColorRef"},{"text":"?","kind":"text"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture":{"url":"/documentation/modelio/mdlcheckerboardtexture","title":"MDLCheckerboardTexture","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture","abstract":[{"type":"text","text":"A generator of texel data that creates a checkerboard pattern with two specified colors."}],"navigatorTitle":[{"text":"MDLCheckerboardTexture","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLCheckerboardTexture","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"9.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.11","beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"introducedAt":"9.0","beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"introducedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"color1","op":"replace","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"color1"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture"]]},"path":"/hierarchy"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Configuring the Checkerboard Pattern","anchor":"Configuring-the-Checkerboard-Pattern","generated":true,"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGColorRef","preciseIdentifier":"c:@T@CGColorRef","text":"CGColorRef","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"color1","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color2/title","value":"color2","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color2/fragments","value":[{"text":"color2","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1divisions/title","value":"divisions","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1divisions/fragments","value":[{"text":"divisions","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CGColorRef/title","value":"CGColorRef","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color1/title","value":"color1","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color1/fragments","value":[{"kind":"identifier","text":"color1"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/title","value":"MDLCheckerboardTexture","op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/fragments","value":[{"kind":"identifier","text":"MDLCheckerboardTexture"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/navigatorTitle","value":[{"kind":"identifier","text":"MDLCheckerboardTexture"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}