{"kind":"symbol","variants":[{"paths":["/documentation/modelio/mdlcheckerboardtexture/divisions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/modelio/mdlcheckerboardtexture/divisions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions"},"seeAlsoSections":[{"title":"Configuring the Checkerboard Pattern","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2"],"generated":true,"anchor":"Configuring-the-Checkerboard-Pattern"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The number of squares along each dimension in the checkerboard pattern.","type":"text"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"divisions","kind":"identifier"}],"roleHeading":"Instance Property","title":"divisions","modules":[{"name":"Model I/O"}],"externalID":"c:objc(cs)MDLCheckerboardTexture(py)divisions","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"divisions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false},{"introducedAt":"9.0","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"introducedAt":"13.1","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"10.11","unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"introducedAt":"9.0","unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS","deprecated":false}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"divisions"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sf","kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"For example, a value of 2 creates a checkerboard pattern of four squares (a 2 x 2 grid), where the top-left and bottom-right squares use the ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1","isActive":true,"type":"reference"},{"text":" color and the other two squares use the ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2","isActive":true,"type":"reference"},{"text":" color. A value of 4 creates a pattern of 16 squares (a 4 x 4 grid), and so on.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Changing the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1"},{"type":"text","text":", or "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2"},{"type":"text","text":" properties invalidates the cache, causing Model I/O to regenerate texel data the next time it is needed."}],"type":"paragraph"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions":{"url":"/documentation/modelio/mdlcheckerboardtexture/divisions","title":"divisions","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/divisions","abstract":[{"type":"text","text":"The number of squares along each dimension in the checkerboard pattern."}],"navigatorTitle":[{"text":"divisions","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"divisions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture":{"url":"/documentation/modelio/mdlcheckerboardtexture","title":"MDLCheckerboardTexture","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture","abstract":[{"type":"text","text":"A generator of texel data that creates a checkerboard pattern with two specified colors."}],"navigatorTitle":[{"text":"MDLCheckerboardTexture","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLCheckerboardTexture","kind":"identifier"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2":{"url":"/documentation/modelio/mdlcheckerboardtexture/color2","title":"color2","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2","abstract":[{"type":"text","text":"The color for the other half of the squares in the checkerboard pattern."}],"navigatorTitle":[{"text":"color2","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color2","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGColor","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGColorRef"},{"text":"?","kind":"text"}]},"doc://com.externally.resolved.symbol/s:Sf":{"type":"topic","kind":"symbol","title":"Float","identifier":"doc://com.externally.resolved.symbol/s:Sf","url":"/documentation/Swift/Float","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Float"}],"role":"symbol","abstract":[{"type":"text","text":"A single-precision, floating-point value type."}]},"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1":{"url":"/documentation/modelio/mdlcheckerboardtexture/color1","title":"color1","role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1","abstract":[{"type":"text","text":"The color for half of the squares in the checkerboard pattern."}],"navigatorTitle":[{"text":"color1","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGColor","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGColorRef"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.1","beta":false},{"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"10.11","beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"9.0","beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0","beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"divisions","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"divisions"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color1","doc://com.apple.modelio/documentation/ModelIO/MDLCheckerboardTexture/color2"],"title":"Configuring the Checkerboard Pattern","generated":true,"anchor":"Configuring-the-Checkerboard-Pattern"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"divisions","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"divisions","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1divisions/title"},{"op":"replace","value":[{"kind":"identifier","text":"divisions"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1divisions/fragments"},{"op":"replace","value":"MDLCheckerboardTexture","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/title"},{"op":"replace","value":[{"text":"MDLCheckerboardTexture","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MDLCheckerboardTexture"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture/navigatorTitle"},{"op":"replace","value":"color2","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color2/title"},{"op":"replace","value":[{"kind":"identifier","text":"color2"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color2/fragments"},{"op":"replace","value":"color1","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color1/title"},{"op":"replace","value":[{"text":"color1","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCheckerboardTexture~1color1/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}