{
  "abstract": [
    {
      "text": "The user is awake.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/awake"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKCategoryValueSleepAnalysis@HKCategoryValueSleepAnalysisAwake",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "awake"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryValueSleepAnalysisAwake"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKCategoryValueSleepAnalysis.awake"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "awake"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis": {
      "abstract": [
        {
          "text": "Categories that represent the result of a sleep analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysis"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysis"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepCore": {
      "abstract": [
        {
          "text": "The user is in light or intermediate sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asleepCore"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepCore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysisAsleepCore"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis.asleepCore",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis/asleepcore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepDeep": {
      "abstract": [
        {
          "text": "The user is in deep sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asleepDeep"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepDeep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysisAsleepDeep"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis.asleepDeep",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis/asleepdeep"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepREM": {
      "abstract": [
        {
          "text": "The user is in REM sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asleepREM"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepREM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysisAsleepREM"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis.asleepREM",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis/asleeprem"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepUnspecified": {
      "abstract": [
        {
          "text": "The user is asleep, but the specific stage isn’t known.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asleepUnspecified"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepUnspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysisAsleepUnspecified"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis.asleepUnspecified",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis/asleepunspecified"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/awake": {
      "abstract": [
        {
          "text": "The user is awake.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "awake"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/awake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysisAwake"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis.awake",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis/awake"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Values-for-Tracking-Sleep-States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepCore",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepDeep",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepREM",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepUnspecified"
      ],
      "title": "Values for Tracking Sleep States"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryValueSleepAnalysisAwake"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysisAwake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Values-for-Tracking-Sleep-States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepCore",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepDeep",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepREM",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis/asleepUnspecified"
              ],
              "title": "Values for Tracking Sleep States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKCategoryValueSleepAnalysisAwake"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/title",
          "value": "HKCategoryValueSleepAnalysis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepUnspecified/title",
          "value": "HKCategoryValueSleepAnalysisAsleepUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepUnspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysisAsleepUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1awake/title",
          "value": "HKCategoryValueSleepAnalysisAwake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1awake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysisAwake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepCore/title",
          "value": "HKCategoryValueSleepAnalysisAsleepCore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepCore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysisAsleepCore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepREM/title",
          "value": "HKCategoryValueSleepAnalysisAsleepREM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepREM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysisAsleepREM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepDeep/title",
          "value": "HKCategoryValueSleepAnalysisAsleepDeep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis~1asleepDeep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysisAsleepDeep"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluesleepanalysis/awake"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluesleepanalysis/awake"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
