{"metadata":{"navigatorTitle":[{"text":"drawWithBox:toContext:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PDFDisplayBox","kind":"typeIdentifier","preciseIdentifier":"c:@E@PDFDisplayBox"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGContext","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGContextRef"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)PDFPage(im)drawWithBox:toContext:","platforms":[{"introducedAt":"11.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"11.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"introducedAt":"10.12","unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"introducedAt":"11.0","unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false,"beta":false}],"title":"draw(with:to:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"PDFKit"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/pdfkit/pdfpage/draw(with:to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/pdfkit/pdfpage/draw(with:to:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"box","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PDFDisplayBox","kind":"typeIdentifier","preciseIdentifier":"c:@E@PDFDisplayBox","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGContext","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGContextRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CGContextRef"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/draw(with:to:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/thumbnail(of:for:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)"]}],"references":{"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGContextRef","text":"CGContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@PDFDisplayBox","text":"PDFDisplayBox","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"transform(_:for:)","navigatorTitle":[{"text":"transformContext:forBox:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"/documentation/pdfkit/pdfpage/transform(_:for:)","kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@PDFDisplayBox","kind":"typeIdentifier","text":"PDFDisplayBox"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform","kind":"typeIdentifier"}],"title":"transform(for:)","navigatorTitle":[{"text":"transformForBox:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"/documentation/pdfkit/pdfpage/transform(for:)","kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"PDFPage"},{"type":"text","text":", a subclass of "},{"type":"codeVoice","code":"NSObject"},{"type":"text","text":", defines methods used to render PDF pages and work with annotations, text, and selections."}],"title":"PDFPage","url":"/documentation/pdfkit/pdfpage","navigatorTitle":[{"kind":"identifier","text":"PDFPage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFPage"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox":{"title":"PDFDisplayBox","role":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox","navigatorTitle":[{"text":"PDFDisplayBox","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFDisplayBox","kind":"identifier"}],"abstract":[{"text":"The following box types may be used with ","type":"text"},{"type":"codeVoice","code":"PDFPage"},{"text":" drawing and bounds-setting methods. See the Adobe PDF Specification for more information on box types, units, and coordinate systems.","type":"text"}],"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdisplaybox"},"doc://com.externally.resolved.symbol/c:@T@CGContextRef":{"type":"topic","fragments":[{"text":"class ","kind":"text"},{"text":"CGContext","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGContextRef","title":"CGContext","url":"/documentation/coregraphics/cgcontext","abstract":[{"type":"text","text":"A Quartz 2D drawing environment."}],"role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/thumbnail(of:for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@PDFDisplayBox","text":"PDFDisplayBox","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"abstract":[],"url":"/documentation/pdfkit/pdfpage/thumbnail(of:for:)","title":"thumbnail(of:for:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"thumbnailOfSize:forBox:"}],"type":"topic","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/thumbnail(of:for:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/draw(with:to:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFDisplayBox","preciseIdentifier":"c:@E@PDFDisplayBox"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"title":"draw(with:to:)","navigatorTitle":[{"kind":"identifier","text":"drawWithBox:toContext:"}],"type":"topic","abstract":[],"role":"symbol","url":"/documentation/pdfkit/pdfpage/draw(with:to:)","kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/draw(with:to:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"11.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"11.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"introducedAt":"10.12","unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"introducedAt":"11.0","unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"drawWithBox:toContext:","op":"replace","path":"/metadata/title"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"drawWithBox:toContext:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Instance Methods","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/thumbnail(of:for:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"drawWithBox:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PDFDisplayBox","kind":"typeIdentifier","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox","preciseIdentifier":"c:@E@PDFDisplayBox"},{"text":") ","kind":"text"},{"text":"box","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGContextRef","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@CGContextRef","preciseIdentifier":"c:@T@CGContextRef"},{"text":") ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(_:for:)/title","value":"transformContext:forBox:"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(_:for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformContext:forBox:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(for:)/title","value":"transformForBox:"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformForBox:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage/title","value":"PDFPage"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage/fragments","value":[{"text":"PDFPage","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage/navigatorTitle","op":"replace","value":[{"text":"PDFPage","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/title","op":"replace","value":"PDFDisplayBox"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/fragments","op":"replace","value":[{"text":"PDFDisplayBox","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/navigatorTitle","op":"replace","value":[{"text":"PDFDisplayBox","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CGContextRef/title","value":"CGContextRef"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1thumbnail(of:for:)/title","value":"thumbnailOfSize:forBox:"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1thumbnail(of:for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"thumbnailOfSize:forBox:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1draw(with:to:)/title","value":"drawWithBox:toContext:"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1draw(with:to:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawWithBox:toContext:"}]}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}