{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/draw(with:to:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","identifier":"doc://com.externally.resolved.symbol/c:@S@CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"box"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFDisplayBox","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox","preciseIdentifier":"c:@E@PDFDisplayBox"},{"kind":"text","text":") -> "},{"text":"UIImage","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]},{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thumbnail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSSize","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSSize"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"box","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PDFDisplayBox","kind":"typeIdentifier","preciseIdentifier":"c:@E@PDFDisplayBox","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox"},{"text":") -> ","kind":"text"},{"text":"NSImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage"}],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"thumbnailOfSize:forBox:"}],"symbolKind":"method","modules":[{"name":"PDFKit"}],"title":"thumbnail(of:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"thumbnail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFDisplayBox","preciseIdentifier":"c:@E@PDFDisplayBox"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"roleHeading":"Instance Method","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"11.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"11.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.13"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"externalID":"c:objc(cs)PDFPage(im)thumbnailOfSize:forBox:"},"sections":[],"identifier":{"url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/thumbnail(of:for:)","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/pdfkit/pdfpage/thumbnail(of:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/pdfkit/pdfpage/thumbnail(of:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"PDFPage"},{"type":"text","text":", a subclass of "},{"type":"codeVoice","code":"NSObject"},{"type":"text","text":", defines methods used to render PDF pages and work with annotations, text, and selections."}],"title":"PDFPage","url":"/documentation/pdfkit/pdfpage","navigatorTitle":[{"kind":"identifier","text":"PDFPage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFPage"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)UIImage":{"role":"symbol","url":"/documentation/UIKit/UIImage","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIImage","title":"UIImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"kind":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox":{"title":"PDFDisplayBox","role":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox","navigatorTitle":[{"text":"PDFDisplayBox","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFDisplayBox","kind":"identifier"}],"abstract":[{"text":"The following box types may be used with ","type":"text"},{"type":"codeVoice","code":"PDFPage"},{"text":" drawing and bounds-setting methods. See the Adobe PDF Specification for more information on box types, units, and coordinate systems.","type":"text"}],"type":"topic","kind":"symbol","url":"/documentation/pdfkit/pdfdisplaybox"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/thumbnail(of:for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@PDFDisplayBox","text":"PDFDisplayBox","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"abstract":[],"url":"/documentation/pdfkit/pdfpage/thumbnail(of:for:)","title":"thumbnail(of:for:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"thumbnailOfSize:forBox:"}],"type":"topic","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/thumbnail(of:for:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGContextRef","text":"CGContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@PDFDisplayBox","text":"PDFDisplayBox","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"transform(_:for:)","navigatorTitle":[{"text":"transformContext:forBox:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"/documentation/pdfkit/pdfpage/transform(_:for:)","kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@PDFDisplayBox","kind":"typeIdentifier","text":"PDFDisplayBox"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform","kind":"typeIdentifier"}],"title":"transform(for:)","navigatorTitle":[{"text":"transformForBox:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"/documentation/pdfkit/pdfpage/transform(for:)","kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.externally.resolved.symbol/c:@S@CGSize":{"url":"/documentation/corefoundation/cgsize","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGSize"}],"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@S@CGSize","abstract":[{"type":"text","text":"A structure that contains width and height values."}],"type":"topic","title":"CGSize"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/draw(with:to:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFDisplayBox","preciseIdentifier":"c:@E@PDFDisplayBox"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"title":"draw(with:to:)","navigatorTitle":[{"kind":"identifier","text":"drawWithBox:toContext:"}],"type":"topic","abstract":[],"role":"symbol","url":"/documentation/pdfkit/pdfpage/draw(with:to:)","kind":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/draw(with:to:)"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"13.1","beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"10.13","beta":false,"unavailable":false,"name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"thumbnailOfSize:forBox:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"thumbnailOfSize:forBox:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage"]]},"path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/draw(with:to:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(_:for:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/transform(for:)"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSImage","kind":"typeIdentifier","text":"NSImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"thumbnailOfSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier","text":"NSSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":" "},{"kind":"identifier","text":"forBox:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@PDFDisplayBox","kind":"typeIdentifier","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox","text":"PDFDisplayBox"},{"kind":"text","text":") "},{"kind":"internalParam","text":"box"},{"kind":"text","text":";"}],"platforms":["macOS"]},{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"thumbnailOfSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","identifier":"doc://com.externally.resolved.symbol/c:@S@CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forBox:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PDFDisplayBox","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox","kind":"typeIdentifier","preciseIdentifier":"c:@E@PDFDisplayBox"},{"text":") ","kind":"text"},{"text":"box","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage/title","value":"PDFPage","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage/fragments","value":[{"kind":"identifier","text":"PDFPage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage/navigatorTitle","value":[{"kind":"identifier","text":"PDFPage"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIImage/fragments","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIImage"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/title","value":"PDFDisplayBox","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/fragments","value":[{"text":"PDFDisplayBox","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/navigatorTitle","value":[{"text":"PDFDisplayBox","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1thumbnail(of:for:)/title","value":"thumbnailOfSize:forBox:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1thumbnail(of:for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"thumbnailOfSize:forBox:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(_:for:)/title","value":"transformContext:forBox:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformContext:forBox:"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(_:for:)/fragments","op":"replace"},{"value":"transformForBox:","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(for:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"transformForBox:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1transform(for:)/fragments","op":"replace"},{"value":"drawWithBox:toContext:","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1draw(with:to:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawWithBox:toContext:"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1draw(with:to:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}