{
  "abstract": [
    {
      "text": "Creates and returns an ",
      "type": "text"
    },
    {
      "code": "CAConstraint",
      "type": "codeVoice"
    },
    {
      "text": " object with the specified parameters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/constraintWithAttribute:relativeTo:attribute:scale:offset:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CAConstraint(cm)constraintWithAttribute:relativeTo:attribute:scale:offset:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "constraintWithAttribute:relativeTo:attribute:scale:offset:"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "constraintWithAttribute:relativeTo:attribute:scale:offset:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "constraintWithAttribute:relativeTo:attribute:scale:offset:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "constraintWithAttribute:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintAttribute",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CAConstraintAttribute",
              "text": "CAConstraintAttribute"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "attr"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "relativeTo:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "srcId"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "attribute:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintAttribute",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CAConstraintAttribute",
              "text": "CAConstraintAttribute"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "srcAttr"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scale:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "m"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "offset:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "c"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The attribute of the layer for which to create a new constraint.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attr"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the layer that this constraint is calculated relative to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "srcId"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The attribute of ",
                  "type": "text"
                },
                {
                  "code": "srcLayer",
                  "type": "codeVoice"
                },
                {
                  "text": " the constraint is calculated relative to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "srcAttr"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The amount to scale the value of ",
                  "type": "text"
                },
                {
                  "code": "srcAttr",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "m"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The offset from the ",
                  "type": "text"
                },
                {
                  "code": "srcAttr",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "c"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "code": "CAConstraint",
              "type": "codeVoice"
            },
            {
              "text": " object with the specified parameters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value for the constraint is calculated as ((",
              "type": "text"
            },
            {
              "code": "srcAttr",
              "type": "codeVoice"
            },
            {
              "text": " * scale) + offset).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint": {
      "abstract": [
        {
          "text": "A representation of a single layout constraint between two layers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAConstraint"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAConstraint"
        }
      ],
      "role": "symbol",
      "title": "CAConstraint",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraint"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/constraintWithAttribute:relativeTo:attribute:scale:offset:": {
      "abstract": [
        {
          "text": "Creates and returns an ",
          "type": "text"
        },
        {
          "code": "CAConstraint",
          "type": "codeVoice"
        },
        {
          "text": " object with the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "constraintWithAttribute:relativeTo:attribute:scale:offset:"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/constraintWithAttribute:relativeTo:attribute:scale:offset:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintWithAttribute:relativeTo:attribute:scale:offset:"
        }
      ],
      "role": "symbol",
      "title": "constraintWithAttribute:relativeTo:attribute:scale:offset:",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraint/constraintwithattribute:relativeto:attribute:scale:offset:"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:)": {
      "abstract": [
        {
          "text": "Creates and returns an ",
          "type": "text"
        },
        {
          "code": "CAConstraint",
          "type": "codeVoice"
        },
        {
          "text": " object with the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAConstraintAttribute",
          "text": "CAConstraintAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAConstraintAttribute",
          "text": "CAConstraintAttribute"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintWithAttribute:relativeTo:attribute:"
        }
      ],
      "role": "symbol",
      "title": "init(attribute:relativeTo:attribute:)",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraint/init(attribute:relativeto:attribute:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:offset:)": {
      "abstract": [
        {
          "text": "Creates and returns an ",
          "type": "text"
        },
        {
          "code": "CAConstraint",
          "type": "codeVoice"
        },
        {
          "text": " object with the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAConstraintAttribute",
          "text": "CAConstraintAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAConstraintAttribute",
          "text": "CAConstraintAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:offset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintWithAttribute:relativeTo:attribute:offset:"
        }
      ],
      "role": "symbol",
      "title": "init(attribute:relativeTo:attribute:offset:)",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraint/init(attribute:relativeto:attribute:offset:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:scale:offset:)": {
      "abstract": [
        {
          "text": "Returns an ",
          "type": "text"
        },
        {
          "code": "CAConstraint",
          "type": "codeVoice"
        },
        {
          "text": " object with the specified parameters. Designated initializer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAConstraintAttribute",
          "text": "CAConstraintAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAConstraintAttribute",
          "text": "CAConstraintAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:scale:offset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttribute:relativeTo:attribute:scale:offset:"
        }
      ],
      "role": "symbol",
      "title": "init(attribute:relativeTo:attribute:scale:offset:)",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraint/init(attribute:relativeto:attribute:scale:offset:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintAttribute": {
      "abstract": [
        {
          "text": "The constraint attribute type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAConstraintAttribute"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraintAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAConstraintAttribute"
        }
      ],
      "role": "symbol",
      "title": "CAConstraintAttribute",
      "type": "topic",
      "url": "/documentation/quartzcore/caconstraintattribute"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514",
      "title": "Core Animation Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Animation Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Create-a-New-Constraint",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:offset:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAConstraint/init(attribute:relativeTo:attribute:scale:offset:)"
      ],
      "title": "Create a New Constraint"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint~1init(attribute:relativeTo:attribute:scale:offset:)/title",
          "value": "initWithAttribute:relativeTo:attribute:scale:offset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint~1init(attribute:relativeTo:attribute:scale:offset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttribute:relativeTo:attribute:scale:offset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraintAttribute/title",
          "value": "CAConstraintAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraintAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraintAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraintAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraintAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint/title",
          "value": "CAConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint~1init(attribute:relativeTo:attribute:offset:)/title",
          "value": "constraintWithAttribute:relativeTo:attribute:offset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint~1init(attribute:relativeTo:attribute:offset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "constraintWithAttribute:relativeTo:attribute:offset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint~1init(attribute:relativeTo:attribute:)/title",
          "value": "constraintWithAttribute:relativeTo:attribute:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAConstraint~1init(attribute:relativeTo:attribute:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "constraintWithAttribute:relativeTo:attribute:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/caconstraint/constraintwithattribute:relativeto:attribute:scale:offset:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
