{"variants":[{"paths":["/documentation/vision/saliencyimageobservation/init(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"Vision","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"visionOS"}],"title":"init(_:)","modules":[{"name":"Vision"}],"externalID":"s:6Vision24SaliencyImageObservationVyACSgSo010VNSaliencycD0Ccfc","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"typeIdentifier","text":"VNSaliencyImageObservation","preciseIdentifier":"c:objc(cs)VNSaliencyImageObservation"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.vision/documentation/Vision","doc://com.apple.vision/documentation/Vision/SaliencyImageObservation"]]},"abstract":[{"type":"text","text":"Creates a saliency image observation."}],"identifier":{"url":"doc://com.apple.vision/documentation/Vision/SaliencyImageObservation/init(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observation","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.vision/documentation/Vision/VNSaliencyImageObservation","text":"VNSaliencyImageObservation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VNSaliencyImageObservation"},{"text":")","kind":"text"}]}]}],"sections":[],"references":{"doc://com.apple.vision/documentation/Vision/SaliencyImageObservation":{"kind":"symbol","abstract":[{"text":"An observation that contains a grayscale heat map of important areas across an image.","type":"text"}],"url":"/documentation/vision/saliencyimageobservation","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SaliencyImageObservation"}],"navigatorTitle":[{"kind":"identifier","text":"SaliencyImageObservation"}],"title":"SaliencyImageObservation","identifier":"doc://com.apple.vision/documentation/Vision/SaliencyImageObservation","type":"topic"},"doc://com.apple.vision/documentation/Vision":{"role":"collection","url":"/documentation/vision","title":"Vision","kind":"symbol","identifier":"doc://com.apple.vision/documentation/Vision","abstract":[{"type":"text","text":"Apply computer vision algorithms to perform a variety of tasks on input images and videos."}],"type":"topic"},"doc://com.apple.vision/documentation/Vision/SaliencyImageObservation/init(_:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"VNSaliencyImageObservation","preciseIdentifier":"c:objc(cs)VNSaliencyImageObservation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(_:)","url":"/documentation/vision/saliencyimageobservation/init(_:)","type":"topic","identifier":"doc://com.apple.vision/documentation/Vision/SaliencyImageObservation/init(_:)","abstract":[{"text":"Creates a saliency image observation.","type":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.apple.vision/documentation/Vision/VNSaliencyImageObservation":{"navigatorTitle":[{"kind":"identifier","text":"VNSaliencyImageObservation"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VNSaliencyImageObservation"}],"role":"symbol","title":"VNSaliencyImageObservation","url":"/documentation/vision/vnsaliencyimageobservation","identifier":"doc://com.apple.vision/documentation/Vision/VNSaliencyImageObservation","type":"topic","abstract":[{"type":"text","text":"An observation that contains a grayscale heat map of important areas across an image."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNSaliencyImageObservation/title","op":"replace","value":"VNSaliencyImageObservation"},{"path":"/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNSaliencyImageObservation/fragments","op":"replace","value":[{"kind":"identifier","text":"VNSaliencyImageObservation"}]},{"path":"/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNSaliencyImageObservation/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"VNSaliencyImageObservation"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}