{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/init(topRadius:bottomRadius:height:)"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNCone"]]},"abstract":[{"type":"text","text":"Creates a cone geometry with the given top radius, bottom radius, and height."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scncone/init(topradius:bottomradius:height:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scncone/init(topradius:bottomradius:height:)"]}],"metadata":{"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false},{"unavailable":false,"name":"watchOS","deprecated":false,"beta":false}],"roleHeading":"Initializer","role":"symbol","modules":[{"name":"SceneKit"}],"externalID":"c:objc(cs)SCNCone(cm)coneWithTopRadius:bottomRadius:height:","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"coneWithTopRadius:bottomRadius:height:"}],"symbolKind":"init","title":"init(topRadius:bottomRadius:height:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"topRadius","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius of the cone’s top, forming a circle in the x- and z-axis dimensions of its local coordinate space."}]}]},{"name":"bottomRadius","content":[{"type":"paragraph","inlineContent":[{"text":"The radius of the cone’s base, forming a circle in the x- and z-axis dimensions of its local coordinate space.","type":"text"}]}]},{"name":"height","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The height of the cone along the y-axis of its local coordinate space."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A new cone geometry."}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"The cone is centered in its local coordinate system. For example, if you create a cone whose bottom radius is ","type":"text"},{"type":"codeVoice","code":"5.0"},{"text":", top radius is ","type":"text"},{"type":"codeVoice","code":"0.0"},{"text":", and height is ","type":"text"},{"type":"codeVoice","code":"10.0"},{"text":", its apex is at the point ","type":"text"},{"type":"codeVoice","code":"{0, 5.0, 0}"},{"text":", and its base lies in the plane whose y-coordinate is ","type":"text"},{"type":"codeVoice","code":"-5.0"},{"text":", extending from ","type":"text"},{"type":"codeVoice","code":"-5.0"},{"text":" to ","type":"text"},{"type":"codeVoice","code":"5.0"},{"text":" along both the x- and z-axes.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Pass zero for "},{"code":"topRadius","type":"codeVoice"},{"type":"text","text":" or "},{"code":"bottomRadius","type":"codeVoice"},{"type":"text","text":" or parameter to create a cone whose sides taper to a single point, or a different value to create a frustum with a circular top."}],"type":"paragraph"}]}],"references":{"doc://com.apple.scenekit/documentation/SceneKit/SCNCone":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone","abstract":[{"text":"A right circular cone or frustum geometry.","type":"text"}],"url":"/documentation/scenekit/scncone","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNCone"}],"title":"SCNCone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNCone"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/init(topRadius:bottomRadius:height:)":{"url":"/documentation/scenekit/scncone/init(topradius:bottomradius:height:)","role":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"title":"init(topRadius:bottomRadius:height:)","navigatorTitle":[{"kind":"identifier","text":"coneWithTopRadius:bottomRadius:height:"}],"abstract":[{"text":"Creates a cone geometry with the given top radius, bottom radius, and height.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNCone/init(topRadius:bottomRadius:height:)"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"role":"symbol","kind":"symbol","title":"CGFloat","type":"topic","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"role":"symbol","kind":"symbol","title":"CGFloat","type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false},{"unavailable":false,"name":"watchOS","deprecated":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Method","op":"replace","path":"/metadata/roleHeading"},{"value":"coneWithTopRadius:bottomRadius:height:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"coneWithTopRadius:bottomRadius:height:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNCone"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"coneWithTopRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"topRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bottomRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bottomRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"height:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"height","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"parameters":[{"name":"topRadius","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius of the cone’s top, forming a circle in the x- and z-axis dimensions of its local coordinate space."}]}]},{"name":"bottomRadius","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius of the cone’s base, forming a circle in the x- and z-axis dimensions of its local coordinate space."}]}]},{"name":"height","content":[{"type":"paragraph","inlineContent":[{"text":"The height of the cone along the y-axis of its local coordinate space.","type":"text"}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new cone geometry."}]}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"value":"SCNCone","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/title","op":"replace"},{"value":[{"text":"SCNCone","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SCNCone"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/navigatorTitle","op":"replace"},{"value":"coneWithTopRadius:bottomRadius:height:","path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1init(topRadius:bottomRadius:height:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"coneWithTopRadius:bottomRadius:height:"}],"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone~1init(topRadius:bottomRadius:height:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}