{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_3-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Xcode 12.3 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode 12.3 includes SDKs for iOS 14.3, iPadOS 14.3, tvOS 14.3, watchOS 7.2, and macOS Big Sur 11.1.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The Xcode 12.3 release supports on-device debugging for iOS 9 and later, tvOS 9 and later, and watchOS 2 and later.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Xcode 12.3 requires a Mac running macOS 10.15.4 or later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "General",
          "level": 3,
          "text": "General",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Improved responsiveness of macOS mouse and keyboard events while under heavy load, such as when building a large project while running Simulator. (71819679)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The first time you launch Xcode on a Mac with Apple silicon without Rosetta installed, Xcode prompts you to install Rosetta.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "The prompt prevents any interaction, and blocks Xcode from launching. (70853975) (FB8848625)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": Launch an x86_64 process to trigger the system’s Rosetta prompt.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Build-System",
          "level": 3,
          "text": "Build System",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue where ",
                      "type": "text"
                    },
                    {
                      "code": "xcodebuild",
                      "type": "codeVoice"
                    },
                    {
                      "text": " sometimes logged unexpected output about failed event streams. (33401512)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Devices",
          "level": 3,
          "text": "Devices",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue that caused Xcode to spontaneously lose device configuration information for an Apple Watch.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This data loss caused Xcode to either crash or display an error stating that your app “cannot be installed on (null)”. (54768855)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue where Xcode could fail to prepare a wirelessly connected iOS device for debugging with the error “Failed _shouldMakeReadyForDevelopment check”. (61227501) (FB7649607)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue that blocked simulator runtimes from being available when running command-line tools like ",
                      "type": "text"
                    },
                    {
                      "code": "simctl",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "xcodebuild",
                      "type": "codeVoice"
                    },
                    {
                      "text": " from a non-root LaunchDaemon, or when launching as a different user from the current user (for example, with ",
                      "type": "text"
                    },
                    {
                      "code": "sudo",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "launchctl",
                      "type": "codeVoice"
                    },
                    {
                      "text": "). (62188195, 69738053)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue that could cause Xcode to get interrupted when copying symbols from iOS devices, and never finish preparing iOS devices for debugging.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "The failure mainly occurred on Xcode installations used to debug multiple iOS devices which are running the same version of iOS.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This bug impacted the performance of launching executables on iOS devices and attaching the debugger to them. (68221778) (FB8611135)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Documentation-Viewer",
          "level": 3,
          "text": "Documentation Viewer",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed a crash that could happen when opening the Documentation Window if you installed Xcode outside of ",
                      "type": "text"
                    },
                    {
                      "code": "/Applications",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". (70631583)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Interface-Builder",
          "level": 3,
          "text": "Interface Builder",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed iOS storyboard rendering issues when using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UISplitViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " simulated metric sizes with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITabBarController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (69054879) (FB8704013)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue that caused Xcode to warn about multiple deprecated system color references in saved documents. (69667149) (FB8749086)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue where the background color of a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextField",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " could appear transparent in your app instead of the default color. (70559650)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "SceneKit",
          "level": 3,
          "text": "SceneKit",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On a Mac with Apple silicon, SceneKit editor may display pixelated graphics or an empty window. (71239899, 71395291, 72141599)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": Click on the Display option icon at the bottom-right of the 3D viewport, then disable the Outline selection and Grid options.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Simulator",
          "level": 3,
          "text": "Simulator",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "simctl",
                      "type": "codeVoice"
                    },
                    {
                      "text": " now prints “Recording started” to ",
                      "type": "text"
                    },
                    {
                      "code": "stderr",
                      "type": "codeVoice"
                    },
                    {
                      "text": " when it has enqueued the first frame of a video recording.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Scripts or other automation can wait for that message before proceeding, to ensure the first part of the operation is captured in the resulting video. (57915463)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "simctl",
                      "type": "codeVoice"
                    },
                    {
                      "text": " video recordings no longer cut off the end of the video when no screen updates are happening.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "The recording timeline now holds the last frame and extends until you terminate the recording with Control-C (SIGINT). (67952344) (FB8565355)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "CoreSimulator now excludes its caches directory from Time Machine backups by default. (68782191)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When using macOS Big Sur 11.0 or 11.0.1 on your Mac, you can’t run a simulated device with watchOS 6, and you can’t run apps with 32-bit code in simulated devices running watchOS 7.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This issue is fixed in macOS Big Sur 11.1. (69093569)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Siri may not respond in a simulated device running on a Mac with Apple silicon. (71604992)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apps may not detect all game controller events when running in simulated devices on Macs with Apple silicon. (71651414)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Swift",
          "level": 3,
          "text": "Swift",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed a failure that could occur when compiling a project with Mac Catalyst that imports ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/OSLog",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " from Swift. (68597591)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes": {
      "abstract": [
        {
          "text": "Learn about changes to Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes",
      "kind": "article",
      "role": "collection",
      "title": "Xcode Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-12-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_0_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_0_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.0.1 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-12_0_1-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.1 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-12_1-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.2 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-12_2-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.4 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-12_4-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.5 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-12_5-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_5_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_5_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.5.1 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-12_5_1-release-notes"
    },
    "doc://com.apple.documentation/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/OSLog"
    },
    "doc://com.apple.documentation/documentation/UIKit/UISplitViewController": {
      "abstract": [
        {
          "text": "A container view controller that implements a hierarchical interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UISplitViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISplitViewController",
      "type": "topic",
      "url": "/documentation/UIKit/UISplitViewController"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITabBarController": {
      "abstract": [
        {
          "text": "A container view controller that manages a multiselection interface, where the selection determines which child view controller to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITabBarController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITabBarController",
      "type": "topic",
      "url": "/documentation/UIKit/UITabBarController"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITextField": {
      "abstract": [
        {
          "text": "An object that displays an editable text area in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextField"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITextField",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextField",
      "type": "topic",
      "url": "/documentation/UIKit/UITextField"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Xcode-12",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_5_1-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_5-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_4-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_2-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_1-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12_0_1-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-12-release-notes"
      ],
      "title": "Xcode 12"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UISplitViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITextField/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextField"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIControl",
              "text": "UIControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITabBarController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITabBarController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
