{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_1-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Xcode 11.1 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode 11.1 includes SDKs for iOS 13.1, macOS Catalina 10.15, watchOS 6, and tvOS",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "13. Xcode 11.1 supports on-device debugging for iOS 8 and later, tvOS 9 and later,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and watchOS 2 and later. Xcode 11.1 requires a Mac running macOS Mojave 10.14.4 or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "General",
          "level": 3,
          "text": "General",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Xcode may fail to update from the Mac App Store after updating to macOS Catalina. (56061273)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": To trigger a new download you can delete the existing Xcode.app",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "or temporarily change the file extension so it is no longer visible to the App Store.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Asset-Catalogs",
          "level": 3,
          "text": "Asset Catalogs",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Images in the asset catalog won’t be found at runtime when running on watchOS 4. (55395258)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Interface-Builder",
          "level": 3,
          "text": "Interface Builder",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You can now preview your interface for the 7th generation iPad. (53957165)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "There is an issue with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITabBarController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "where decoding an instance from a storyboard will create some extra views at the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "left end of the screen. Developers may remove these by applying a workaround. (55310448)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": To remove the extraneous views from Storyboard, create a subclass",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "of a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITabBarController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and add the following",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "snippet in the class’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/init(coder:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "class WorkaroundTabBarController: UITabBarController {",
                    "    required init?(coder: NSCoder) {",
                    "        super.init(coder: coder)",
                    "",
                    "        // This must be run immediately after the call to super.",
                    "        if tabBar.subviews.count > 1 {",
                    "            tabBar.subviews[0].isHidden = true",
                    "        }",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed a crash that sometimes occurred when compiling XIB files in iOS projects",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "that backwards deploy to iOS versions earlier than 13.0. (55271752)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Localization",
          "level": 3,
          "text": "Localization",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITableViewCell",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " labels in storyboards and",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "XIB files do not use localized string values from the strings file at runtime. (52839404)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Simulator",
          "level": 3,
          "text": "Simulator",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On macOS Catalina, iCloud Drive will crash in a loop on simulated devices running",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "older versions of iOS. (51392951, 54282967, 54818084)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": Log out of iCloud in impacted simulators to halt the crash cycle.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "CarPlay works on iOS 13.1 simulators. (54492162)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Swift",
          "level": 3,
          "text": "Swift",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "NEHotspotConfigurationError",
                      "type": "codeVoice"
                    },
                    {
                      "text": " enum from the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "framework changed from ",
                      "type": "text"
                    },
                    {
                      "code": "NS_ENUM",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to ",
                      "type": "text"
                    },
                    {
                      "code": "NS_ERROR_ENUM",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", which can cause compiler",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "errors in existing Swift code that uses the enum. For example, in code like this:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "let code = NEHotspotConfigurationError(rawValue: errorCode)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                },
                {
                  "inlineContent": [
                    {
                      "text": "You will see the error message: “error: incorrect argument label in call (have ‘rawValue:’, expected ‘_nsError:’).” (54134493)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": Replace references of ",
                      "type": "text"
                    },
                    {
                      "code": "NEHotspotConfigurationError",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfigurationError",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the above example, change the code to:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "let code = NEHotspotConfigurationError.Code(rawValue: errorCode)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "SwiftUI",
          "level": 3,
          "text": "SwiftUI",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fixed an issue with Xcode Previews where debugging a preview would no longer pin",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the preview, and navigating would lose the debug session. (54758098)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Swift-Packages",
          "level": 3,
          "text": "Swift Packages",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If an iOS, tvOS, or watchOS app uses a Swift Package that builds a dynamic library,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "it cannot be submitted to the App Store. (55564324)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": Modify the Package manifest to build a static library.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "watchOS",
          "level": 3,
          "text": "watchOS",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "watchOS applications built with the watchOS 6 SDK and a deployment target of watchOS",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "5.3 will crash on launch when run on watchOS 5.3. (55360395)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": ": Set the ",
                      "type": "text"
                    },
                    {
                      "code": "__WKEXTENSIONMAIN_LEGACY_TARGET_5_3",
                      "type": "codeVoice"
                    },
                    {
                      "text": " build setting to",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "“legacy,” or use another deployment target instead of 5.3.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes": {
      "abstract": [
        {
          "text": "Learn about changes to Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes",
      "kind": "article",
      "role": "collection",
      "title": "Xcode Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.2 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_2-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_2_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_2_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.2.1 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_2_1-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.3 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_3-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_3_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_3_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.3.1 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_3_1-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.4 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_4-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_4_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_4_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.4.1 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_4_1-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.5 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_5-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_6-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_6-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.6 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_6-release-notes"
    },
    "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_7-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_7-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 11.7 Release Notes",
      "type": "topic",
      "url": "/documentation/xcode-release-notes/xcode-11_7-release-notes"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/NetworkExtension"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfigurationError": {
      "abstract": [
        {
          "text": "Error values returned by hotspot configuration manager methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfigurationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEHotspotConfigurationError",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEHotspotConfigurationError"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITabBarController": {
      "abstract": [
        {
          "text": "A container view controller that manages a multiselection interface, where the selection determines which child view controller to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITabBarController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITabBarController",
      "type": "topic",
      "url": "/documentation/UIKit/UITabBarController"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITableViewCell": {
      "abstract": [
        {
          "text": "The visual representation of a single row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewCell"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITableViewCell",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITableViewCell",
      "type": "topic",
      "url": "/documentation/UIKit/UITableViewCell"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIViewController/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a view controller with data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/init(coder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController/init(coder:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Xcode-11",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_7-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_6-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_5-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_4_1-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_4-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_3_1-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_3-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_2_1-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11_2-release-notes",
        "doc://com.apple.Xcode-Release-Notes/documentation/Xcode-Release-Notes/xcode-11-release-notes"
      ],
      "title": "Xcode 11"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCoder",
              "text": "NSCoder"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "coder"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEHotspotConfigurationError/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationError"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITableViewCell/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITableViewCell"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITabBarController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITabBarController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
