{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"count","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"itemCount","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"itemCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The badge count."}]}]}],"kind":"parameters"}],"metadata":{"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"macOS"}],"roleHeading":"Initializer","title":"init(count:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"count","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"modules":[{"name":"AppKit"}],"symbolKind":"init","externalID":"c:objc(cs)NSMenuItemBadge(im)initWithCount:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCount:"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge"]]},"abstract":[{"type":"text","text":"Creates a badge with a count and an empty string."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/init(string:)"],"generated":true,"anchor":"Creating-menu-item-badges","title":"Creating menu item badges"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["/documentation/appkit/nsmenuitembadge/init(count:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsmenuitembadge/init(count:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/init(count:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/init(count:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(count:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a badge with a count and an empty string."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/init(count:)","url":"/documentation/appkit/nsmenuitembadge/init(count:)","navigatorTitle":[{"kind":"identifier","text":"initWithCount:"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/init(string:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"string"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(string:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a badge with the provided custom string."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/init(string:)","url":"/documentation/appkit/nsmenuitembadge/init(string:)","navigatorTitle":[{"text":"initWithString:","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge","title":"NSMenuItemBadge","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSMenuItemBadge","kind":"identifier"}],"abstract":[{"type":"text","text":"A control that provides additional quantitative information specific to a menu item, such as the number of available updates."}],"kind":"symbol","navigatorTitle":[{"text":"NSMenuItemBadge","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsmenuitembadge"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/initWithCount:type:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCount:type:"}],"title":"initWithCount:type:","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/initWithCount:type:","url":"/documentation/appkit/nsmenuitembadge/initwithcount:type:","navigatorTitle":[{"kind":"identifier","text":"initWithCount:type:"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"initWithCount:","op":"replace"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCount:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/initWithCount:type:","doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/init(string:)"],"title":"Creating menu item badges","generated":true,"anchor":"Creating-menu-item-badges"}],"op":"replace","path":"/seeAlsoSections"},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCount:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"itemCount"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"itemCount","content":[{"type":"paragraph","inlineContent":[{"text":"The badge count.","type":"text"}]}]}]},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1init(count:)/title","value":"initWithCount:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1init(count:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCount:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1init(string:)/title","value":"initWithString:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1init(string:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithString:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/title","value":"NSMenuItemBadge"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/fragments","value":[{"text":"NSMenuItemBadge","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/navigatorTitle","value":[{"text":"NSMenuItemBadge","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}