{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/itemCount"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge"]]},"sections":[],"seeAlsoSections":[{"anchor":"Accessing-menu-item-badge-attributes","title":"Accessing menu item badge attributes","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/stringValue-fc9f","doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/type"],"generated":true}],"metadata":{"modules":[{"name":"AppKit"}],"symbolKind":"property","title":"itemCount","externalID":"c:objc(cs)NSMenuItemBadge(py)itemCount","navigatorTitle":[{"text":"itemCount","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"14.0"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The number of items the badge displays."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If you create a badge with a custom string, this value is ","type":"text"},{"code":"0","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"paths":["/documentation/appkit/nsmenuitembadge/itemcount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsmenuitembadge/itemcount"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/itemCount":{"abstract":[{"text":"The number of items the badge displays.","type":"text"}],"url":"/documentation/appkit/nsmenuitembadge/itemcount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/itemCount","title":"itemCount","navigatorTitle":[{"kind":"identifier","text":"itemCount"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/type":{"abstract":[{"text":"The type of items the badge displays.","type":"text"}],"url":"/documentation/appkit/nsmenuitembadge/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSMenuItemBadge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMenuItemBadge"},{"text":".","kind":"text"},{"text":"BadgeType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSMenuItemBadgeType"}],"kind":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/type","role":"symbol","type":"topic","title":"type"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge","title":"NSMenuItemBadge","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSMenuItemBadge","kind":"identifier"}],"abstract":[{"type":"text","text":"A control that provides additional quantitative information specific to a menu item, such as the number of available updates."}],"kind":"symbol","navigatorTitle":[{"text":"NSMenuItemBadge","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsmenuitembadge"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/stringValue-fc9f":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/stringValue-fc9f","url":"/documentation/appkit/nsmenuitembadge/stringvalue-fc9f","navigatorTitle":[{"text":"stringValue","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stringValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","title":"stringValue","role":"symbol","abstract":[{"type":"text","text":"The string representation of the badge when it displays."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"14.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"itemCount","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"itemCount","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Accessing menu item badge attributes","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/stringValue-fc9f","doc://com.apple.appkit/documentation/AppKit/NSMenuItemBadge/type"],"generated":true,"anchor":"Accessing-menu-item-badge-attributes"}],"op":"replace","path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"itemCount","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1itemCount/title","value":"itemCount","op":"replace"},{"op":"replace","value":[{"text":"itemCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1itemCount/fragments"},{"op":"replace","value":"type","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1type/title"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1type/fragments"},{"op":"replace","value":"NSMenuItemBadge","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/title"},{"op":"replace","value":[{"text":"NSMenuItemBadge","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/fragments"},{"op":"replace","value":[{"text":"NSMenuItemBadge","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge/navigatorTitle"},{"op":"replace","value":"stringValue","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1stringValue-fc9f/title"},{"op":"replace","value":[{"text":"stringValue","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemBadge~1stringValue-fc9f/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}