{"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:item:willAnimateDropWith:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:concludeDrop:)"],"title":"Animating the drop","generated":true,"anchor":"Animating-the-drop"}],"abstract":[{"text":"Asks the delegate for the targeted drag item preview to show during the drop animation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIDropInteraction","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction"},{"text":", ","kind":"text"},{"text":"previewForDropping","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIDragItem","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragItem","preciseIdentifier":"c:objc(cs)UIDragItem"},{"text":", ","kind":"text"},{"text":"withDefault","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"defaultPreview","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UITargetedDragPreview","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview","preciseIdentifier":"c:objc(cs)UITargetedDragPreview"},{"text":") -> ","kind":"text"},{"text":"UITargetedDragPreview","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview","preciseIdentifier":"c:objc(cs)UITargetedDragPreview"},{"text":"?","kind":"text"}]}]},{"parameters":[{"name":"interaction","content":[{"type":"paragraph","inlineContent":[{"text":"The interaction that called this method.","type":"text"}]}]},{"name":"item","content":[{"inlineContent":[{"text":"The drag item represented by the preview.","type":"text"}],"type":"paragraph"}]},{"name":"defaultPreview","content":[{"type":"paragraph","inlineContent":[{"text":"A targeted drag preview provided by the system, if this is the first call for this item; otherwise, it’s the previous value for the drag preview.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"The default preview, which is the same behavior as not implementing this method."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A targeted drag item preview that you create."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The preview returned after moving to a new preview target by using the "},{"code":"defaultPreview","type":"codeVoice"},{"type":"text","text":"’s "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview/retargetedPreview(with:)","isActive":true},{"type":"text","text":" method."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"nil"},{"type":"text","text":" to fade the preview that is currently displayed to the user."}],"type":"paragraph"}]}]}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The system calls this method multiple times, once for each visible drag item. It shows the preview during the drop animation in order to visually "},{"type":"emphasis","inlineContent":[{"type":"text","text":"drop"}]},{"type":"text","text":" the drag item into place."}],"type":"paragraph"},{"inlineContent":[{"text":"If you call ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragItem/setNeedsDropPreviewUpdate()","isActive":true,"type":"reference"},{"text":" to tell the system to request a new drop preview, the system provides the previous value in the ","type":"text"},{"code":"defaultPreview","type":"codeVoice"},{"text":" parameter.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:previewForDropping:withDefault:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewForDropping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDragItem","text":"UIDragItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITargetedDragPreview","text":"UITargetedDragPreview"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITargetedDragPreview","text":"UITargetedDragPreview"},{"kind":"text","text":"?"}],"title":"dropInteraction(_:previewForDropping:withDefault:)","modules":[{"name":"UIKit"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","platforms":[{"deprecated":false,"introducedAt":"11.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"11.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false}],"navigatorTitle":[{"kind":"identifier","text":"dropInteraction:previewForDroppingItem:withDefault:"}],"externalID":"c:objc(pl)UIDropInteractionDelegate(im)dropInteraction:previewForDroppingItem:withDefault:"},"sections":[],"variants":[{"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:previewfordropping:withdefault:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:previewfordropping:withdefault:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate":{"type":"topic","kind":"symbol","title":"UIDropInteractionDelegate","role":"symbol","navigatorTitle":[{"text":"UIDropInteractionDelegate","kind":"identifier"}],"url":"/documentation/uikit/uidropinteractiondelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteractionDelegate","kind":"identifier"}],"abstract":[{"text":"The interface for configuring and controlling a drop interaction.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"},"doc://com.apple.uikit/documentation/UIKit/UIDragItem/setNeedsDropPreviewUpdate()":{"url":"/documentation/uikit/uidragitem/setneedsdroppreviewupdate()","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragItem/setNeedsDropPreviewUpdate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNeedsDropPreviewUpdate"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"setNeedsDropPreviewUpdate"}],"abstract":[{"type":"text","text":"Notifies the operating system that an updated drop preview is available for the item."}],"kind":"symbol","type":"topic","title":"setNeedsDropPreviewUpdate()"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction":{"navigatorTitle":[{"text":"UIDropInteraction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An interaction to enable dropping of items onto a view, employing a delegate to instantiate objects and respond to calls from the drop session.","type":"text"}],"url":"/documentation/uikit/uidropinteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","title":"UIDropInteraction","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteraction","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:previewForDropping:withDefault:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:previewfordropping:withdefault:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:previewForDropping:withDefault:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewForDropping"},{"text":": ","kind":"text"},{"text":"UIDragItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDragItem"},{"text":", ","kind":"text"},{"text":"withDefault","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITargetedDragPreview","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITargetedDragPreview"},{"text":") -> ","kind":"text"},{"text":"UITargetedDragPreview","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITargetedDragPreview"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dropInteraction:previewForDroppingItem:withDefault:","kind":"identifier"}],"abstract":[{"type":"text","text":"Asks the delegate for the targeted drag item preview to show during the drop animation."}],"kind":"symbol","type":"topic","title":"dropInteraction(_:previewForDropping:withDefault:)"},"doc://com.apple.uikit/documentation/UIKit/UIDragItem":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIDragItem"}],"url":"/documentation/uikit/uidragitem","title":"UIDragItem","navigatorTitle":[{"kind":"identifier","text":"UIDragItem"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragItem","abstract":[{"type":"text","text":"A representation of an underlying data item as a person drags it from one location to another."}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview":{"title":"UITargetedDragPreview","abstract":[{"type":"text","text":"A drag item preview used by the system during lift, drop, or cancellation animation."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview","type":"topic","role":"symbol","url":"/documentation/uikit/uitargeteddragpreview","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITargetedDragPreview"}],"navigatorTitle":[{"kind":"identifier","text":"UITargetedDragPreview"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:item:willAnimateDropWith:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"item","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDragItem","text":"UIDragItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willAnimateDropWith","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDragAnimating","text":"UIDragAnimating","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"dropInteraction(_:item:willAnimateDropWith:)","abstract":[{"text":"Tells the delegate the system’s drop animation is about to start.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:item:willAnimateDropWith:)","type":"topic","url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:item:willanimatedropwith:)","navigatorTitle":[{"text":"dropInteraction:item:willAnimateDropWithAnimator:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:concludeDrop:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"concludeDrop","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"dropInteraction(_:concludeDrop:)","abstract":[{"text":"Tells the delegate the drop activity and its related animations have finished.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:concludeDrop:)","type":"topic","url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:concludedrop:)","navigatorTitle":[{"text":"dropInteraction:concludeDrop:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview/retargetedPreview(with:)":{"title":"retargetedPreview(with:)","url":"/documentation/uikit/uitargeteddragpreview/retargetedpreview(with:)","type":"topic","navigatorTitle":[{"text":"retargetedPreviewWithTarget:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a new targeted drag item preview based on an existing one, but with a new geometric target."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retargetedPreview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIDragPreviewTarget","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDragPreviewTarget"},{"text":") -> ","kind":"text"},{"text":"UITargetedDragPreview","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITargetedDragPreview"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview/retargetedPreview(with:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"dropInteraction:previewForDroppingItem:withDefault:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:previewForDroppingItem:withDefault:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Animating the drop","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:item:willAnimateDropWith:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:concludeDrop:)"],"anchor":"Animating-the-drop","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UITargetedDragPreview","preciseIdentifier":"c:objc(cs)UITargetedDragPreview","identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"dropInteraction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewForDroppingItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDragItem","preciseIdentifier":"c:objc(cs)UIDragItem","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragItem"},{"text":" *) ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withDefault:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITargetedDragPreview","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview","preciseIdentifier":"c:objc(cs)UITargetedDragPreview"},{"text":" *) ","kind":"text"},{"text":"defaultPreview","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The interaction that called this method.","type":"text"}],"type":"paragraph"}],"name":"interaction"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The drag item represented by the preview.","type":"text"}]}],"name":"item"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A targeted drag preview provided by the system, if this is the first call for this item; otherwise, it’s the previous value for the drag preview."}]}],"name":"defaultPreview"}],"kind":"parameters"}},{"path":"/primaryContentSections/2","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":""}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The default preview, which is the same behavior as not implementing this method."}]}]},{"content":[{"inlineContent":[{"text":"A targeted drag item preview that you create.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The preview returned after moving to a new preview target by using the ","type":"text"},{"code":"defaultPreview","type":"codeVoice"},{"text":"’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITargetedDragPreview/retargetedPreview(with:)","type":"reference"},{"text":" method.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"nil","type":"codeVoice"},{"text":" to fade the preview that is currently displayed to the user.","type":"text"}]}]}]}],"kind":"content"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/title","value":"UIDropInteractionDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/fragments","value":[{"kind":"identifier","text":"UIDropInteractionDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/navigatorTitle","value":[{"text":"UIDropInteractionDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem~1setNeedsDropPreviewUpdate()/title","value":"setNeedsDropPreviewUpdate"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem~1setNeedsDropPreviewUpdate()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNeedsDropPreviewUpdate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/title","value":"UIDropInteraction"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/fragments","value":[{"text":"UIDropInteraction","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/navigatorTitle","value":[{"kind":"identifier","text":"UIDropInteraction"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:previewForDropping:withDefault:)/title","value":"dropInteraction:previewForDroppingItem:withDefault:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:previewForDropping:withDefault:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:previewForDroppingItem:withDefault:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/title","value":"UIDragItem"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/fragments","value":[{"kind":"identifier","text":"UIDragItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem/navigatorTitle","value":[{"kind":"identifier","text":"UIDragItem"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview/title","value":"UITargetedDragPreview"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview/fragments","value":[{"kind":"identifier","text":"UITargetedDragPreview"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview/navigatorTitle","value":[{"kind":"identifier","text":"UITargetedDragPreview"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:item:willAnimateDropWith:)/title","value":"dropInteraction:item:willAnimateDropWithAnimator:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:item:willAnimateDropWith:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:item:willAnimateDropWithAnimator:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:concludeDrop:)/title","value":"dropInteraction:concludeDrop:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:concludeDrop:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:concludeDrop:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview~1retargetedPreview(with:)/title","value":"retargetedPreviewWithTarget:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedDragPreview~1retargetedPreview(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"retargetedPreviewWithTarget:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}