{"sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnd:"}],"externalID":"c:objc(pl)UIDropInteractionDelegate(im)dropInteraction:sessionDidEnd:","modules":[{"name":"UIKit"}],"role":"symbol","roleHeading":"Instance Method","platforms":[{"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"11.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false}],"title":"dropInteraction(_:sessionDidEnd:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnd"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidend:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidend:)"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)"],"anchor":"Tracking-the-drop-movements","generated":true,"title":"Tracking the drop movements"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","text":"UIDropInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction"},{"text":", ","kind":"text"},{"text":"sessionDidEnd","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","text":"UIDropSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The interaction that called this method.","type":"text"}],"type":"paragraph"}],"name":"interaction"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The drop session that ended.","type":"text"}]}],"name":"session"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"Implement this method if you need to clean up resources you created during the session."}],"type":"paragraph"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate the drop session has ended."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction":{"navigatorTitle":[{"text":"UIDropInteraction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An interaction to enable dropping of items onto a view, employing a delegate to instantiate objects and respond to calls from the drop session.","type":"text"}],"url":"/documentation/uikit/uidropinteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","title":"UIDropInteraction","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteraction","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropSession":{"abstract":[{"type":"text","text":"The interface for querying a drop session about its state and associated drag items."}],"url":"/documentation/uikit/uidropsession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","title":"UIDropSession","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIDropSession","kind":"identifier"}],"navigatorTitle":[{"text":"UIDropSession","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidenter:)","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnter:"}],"role":"symbol","abstract":[{"text":"Tells the delegate the drop session has moved into the drop interaction’s view.","type":"text"}],"type":"topic","title":"dropInteraction(_:sessionDidEnter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnter"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"dropInteraction:sessionDidUpdate:","kind":"identifier"}],"title":"dropInteraction(_:sessionDidUpdate:)","url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidupdate:)","abstract":[{"type":"text","text":"Tells the delegate the drop session has changed."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sessionDidUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropProposal","text":"UIDropProposal","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidend:)","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnd:"}],"role":"symbol","abstract":[{"text":"Tells the delegate the drop session has ended.","type":"text"}],"type":"topic","title":"dropInteraction(_:sessionDidEnd:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnd"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate":{"type":"topic","kind":"symbol","title":"UIDropInteractionDelegate","role":"symbol","navigatorTitle":[{"text":"UIDropInteractionDelegate","kind":"identifier"}],"url":"/documentation/uikit/uidropinteractiondelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteractionDelegate","kind":"identifier"}],"abstract":[{"text":"The interface for configuring and controlling a drop interaction.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidexit:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidExit:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)","type":"topic","kind":"symbol","abstract":[{"text":"Tells the delegate the drop session has moved out of the drop interaction’s view.","type":"text"}],"title":"dropInteraction(_:sessionDidExit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidExit"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"11.0","beta":false},{"name":"iPadOS","beta":false,"introducedAt":"11.0","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"dropInteraction:sessionDidEnd:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidEnd:","kind":"identifier"}],"path":"/metadata/fragments"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)"],"title":"Tracking the drop movements","anchor":"Tracking-the-drop-movements"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dropInteraction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDropInteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidEnd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIDropSession>","preciseIdentifier":"c:Qoobjc(pl)UIDropSession"},{"kind":"text","text":") "},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"name":"interaction","content":[{"inlineContent":[{"type":"text","text":"The interaction that called this method."}],"type":"paragraph"}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The drop session that ended."}]}]}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/title","op":"replace","value":"UIDropInteraction"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/fragments","op":"replace","value":[{"kind":"identifier","text":"UIDropInteraction"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/navigatorTitle","op":"replace","value":[{"text":"UIDropInteraction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title","op":"replace","value":"UIDropSession"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments","op":"replace","value":[{"text":"UIDropSession","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle","op":"replace","value":[{"text":"UIDropSession","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/title","op":"replace","value":"dropInteraction:sessionDidEnter:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidEnter:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/title","op":"replace","value":"dropInteraction:sessionDidUpdate:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidUpdate:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnd:)/title","value":"dropInteraction:sessionDidEnd:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnd:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidEnd:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/title","value":"UIDropInteractionDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/fragments","value":[{"kind":"identifier","text":"UIDropInteractionDelegate"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/navigatorTitle","value":[{"text":"UIDropInteractionDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidExit:)/title","value":"dropInteraction:sessionDidExit:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidExit:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:sessionDidExit:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}