{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","interfaceLanguage":"swift"},"abstract":[{"text":"Tells the delegate the drop session has moved into the drop interaction’s view.","type":"text"}],"metadata":{"modules":[{"name":"UIKit"}],"title":"dropInteraction(_:sessionDidEnter:)","externalID":"c:objc(pl)UIDropInteractionDelegate(im)dropInteraction:sessionDidEnter:","symbolKind":"method","platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"11.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"11.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIDropInteraction","kind":"typeIdentifier","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnter"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnter:"}],"roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction"},{"text":", ","kind":"text"},{"text":"sessionDidEnter","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"interaction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The interaction that called this method."}]}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"text":"The drop session that has moved into the interaction’s view.","type":"text"}]}]}],"kind":"parameters"},{"mentions":["doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination"],"kind":"mentions"}],"sections":[],"kind":"symbol","variants":[{"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidenter:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidenter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)"],"generated":true,"anchor":"Tracking-the-drop-movements","title":"Tracking the drop movements"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate":{"type":"topic","kind":"symbol","title":"UIDropInteractionDelegate","role":"symbol","navigatorTitle":[{"text":"UIDropInteractionDelegate","kind":"identifier"}],"url":"/documentation/uikit/uidropinteractiondelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteractionDelegate","kind":"identifier"}],"abstract":[{"text":"The interface for configuring and controlling a drop interaction.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"},"doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination":{"role":"article","title":"Making a view into a drop destination","url":"/documentation/uikit/making-a-view-into-a-drop-destination","identifier":"doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination","type":"topic","kind":"article","abstract":[{"text":"Adopt drop interaction APIs to selectively consume dragged content.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidexit:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidExit:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)","type":"topic","kind":"symbol","abstract":[{"text":"Tells the delegate the drop session has moved out of the drop interaction’s view.","type":"text"}],"title":"dropInteraction(_:sessionDidExit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidExit"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidend:)","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnd:"}],"role":"symbol","abstract":[{"text":"Tells the delegate the drop session has ended.","type":"text"}],"type":"topic","title":"dropInteraction(_:sessionDidEnd:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnd"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"dropInteraction:sessionDidUpdate:","kind":"identifier"}],"title":"dropInteraction(_:sessionDidUpdate:)","url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidupdate:)","abstract":[{"type":"text","text":"Tells the delegate the drop session has changed."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sessionDidUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropProposal","text":"UIDropProposal","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction":{"navigatorTitle":[{"text":"UIDropInteraction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An interaction to enable dropping of items onto a view, employing a delegate to instantiate objects and respond to calls from the drop session.","type":"text"}],"url":"/documentation/uikit/uidropinteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","title":"UIDropInteraction","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteraction","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidenter:)","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnter:"}],"role":"symbol","abstract":[{"text":"Tells the delegate the drop session has moved into the drop interaction’s view.","type":"text"}],"type":"topic","title":"dropInteraction(_:sessionDidEnter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnter"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropSession":{"abstract":[{"type":"text","text":"The interface for querying a drop session about its state and associated drag items."}],"url":"/documentation/uikit/uidropsession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","title":"UIDropSession","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIDropSession","kind":"identifier"}],"navigatorTitle":[{"text":"UIDropSession","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"11.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"11.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"op":"replace","value":"dropInteraction:sessionDidEnter:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:sessionDidEnter:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)"],"anchor":"Tracking-the-drop-movements","generated":true,"title":"Tracking the drop movements"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dropInteraction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidEnter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIDropSession>","preciseIdentifier":"c:Qoobjc(pl)UIDropSession"},{"kind":"text","text":") "},{"kind":"internalParam","text":"session"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"interaction","content":[{"type":"paragraph","inlineContent":[{"text":"The interaction that called this method.","type":"text"}]}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The drop session that has moved into the interaction’s view."}]}]}]},"op":"replace"},{"op":"replace","value":"UIDropInteractionDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/title"},{"op":"replace","value":[{"text":"UIDropInteractionDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropInteractionDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/navigatorTitle"},{"op":"replace","value":"dropInteraction:sessionDidExit:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidExit:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:sessionDidExit:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidExit:)/fragments"},{"op":"replace","value":"dropInteraction:sessionDidEnd:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnd:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidEnd:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnd:)/fragments"},{"op":"replace","value":"dropInteraction:sessionDidUpdate:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:sessionDidUpdate:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/fragments"},{"op":"replace","value":"UIDropInteraction","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropInteraction"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/fragments"},{"op":"replace","value":[{"text":"UIDropInteraction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/navigatorTitle"},{"op":"replace","value":"dropInteraction:sessionDidEnter:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidEnter:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/fragments"},{"op":"replace","value":"UIDropSession","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropSession"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments"},{"op":"replace","value":[{"text":"UIDropSession","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}