{"seeAlsoSections":[{"generated":true,"title":"Tracking the drop movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)"],"anchor":"Tracking-the-drop-movements"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]},"sections":[],"variants":[{"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidupdate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidupdate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Tells the delegate the drop session has changed."}],"metadata":{"platforms":[{"beta":false,"introducedAt":"11.0","unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"introducedAt":"11.0","unavailable":false,"name":"iPadOS","deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","title":"dropInteraction(_:sessionDidUpdate:)","navigatorTitle":[{"text":"dropInteraction:sessionDidUpdate:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"UIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDropInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction"},{"text":", ","kind":"text"},{"text":"sessionDidUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIDropSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession"},{"text":") -> ","kind":"text"},{"text":"UIDropProposal","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropProposal"}],"symbolKind":"method","externalID":"c:objc(pl)UIDropInteractionDelegate(im)dropInteraction:sessionDidUpdate:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidUpdate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","text":"UIDropSession"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropProposal","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropProposal","text":"UIDropProposal"}],"languages":["swift"]}]},{"parameters":[{"name":"interaction","content":[{"inlineContent":[{"type":"text","text":"The interaction that called this method."}],"type":"paragraph"}]},{"name":"session","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The drop session that has changed."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"A drop proposal that contains the operation the delegate intends to perform. You may return a proposal containing the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move","type":"reference","isActive":true},{"text":" operation only if the session’s ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragDropSession/allowsMoveOperation","type":"reference","isActive":true},{"text":" is ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"text":".","type":"text"}]}],"kind":"content"},{"mentions":["doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination"],"kind":"mentions"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"You must implement this method if the drop interaction’s view can accept drop activities. If you don’t provide this method, the view cannot accept any drop activities.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The interaction calls this method when one of the following happens:"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The session enters the area of the drop interaction’s view."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The session moves inside the area of the drop interaction’s view.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The user adds a drag item to the session that within the area of the drop interaction’s view.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To get the location of the drop session after it has moved, call the session’s "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragDropSession/location(in:)","isActive":true},{"type":"text","text":" method."}]}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination":{"role":"article","title":"Making a view into a drop destination","url":"/documentation/uikit/making-a-view-into-a-drop-destination","identifier":"doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination","type":"topic","kind":"article","abstract":[{"text":"Adopt drop interaction APIs to selectively consume dragged content.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDragDropSession/location(in:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the geometrical location of the user’s drag activity within the specified view."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"role":"symbol","url":"/documentation/uikit/uidragdropsession/location(in:)","title":"location(in:)","kind":"symbol","required":true,"navigatorTitle":[{"text":"locationInView:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragDropSession/location(in:)"},"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move":{"url":"/documentation/uikit/uidropoperation/move","role":"symbol","title":"UIDropOperation.move","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move","navigatorTitle":[{"text":"UIDropOperationMove","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"move","kind":"identifier"}],"abstract":[{"text":"A drop operation type specifying that the data represented by the drag items should be moved, not copied.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropProposal":{"navigatorTitle":[{"text":"UIDropProposal","kind":"identifier"}],"title":"UIDropProposal","url":"/documentation/uikit/uidropproposal","abstract":[{"type":"text","text":"A configuration for the behavior of a drop interaction, required if a view accepts drop activities."}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropProposal","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropProposal"},"doc://com.apple.uikit/documentation/UIKit/UIDropSession":{"abstract":[{"type":"text","text":"The interface for querying a drop session about its state and associated drag items."}],"url":"/documentation/uikit/uidropsession","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropSession","title":"UIDropSession","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIDropSession","kind":"identifier"}],"navigatorTitle":[{"text":"UIDropSession","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate":{"type":"topic","kind":"symbol","title":"UIDropInteractionDelegate","role":"symbol","navigatorTitle":[{"text":"UIDropInteractionDelegate","kind":"identifier"}],"url":"/documentation/uikit/uidropinteractiondelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteractionDelegate","kind":"identifier"}],"abstract":[{"text":"The interface for configuring and controlling a drop interaction.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidexit:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidExit:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)","type":"topic","kind":"symbol","abstract":[{"text":"Tells the delegate the drop session has moved out of the drop interaction’s view.","type":"text"}],"title":"dropInteraction(_:sessionDidExit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidExit"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidend:)","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnd:"}],"role":"symbol","abstract":[{"text":"Tells the delegate the drop session has ended.","type":"text"}],"type":"topic","title":"dropInteraction(_:sessionDidEnd:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnd"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction":{"navigatorTitle":[{"text":"UIDropInteraction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An interaction to enable dropping of items onto a view, employing a delegate to instantiate objects and respond to calls from the drop session.","type":"text"}],"url":"/documentation/uikit/uidropinteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction","title":"UIDropInteraction","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDropInteraction","kind":"identifier"}]},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)":{"url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidenter:)","navigatorTitle":[{"kind":"identifier","text":"dropInteraction:sessionDidEnter:"}],"role":"symbol","abstract":[{"text":"Tells the delegate the drop session has moved into the drop interaction’s view.","type":"text"}],"type":"topic","title":"dropInteraction(_:sessionDidEnter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionDidEnter"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UIDropSession","kind":"typeIdentifier","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"dropInteraction:sessionDidUpdate:","kind":"identifier"}],"title":"dropInteraction(_:sessionDidUpdate:)","url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidupdate:)","abstract":[{"type":"text","text":"Tells the delegate the drop session has changed."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sessionDidUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDropProposal","text":"UIDropProposal","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDragDropSession/allowsMoveOperation":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsMoveOperation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/uikit/uidragdropsession/allowsmoveoperation","required":true,"role":"symbol","title":"allowsMoveOperation","navigatorTitle":[{"text":"allowsMoveOperation","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether the drag session permits moving drag items within the same app.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragDropSession/allowsMoveOperation","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"11.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"dropInteraction:sessionDidUpdate:"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:sessionDidUpdate:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidExit:)","doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnd:)"],"title":"Tracking the drop movements","anchor":"Tracking-the-drop-movements"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropProposal","text":"UIDropProposal","preciseIdentifier":"c:objc(cs)UIDropProposal"},{"kind":"text","text":" *) "},{"text":"dropInteraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteraction"},{"text":" *) ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sessionDidUpdate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIDropSession","text":"id<UIDropSession>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The interaction that called this method."}],"type":"paragraph"}],"name":"interaction"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The drop session that has changed.","type":"text"}]}],"name":"session"}]},"path":"/primaryContentSections/1"},{"op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"A drop proposal that contains the operation the delegate intends to perform. You may return a proposal containing the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move"},{"text":" operation only if the session’s ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDragDropSession/allowsMoveOperation"},{"text":" is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":".","type":"text"}],"type":"paragraph"}]},"path":"/primaryContentSections/2"},{"op":"replace","value":"locationInView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragDropSession~1location(in:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationInView:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragDropSession~1location(in:)/fragments"},{"op":"replace","value":"UIDropOperationMove","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1move/title"},{"op":"replace","value":[{"text":"UIDropOperationMove","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1move/fragments"},{"op":"replace","value":"UIDropProposal","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropProposal"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropProposal"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/navigatorTitle"},{"op":"replace","value":"UIDropSession","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropSession"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments"},{"op":"replace","value":[{"text":"UIDropSession","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle"},{"op":"replace","value":"UIDropInteractionDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/title"},{"op":"replace","value":[{"text":"UIDropInteractionDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIDropInteractionDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/navigatorTitle"},{"op":"replace","value":"dropInteraction:sessionDidExit:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidExit:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:sessionDidExit:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidExit:)/fragments"},{"op":"replace","value":"dropInteraction:sessionDidEnd:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnd:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:sessionDidEnd:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnd:)/fragments"},{"op":"replace","value":"UIDropInteraction","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/title"},{"op":"replace","value":[{"text":"UIDropInteraction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/fragments"},{"op":"replace","value":[{"text":"UIDropInteraction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/navigatorTitle"},{"op":"replace","value":"dropInteraction:sessionDidEnter:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidEnter:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/fragments"},{"op":"replace","value":"dropInteraction:sessionDidUpdate:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dropInteraction:sessionDidUpdate:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/fragments"},{"op":"replace","value":"allowsMoveOperation","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragDropSession~1allowsMoveOperation/title"},{"op":"replace","value":[{"text":"allowsMoveOperation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragDropSession~1allowsMoveOperation/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}