{
  "abstract": [
    {
      "text": "Tells the delegate it can request the item provider data from the session’s drag items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIDropInteractionDelegate(im)dropInteraction:performDrop:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dropInteraction"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIDropInteraction",
        "text": "UIDropInteraction"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "performDrop"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UIDropSession",
        "text": "UIDropSession"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dropInteraction:performDrop:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "dropInteraction(_:performDrop:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "interaction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteraction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIDropInteraction",
              "text": "UIDropInteraction"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "performDrop"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIDropSession",
              "text": "UIDropSession"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The interaction that called this method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "interaction"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The session containing the drag items.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can request a drag item’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem/itemProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " data within the scope of this method only and not at any other time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To request the data, iterate over the session items calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888336-loadobject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on each item’s item provider. For example, if you are expecting the drag items to be images, here’s how you can load each image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func dropInteraction(_ interaction: UIDropInteraction, performDrop session: UIDropSession) {",
            "    for item in session.items {",
            "        let itemProvider = item.itemProvider",
            "        guard itemProvider.canLoadObject(ofClass: UIImage.self) ",
            "        else {continue}",
            "",
            "        itemProvider.loadObject(ofClass: UIImage.self, completionHandler: { (object, error) in",
            "            if let image = object as? UIImage {",
            "                DispatchQueue.main.async {",
            "                    self.imageView.image = image",
            "                }",
            "            }",
            "        })",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you need to be more specific about the type of data to load, use one of the following methods to specify the desired data type using its uniform type identifier (UTI):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888331-loaddatarepresentation",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888338-loadfilerepresentation",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888335-loadinplacefilerepresentation",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you want only JPEG images, use the UTI for the JPEG image type:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import MobileCoreServices // for kUTTypeJPEG",
            "func dropInteraction(_ interaction: UIDropInteraction, performDrop session: UIDropSession) {",
            "    for item in session.items {",
            "        let itemProvider = item.itemProvider",
            "        itemProvider.loadDataRepresentation(forTypeIdentifier: kUTTypeJPEG as String, completionHandler: { (data, error) in",
            "            guard",
            "                let data = data,",
            "                let image = UIImage(data: data)",
            "                else {return}",
            "            ",
            "            DispatchQueue.main.async {",
            "                self.imageView.image = image",
            "            }        ",
            "        })",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use the session’s convenience method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to load the data for an item. Note that the completion handler for this method is called on the main thread, which is not true when loading the data from the item provider.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func dropInteraction(_ interaction: UIDropInteraction, performDrop session: UIDropSession) {",
            "    session.loadObjects(ofClass: UIImage.self) { objects in",
            "        guard let images = objects as? [UIImage] else {return}",
            "        for image in images {",
            "            self.imageView.image = image",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When you ask the session or item provider to load its data, it gives you a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/progress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. You can also get the progress for the session at a later time from its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/progressreporting/1412781-progress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/progress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object tells you how much of the data transfer is complete and if the transfer has finished. What’s more, it can be used to cancel, pause, and resume the data-load process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888331-loaddatarepresentation": {
      "abstract": [
        {
          "text": "Asynchronously copies the provided, typed data into a generic data object, returning a progress object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "loadDataRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "forTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": String, "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (Data?, (any Error)?) -> Void) -> Progress"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888331-loaddatarepresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadDataRepresentation(forTypeIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider/2888331-loaddatarepresentation"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888335-loadinplacefilerepresentation": {
      "abstract": [
        {
          "text": "Asynchronously opens a file in place, if possible, returning a progress object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "loadInPlaceFileRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "forTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": String, "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (URL?, Bool, (any Error)?) -> Void) -> Progress"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888335-loadinplacefilerepresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadInPlaceFileRepresentation(forTypeIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider/2888335-loadinplacefilerepresentation"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888336-loadobject": {
      "abstract": [
        {
          "text": "Asynchronously loads an object of a specified class to an item provider, returning a progress object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "loadObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "ofClass"
        },
        {
          "kind": "text",
          "text": ": any NSItemProviderReading.Type, "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any NSItemProviderReading)?, (any Error)?) -> Void) -> Progress"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888336-loadobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadObject(ofClass:completionHandler:)",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider/2888336-loadobject"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888338-loadfilerepresentation": {
      "abstract": [
        {
          "text": "Asynchronously writes a copy of the provided, typed data to a temporary file, returning a progress object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "loadFileRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "forTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": String, "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (URL?, (any Error)?) -> Void) -> Progress"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888338-loadfilerepresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadFileRepresentation(forTypeIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider/2888338-loadfilerepresentation"
    },
    "doc://com.apple.documentation/documentation/foundation/progress": {
      "abstract": [
        {
          "text": "An object that conveys ongoing progress to the user for a specified task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/progress",
      "kind": "symbol",
      "role": "symbol",
      "title": "Progress",
      "type": "topic",
      "url": "/documentation/foundation/progress"
    },
    "doc://com.apple.documentation/documentation/foundation/progressreporting/1412781-progress": {
      "abstract": [
        {
          "text": "The progress object returned by the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "progress"
        },
        {
          "kind": "text",
          "text": ": Progress"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/progressreporting/1412781-progress",
      "kind": "symbol",
      "role": "symbol",
      "title": "progress",
      "type": "topic",
      "url": "/documentation/foundation/progressreporting/1412781-progress"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragItem/itemProvider": {
      "abstract": [
        {
          "text": "The item provider associated with the drag item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSItemProvider",
          "text": "NSItemProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragItem/itemProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemProvider"
        }
      ],
      "role": "symbol",
      "title": "itemProvider",
      "type": "topic",
      "url": "/documentation/uikit/uidragitem/itemprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteraction": {
      "abstract": [
        {
          "text": "An interaction to enable dropping of items onto a view, employing a delegate to instantiate objects and respond to calls from the drop session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIDropInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate": {
      "abstract": [
        {
          "text": "The interface for configuring and controlling a drop interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIDropInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether it can handle the session’s drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropInteraction",
          "text": "UIDropInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "canHandle"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropInteraction:canHandleSession:"
        }
      ],
      "role": "symbol",
      "title": "dropInteraction(_:canHandle:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:canhandle:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)": {
      "abstract": [
        {
          "text": "Tells the delegate it can request the item provider data from the session’s drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropInteraction",
          "text": "UIDropInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performDrop"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropInteraction:performDrop:"
        }
      ],
      "role": "symbol",
      "title": "dropInteraction(_:performDrop:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:performdrop:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession": {
      "abstract": [
        {
          "text": "The interface for querying a drop session about its state and associated drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropSession"
        }
      ],
      "role": "symbol",
      "title": "UIDropSession",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)": {
      "abstract": [
        {
          "text": "Creates and loads a new instance of the specified class for each drag item in the session.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadObjects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofClass"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSItemProviderReading",
          "text": "NSItemProviderReading"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ([any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSItemProviderReading",
          "text": "NSItemProviderReading"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadObjectsOfClass:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "loadObjects(ofClass:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession/loadobjects(ofclass:completion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination": {
      "abstract": [
        {
          "text": "Adopt drop interaction APIs to selectively consume dragged content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination",
      "kind": "article",
      "role": "article",
      "title": "Making a view into a drop destination",
      "type": "topic",
      "url": "/documentation/uikit/making-a-view-into-a-drop-destination"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-the-drop",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)"
      ],
      "title": "Handling the drop"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dropInteraction:performDrop:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:performDrop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-the-drop",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)"
              ],
              "title": "Handling the drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "dropInteraction:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteraction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIDropInteraction",
                    "text": "UIDropInteraction"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "interaction"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "performDrop:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)UIDropSession",
                    "text": "id<UIDropSession>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The interaction that called this method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "interaction"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The session containing the drag items.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "session"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/title",
          "value": "UIDropInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/title",
          "value": "loadObjectsOfClass:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadObjectsOfClass:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/title",
          "value": "dropInteraction:performDrop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:performDrop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title",
          "value": "UIDropSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsitemprovider~12888335-loadinplacefilerepresentation/title",
          "value": "loadInPlaceFileRepresentationForTypeIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsitemprovider~12888338-loadfilerepresentation/title",
          "value": "loadFileRepresentationForTypeIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem~1itemProvider/title",
          "value": "itemProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragItem~1itemProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/title",
          "value": "UIDropInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:canHandle:)/title",
          "value": "dropInteraction:canHandleSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:canHandle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:canHandleSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsitemprovider~12888336-loadobject/title",
          "value": "loadObjectOfClass:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsitemprovider~12888331-loaddatarepresentation/title",
          "value": "loadDataRepresentationForTypeIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1progress/title",
          "value": "NSProgress"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:performdrop:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:performdrop:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
