{
  "abstract": [
    {
      "text": "A parameter expresses a control or a set of controls that influence frame processing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "VideoToolbox",
    "externalID": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Parameter"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Parameter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VTRAWProcessingSession.Parameter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Parameter"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Parameters can represent Boolean options, integer or floating-point ranges, lists, or subgroups. All parameters have a collection of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Details",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " containing a localized name suitable for display in UI, a longer localized description string, and a Boolean that indicates whether it’s enabled. All details, except for subgroups, must have a “key” string used to uniquely identify that parameter. All parameters other than subgroups have a collection of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Values",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " containing a mandatory “initial” value, and optional “neutral” and “camera” values. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/IntegerParameter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/FloatParameter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " are required to have “minimum” and “maximum” values in their Values",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Parameter arrays are created and returned by the VideoToolbox framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter": {
      "abstract": [
        {
          "text": "A parameter expresses a control or a set of controls that influence frame processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Parameter"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Parameter"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/BooleanParameter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BooleanParameter"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/BooleanParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BooleanParameter"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.BooleanParameter",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/booleanparameter"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Details": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Details"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Details",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Details"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.Details",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/details"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/FloatParameter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FloatParameter"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/FloatParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FloatParameter"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.FloatParameter",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/floatparameter"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/IntegerParameter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IntegerParameter"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/IntegerParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IntegerParameter"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.IntegerParameter",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/integerparameter"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/ListParameter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ListParameter"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/ListParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ListParameter"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.ListParameter",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/listparameter"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Values": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Values"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Values",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Values"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.Values",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/values"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/bool(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bool"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO07BooleanF0V",
          "text": "BooleanParameter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/bool(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.bool(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/bool(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/float(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO05FloatF0V",
          "text": "FloatParameter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/float(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.float(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/float(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/int(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO07IntegerF0V",
          "text": "IntegerParameter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/int(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.int(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/int(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/list(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "list"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO04ListF0V",
          "text": "ListParameter"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/list(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.list(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/list(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/subgroup(details:elements:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subgroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "details"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO7DetailsV",
          "text": "Details"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "elements"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/subgroup(details:elements:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSession.Parameter.subgroup(details:elements:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameter/subgroup(details:elements:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/parameters()": {
      "abstract": [
        {
          "text": "Returns an asynchronous sequence that provides updates to the processing Parameter array if the processing extension makes changes to the set of Parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sci",
          "text": "AsyncSequence"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/parameters()",
      "kind": "symbol",
      "role": "symbol",
      "title": "parameters()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/parameters()"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/processingParameters": {
      "abstract": [
        {
          "text": "An array of processing parameters available for this RAW processing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processingParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
          "text": "VTRAWProcessingSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So25VTRAWProcessingSessionRefa12VideoToolboxE9ParameterO",
          "text": "Parameter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/processingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "processingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/processingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/updateParameter(values:)": {
      "abstract": [
        {
          "text": "Sets the value for one or more of the processing parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateParameter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "values"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/updateParameter(values:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateParameter(values:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession/updateparameter(values:)"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/parameters()",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/updateParameter(values:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/processingParameters"
      ],
      "title": "Configuring parameters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Parameters",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/BooleanParameter",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Details",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/FloatParameter",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/IntegerParameter",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/ListParameter",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/Values"
      ],
      "title": "Parameters"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/bool(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/float(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/int(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/list(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession/Parameter/subgroup(details:elements:)"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/title",
          "value": "VTRAWProcessingSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtrawprocessingsession/parameter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
