{
  "abstract": [
    {
      "text": "The position within the resource of the first byte requested.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestedOffset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAssetResourceLoadingDataRequest(py)requestedOffset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "requestedOffset"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int64V",
        "text": "Int64"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "requestedOffset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "requestedOffset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requestedOffset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int64V",
              "text": "Int64"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When all of the requested bytes that can be provided have been loaded—including the possible ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/contentInformationRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " data in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance that contains the receiver—the delegate should respond by invoking ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the ",
              "type": "text"
            },
            {
              "code": "requestedOffset",
              "type": "codeVoice"
            },
            {
              "text": " value is beyond the content length of the resource, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance is sent a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message without any prior invocations of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest": {
      "abstract": [
        {
          "text": "An object for requesting data from a resource that an asset resource-loading request references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingDataRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingDataRequest"
        }
      ],
      "role": "symbol",
      "title": "AVAssetResourceLoadingDataRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingdatarequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/currentOffset": {
      "abstract": [
        {
          "text": "The position within the resource of the next byte.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/currentOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentOffset"
        }
      ],
      "role": "symbol",
      "title": "currentOffset",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingdatarequest/currentoffset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestedLength": {
      "abstract": [
        {
          "text": "The length, in bytes, of the data requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestedLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestedLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestedLength"
        }
      ],
      "role": "symbol",
      "title": "requestedLength",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingdatarequest/requestedlength"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestedOffset": {
      "abstract": [
        {
          "text": "The position within the resource of the first byte requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestedOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestedOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestedOffset"
        }
      ],
      "role": "symbol",
      "title": "requestedOffset",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingdatarequest/requestedoffset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestsAllDataToEndOfResource": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the entire remaining length of the resource from the offest to the end of the resource is being requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestsAllDataToEndOfResource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestsAllDataToEndOfResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestsAllDataToEndOfResource"
        }
      ],
      "role": "symbol",
      "title": "requestsAllDataToEndOfResource",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingdatarequest/requestsalldatatoendofresource"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)": {
      "abstract": [
        {
          "text": "Provides data to the loading request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "respond"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "respondWithData:"
        }
      ],
      "role": "symbol",
      "title": "respond(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingdatarequest/respond(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a resource request from a resource loader object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoadingRequest"
        }
      ],
      "role": "symbol",
      "title": "AVAssetResourceLoadingRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/contentInformationRequest": {
      "abstract": [
        {
          "text": "The information for a requested resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentInformationRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetResourceLoadingContentInformationRequest",
          "text": "AVAssetResourceLoadingContentInformationRequest"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/contentInformationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentInformationRequest"
        }
      ],
      "role": "symbol",
      "title": "contentInformationRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/contentinformationrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()": {
      "abstract": [
        {
          "text": "Causes the receiver to treat the processing of the request as complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishLoading"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingRequest/finishLoading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishLoading"
        }
      ],
      "role": "symbol",
      "title": "finishLoading()",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetresourceloadingrequest/finishloading()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int64V": {
      "abstract": [
        {
          "text": "A 64-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int64",
      "type": "topic",
      "url": "/documentation/Swift/Int64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-Data-to-a-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestedLength",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/currentOffset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestsAllDataToEndOfResource"
      ],
      "title": "Providing Data to a Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "requestedOffset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestedOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-Data-to-a-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/respond(with:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestedLength",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/currentOffset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetResourceLoadingDataRequest/requestsAllDataToEndOfResource"
              ],
              "title": "Providing Data to a Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:K",
                    "text": "long long"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "requestedOffset"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest/title",
          "value": "AVAssetResourceLoadingDataRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingDataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingDataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1respond(with:)/title",
          "value": "respondWithData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1respond(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "respondWithData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1currentOffset/title",
          "value": "currentOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1currentOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading()/title",
          "value": "finishLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1finishLoading()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1requestedOffset/title",
          "value": "requestedOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1requestedOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestedOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1requestsAllDataToEndOfResource/title",
          "value": "requestsAllDataToEndOfResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1requestsAllDataToEndOfResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestsAllDataToEndOfResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1requestedLength/title",
          "value": "requestedLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingDataRequest~1requestedLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestedLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/title",
          "value": "AVAssetResourceLoadingRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoadingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1contentInformationRequest/title",
          "value": "contentInformationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetResourceLoadingRequest~1contentInformationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentInformationRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetresourceloadingdatarequest/requestedoffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetresourceloadingdatarequest/requestedoffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
