{
  "abstract": [
    {
      "text": "A constant that draws the halo effect inside the shape.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/inside"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIFocusHaloEffectPosition@UIFocusHaloEffectPositionInside",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inside"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIFocusHaloEffectPositionInside"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIFocusHaloEffect.Position.inside"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inside"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect": {
      "abstract": [
        {
          "text": "A visual focus effect that draws a halo around the focus item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusHaloEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusHaloEffect"
        }
      ],
      "role": "symbol",
      "title": "UIFocusHaloEffect",
      "type": "topic",
      "url": "/documentation/uikit/uifocushaloeffect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe positions for drawing the halo focus effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Position"
        }
      ],
      "role": "symbol",
      "title": "UIFocusHaloEffect.Position",
      "type": "topic",
      "url": "/documentation/uikit/uifocushaloeffect/position-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/automatic": {
      "abstract": [
        {
          "text": "A constant that automatically chooses a position for drawing the halo effect depending on the focus item and its containing view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusHaloEffectPositionAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UIFocusHaloEffect.Position.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uifocushaloeffect/position-swift.enum/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/inside": {
      "abstract": [
        {
          "text": "A constant that draws the halo effect inside the shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inside"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/inside",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusHaloEffectPositionInside"
        }
      ],
      "role": "symbol",
      "title": "UIFocusHaloEffect.Position.inside",
      "type": "topic",
      "url": "/documentation/uikit/uifocushaloeffect/position-swift.enum/inside"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/outside": {
      "abstract": [
        {
          "text": "A constant that draws the halo effect around the shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outside"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/outside",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusHaloEffectPositionOutside"
        }
      ],
      "role": "symbol",
      "title": "UIFocusHaloEffect.Position.outside",
      "type": "topic",
      "url": "/documentation/uikit/uifocushaloeffect/position-swift.enum/outside"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/outside"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIFocusHaloEffectPositionInside"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffectPositionInside"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UIFocusHaloEffect/Position-swift.enum/outside"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIFocusHaloEffectPositionInside"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum/title",
          "value": "UIFocusHaloEffectPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffectPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffectPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect/title",
          "value": "UIFocusHaloEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum~1outside/title",
          "value": "UIFocusHaloEffectPositionOutside"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum~1outside/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffectPositionOutside"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum~1automatic/title",
          "value": "UIFocusHaloEffectPositionAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffectPositionAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum~1inside/title",
          "value": "UIFocusHaloEffectPositionInside"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHaloEffect~1Position-swift.enum~1inside/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusHaloEffectPositionInside"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifocushaloeffect/position-swift.enum/inside"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifocushaloeffect/position-swift.enum/inside"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
