{"kind":"symbol","abstract":[{"text":"Provides the user-selected text.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/authenticationservices/ascredentialproviderextensioncontext/completerequest(withtexttoinsert:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/authenticationservices/ascredentialproviderextensioncontext/completerequest(withtexttoinsert:completionhandler:)"]}],"metadata":{"title":"completeRequest(withTextToInsert:completionHandler:)","role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"18.0","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"18.0","unavailable":false}],"navigatorTitle":[{"text":"completeRequestWithTextToInsert:completionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"Authentication Services"}],"externalID":"c:objc(cs)ASCredentialProviderExtensionContext(im)completeRequestWithTextToInsert:completionHandler:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completeRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTextToInsert","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"symbolKind":"method"},"identifier":{"url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withTextToInsert:completionHandler:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"completeRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTextToInsert"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS","iPadOS"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"completeRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTextToInsert"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS","iPadOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The text to insert.","type":"text"}],"type":"paragraph"}],"name":"text"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional work that the extension performs as a background-priority task after the request completes. The ","type":"text"},{"code":"expired","type":"codeVoice"},{"text":" parameter is ","type":"text"},{"code":"YES","type":"codeVoice"},{"text":" if the system prematurely terminates a previous non-expiration invocation of the ","type":"text"},{"code":"completionHandler","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"completionHandler"}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"At some point after you call this method, the system dismisses the associated view controller.","type":"text"}],"type":"paragraph"}]}],"sections":[],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","fragments":[{"text":"class ","kind":"text"},{"kind":"identifier","text":"NSString"}],"role":"symbol","title":"NSString","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"url":"/documentation/foundation/nsstring"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withTextToInsert:completionHandler:)":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Provides the user-selected text."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completeRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTextToInsert","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"title":"completeRequest(withTextToInsert:completionHandler:)","navigatorTitle":[{"text":"completeRequestWithTextToInsert:completionHandler:","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext/completeRequest(withTextToInsert:completionHandler:)","url":"/documentation/authenticationservices/ascredentialproviderextensioncontext/completerequest(withtexttoinsert:completionhandler:)","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"url":"/documentation/objectivec/bool","title":"BOOL","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext":{"navigatorTitle":[{"kind":"identifier","text":"ASCredentialProviderExtensionContext"}],"role":"symbol","url":"/documentation/authenticationservices/ascredentialproviderextensioncontext","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext","abstract":[{"text":"A mechanism that credential provider extensions use to communicate with the system.","type":"text"}],"title":"ASCredentialProviderExtensionContext","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASCredentialProviderExtensionContext","kind":"identifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"role":"symbol","title":"String","url":"/documentation/Swift/String","identifier":"doc://com.externally.resolved.symbol/s:SS","type":"topic","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.externally.resolved.symbol/s:Sb":{"identifier":"doc://com.externally.resolved.symbol/s:Sb","title":"Bool","role":"symbol","url":"/documentation/Swift/Bool","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}]},"doc://com.externally.resolved.symbol/s:s4Voida":{"identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"type":"topic","url":"/documentation/Swift/Void","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"title":"Void"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"18.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"18.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"completeRequestWithTextToInsert:completionHandler:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"completeRequestWithTextToInsert:completionHandler:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialProviderExtensionContext"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"completeRequestWithTextToInsert:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"expired","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS"]}]},"op":"replace"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"text","content":[{"type":"paragraph","inlineContent":[{"text":"The text to insert.","type":"text"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"Optional work that the extension performs as a background-priority task after the request completes. The ","type":"text"},{"type":"codeVoice","code":"expired"},{"text":" parameter is ","type":"text"},{"type":"codeVoice","code":"YES"},{"text":" if the system prematurely terminates a previous non-expiration invocation of the ","type":"text"},{"type":"codeVoice","code":"completionHandler"},{"text":".","type":"text"}]}]}]}},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeRequest(withTextToInsert:completionHandler:)/title","value":"completeRequestWithTextToInsert:completionHandler:","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext~1completeRequest(withTextToInsert:completionHandler:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"completeRequestWithTextToInsert:completionHandler:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext/title","value":"ASCredentialProviderExtensionContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext/fragments","value":[{"text":"ASCredentialProviderExtensionContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialProviderExtensionContext/navigatorTitle","value":[{"text":"ASCredentialProviderExtensionContext","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}