{
  "abstract": [
    {
      "text": "Passes the nearest strings, within a radius of a string in the vocabulary, to a block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NLEmbedding(im)enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "enumerateNeighborsForString:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "string"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maximumCount:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "maxCount"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maximumDistance:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLDistance",
              "text": "NLDistance"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "maxDistance"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "distanceType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NLDistanceType",
              "text": "NLDistanceType"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "distanceType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "usingBlock:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "neighbor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLDistance",
              "text": "NLDistance"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "distance"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "stop"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A string in the embedding vocabulary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "string"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The largest number of times the method calls ",
                  "type": "text"
                },
                {
                  "code": "block",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "maxCount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A means of calculating distance that determines which formula the method uses to evaluate a neighbor’s distance from ",
                  "type": "text"
                },
                {
                  "code": "string",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "distanceType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block with the following parameters:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A neighboring string.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "neighbor",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The distance from ",
                            "type": "text"
                          },
                          {
                            "code": "string",
                            "type": "codeVoice"
                          },
                          {
                            "text": " to the neighboring string.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "distance",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A Boolean that indicates whether to stop enumerating neighbors.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "stop",
                        "type": "codeVoice"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "block"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance": {
      "abstract": [
        {
          "text": "The distance between two strings in a text embedding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLDistance"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLDistance"
        }
      ],
      "role": "symbol",
      "title": "NLDistance",
      "type": "topic",
      "url": "/documentation/naturallanguage/nldistance"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType": {
      "abstract": [
        {
          "text": "The means of calculating a distance between two locations in a text embedding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLDistanceType"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLDistanceType"
        }
      ],
      "role": "symbol",
      "title": "NLDistanceType",
      "type": "topic",
      "url": "/documentation/naturallanguage/nldistancetype"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding": {
      "abstract": [
        {
          "text": "A map of strings to vectors, which locates neighboring, similar strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLEmbedding"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLEmbedding"
        }
      ],
      "role": "symbol",
      "title": "NLEmbedding",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distanceBetweenString:andString:distanceType:": {
      "abstract": [
        {
          "text": "Calculates the distance between two strings in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "distanceBetweenString:andString:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distanceBetweenString:andString:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distanceBetweenString:andString:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "distanceBetweenString:andString:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/distancebetweenstring:andstring:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings of a string in the vocabulary to a block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForString:maximumCount:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforstring:maximumcount:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings, within a radius of a string in the vocabulary, to a block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforstring:maximumcount:maximumdistance:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings of a location in the vocabulary space to a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforvector:maximumcount:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings, within a radius of a location in the vocabulary space, to a block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforvector:maximumcount:maximumdistance:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings near a string in the vocabulary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForString:maximumCount:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforstring:maximumcount:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:maximumDistance:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings, within a radius of a string, in the vocabulary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:maximumDistance:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForString:maximumCount:maximumDistance:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforstring:maximumcount:maximumdistance:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings near a location in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForVector:maximumCount:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforvector:maximumcount:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:maximumDistance:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings within a radius of a location in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:maximumDistance:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForVector:maximumCount:maximumDistance:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforvector:maximumcount:maximumdistance:distancetype:"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Finding-strings-and-their-distances-in-an-embedding",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:distanceType:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:maximumDistance:distanceType:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:distanceType:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:maximumDistance:distanceType:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:distanceType:usingBlock:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distanceBetweenString:andString:distanceType:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance"
      ],
      "title": "Finding strings and their distances in an embedding"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType/title",
          "value": "NLDistanceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistance/title",
          "value": "NLDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLEmbedding/title",
          "value": "NLEmbedding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLEmbedding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLEmbedding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nlembedding/enumerateneighborsforstring:maximumcount:maximumdistance:distancetype:usingblock:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
